### ISSUE TITLE
Altar.json

### ISSUE THREAD

**Issue by Keiko403** [Iskallia/Vault-public#1]
Looks like vault altar has a chance to roll “minecraft:prismarine_bricks” 2x

sorry for snooping, just trying to learn and spotted this. Don’t know what would happen if the altar rolled this.

**Comment by KaptainWutax** [comment]
The default configs are for dev, wait for the actual release to get the good ones.

**Comment by Keiko403** [comment]
Cheers Kap. Also well done to you and the rest of the team on this pack. Good luck with the public release too
