### ISSUE TITLE
When placing a Vault Boss Statue in creative, game crashes

### ISSUE THREAD

**Issue by nicktherushfan** [Iskallia/Vault-public#101]
Game crashed while placing a Vault Boss Statue given through creative. Attached is the crash log. To recreate what happened, search "Vault Boss Statue", give to yourself through JEI, then click on top of a vault boss crate.

[crash-2021-03-27_02.58.39-server.txt](https://github.com/Iskallia/Vault-public/files/6215886/crash-2021-03-27_02.58.39-server.txt)

**Comment by Nimothy** [comment]
Hi @nicktherushfan, please see issue #13 this is not a bug, or something that will be fixed.

**Comment by nicktherushfan** [comment]
Sounds good, thanks!
