### ISSUE TITLE
Cant create server from provided server files on curseforge

### ISSUE THREAD

**Issue by AliKamalddin** [Iskallia/Vault-public#1014]
when launching the forge jar nothing happens other than the logs folder being made, using the minecraft_server.1.16.5 jar file creates a vanilla server, what do i do in order to create a server that is joinable and playable? i am using Java 8 update 333 so i dont think its a java version issue, i think a readme would be nice to show how to create a server.

![image](https://user-images.githubusercontent.com/108277937/178316602-ced18749-8df6-4b16-bdc4-6e5b336a1afa.png)

**Comment by chico1992** [comment]
Actually it's a java issue any versions newer then java 8 312 won't work

**Comment by AliKamalddin** [comment]
alright, that worked, thank you, however i am getting a cant connect to server error when i use localhost:25569.
![image](https://user-images.githubusercontent.com/108277937/178322167-a95ed86f-c9ab-42f1-91ac-713276f08839.png)
![image](https://user-images.githubusercontent.com/108277937/178322210-91263d48-7333-44d1-a54c-276e015f5a36.png)

**Comment by AliKamalddin** [comment]
forgot to add, the server-port is set to 25569 and my server-ip is set to my internal ipv4 address, i couldnt find Java 8 312 so i settled for 311, not sure if thats the issue

**Comment by chico1992** [comment]
Leave the ip in the server.properties as 0.0.0.0

**Comment by AliKamalddin** [comment]
thanks! worked like a charm
