### ISSUE TITLE
Village Room Portal Not Working

### ISSUE THREAD

**Issue by EnderSpy29** [Iskallia/Vault-public#1016]
**Village Room Portal Has Not Worked**
I've Run many Vaults, And this Being The Only Village Room I Had Found With A Portal Room, I Was Excited. So I Cleared The Area, And Put In The Last Ender Eye, Sadly though For Some reason It Did Not Activate And turn Into Gilded Chests.

**To Reproduce**
No Idea, ive Only Found one portal Room

**Expected behavior**
I expected The portal Frame To Turn Into Gilded Chests.

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- Multiplayer, but it was a solo vault
- modpack version: 1.13.4

**Comment by chico1992** [comment]
Enable command blocks on the server

**Comment by EnderSpy29** [comment]
i will do that right now!

**Comment by EnderSpy29** [comment]
it has worked
