### ISSUE TITLE
Execute doesnt do damage

### ISSUE THREAD

**Issue by Bright7185** [Iskallia/Vault-public#102]
Sorry for iskall in the background watching while testing this is on max execute 

https://user-images.githubusercontent.com/17716203/112726397-19827f80-8f15-11eb-97a3-2756492abc97.mp4

**Comment by nicktherushfan** [comment]
Execute now deals damage based on missing health. To be most effective, the boss/mob needs to be at or below half health.

**Comment by Nimothy** [comment]
This looks to be working correctly. Execute works on the percentage of hearts lost. As the iron golem￼ is on full health, execute would seem to have no effect.

**Comment by Bright7185** [comment]
Sorry forgot that it updated
