### ISSUE TITLE
Raffle Vault in Multiplayer

### ISSUE THREAD

**Issue by sethlans01** [Iskallia/Vault-public#1026]
**Describe the bug**
I am playing VH on a multiplayer server with a friend and we usually run the vaults in a party to play together.
We got our first raffle seal and I entered the vault with the party on, but only I entered the vault, while my friend stayed in the Overworld.

**To Reproduce**
1. Create a Raffle Crystal
2. Create a party with at least one person
3. Enter the Vault

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.13.4

**Comment by Pancakezombie2** [comment]
Raffle seals are ment to be solo
