### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Tox1c89** [Iskallia/Vault-public#1033]
Me and my friend wanted Vault Hunters server so we decided to create one (we have some experience with vanilla minecraft server).

We have been working on it past 2 days and we encountered some problems. So we decided to post it on Github.

**RAM allocation:** 10 GB
**Java version:** Java 1.8.0_342
**Forge version:** 1.16.5-36.2.34
**Server version:** 13.4
**Word type:** Server

### Testing
Overworld dim is working properly.

So we tried few thing - opening Pandora boxes, eating special Apples, using Star cores, Traders, rolling Vault Gear

It was fine - working right as it should!

### Cant put Vault Rock into Vault Altar
When I tried putting Vault Rock into Vault Altar on client side nothing happened. On the server side we got some errors.

_-cut out server log right right after I put Vault Rock into Vault Altar:_ https://pastebin.com/mBuuAAci

_-full server log:_  https://pastebin.com/3Rh7MCYp

Server was still up and running. Nothing serious.

**The Vault dimension crashing our server**
When i teleported to the Vault dimension it seemed fine. We had some performance issues (I thing that's normal when generating new dim).

`Can't keep up! Is the server overloaded? Running 4928ms or 98 ticks behind`

After 5 second the server crashed.

_-cut out server log right right after I entered the Vault:_ https://pastebin.com/XhBxDnEd

_-full server log:_  https://pastebin.com/3Rh7MCYp

**Comment by kvermaat** [comment]
had the same problems i did the following:

lower to 8gb (had 20gb) this pack cannot run higher than that.
Server mods added: Ferritecore, Starlight and AutoRestart
settings: restart every 12 hours and restart after no players online for 1 hour
clients added: Betterfpsdist, Lazydfu and optifine
optifine options if you want to setup fast:
[optionsof.txt](https://github.com/Iskallia/Vault-public-S1/files/9386496/optionsof.txt)

**Comment by kvermaat** [comment]
java version
![image](https://user-images.githubusercontent.com/1015046/185735780-8d0114a8-37df-49fa-af0c-237519f5e54d.png)

**Comment by Tox1c89** [comment]
> had the same problems i did the following:
> 
> lower to 8gb (had 20gb) this pack cannot run higher than that. Server mods added: Ferritecore, Starlight and AutoRestart settings: restart every 12 hours and restart after no players online for 1 hour clients added: Betterfpsdist, Lazydfu and optifine optifine options if you want to setup fast: [optionsof.txt](https://github.com/Iskallia/Vault-public-S1/files/9386496/optionsof.txt)

Thanks man, lowering the RAM worked!
I would never imagine that could cause an issue.
