### ISSUE TITLE
vault broken!!

### ISSUE THREAD

**Issue by monsterT2008** [Iskallia/Vault-public#108]
when you enter a vault the timer doesn't start even after 10 munities and all chests are empty and no mobs spawn

**Comment by ImreBoersma** [comment]
Are you sure you downloaded the latest version of the modpack. Similar issues have been reported: #84 #85 #93

**Comment by monsterT2008** [comment]
yes! i downloaded it from iskall's discord

**Comment by monsterT2008** [comment]
its fixed now!
