### ISSUE TITLE
Dank Storage - Cannot Lock items into Danks.

### ISSUE THREAD

**Issue by StrykForce** [Iskallia/Vault-public#109]
When trying to lock any item (Using the button CTRL) in any kind of dank, it does not change the desired slot inside the dank to a red color, as it is supposed to normally do. No other control in the control settings is affecting this.

In order to reproduce this behavior, take a dank, any item you wish to lock, and press CTRL.

It is expected to have the desired inventory slot, that one wishes to lock, should turn to a red box/border when pressing CTRL.

World/Modpack info:
- Singleplayer world.
- 1.0.1 The_Vault

As stated, no other controls is affecting this.

**Comment by magicalex234** [comment]
don't know if this applies, but if you're on a mac, you need to hit CMD, not CTRL

**Comment by StrykForce** [comment]
> don't know if this applies, but if you're on a mac, you need to hit CMD, not CTRL

I am on a windows computer, not a mac. It would probably act the same way still, but im not on mac so I dont know.

**Comment by grandwigg** [comment]
I don't believe this problem is unique to Vault Hunters. I have the same issue on Enigmatica 6 as well as Vault Hunters.  It is possibly due to another mod the two packs have in common.  Using MultiMC 5 On windows 10.

**Comment by bmemike** [comment]
@grandwigg You are correct. This is not related to VH at all.

I've had luck in other modpacks by making sure my off-hand is empty when I'm trying to lock the cell.

**Comment by Peskybirdofdoom** [comment]
I am reasonably sure that if you try CTRL + Right clicking it should work. If not I have no idea what's wrong

**Comment by StrykForce** [comment]
> I am reasonably sure that if you try CTRL + Right clicking it should work. If not I have no idea what's wrong

This worked for any future people. Thank you!
