### ISSUE TITLE
vault timer

### ISSUE THREAD

**Issue by toinedeman** [Iskallia/Vault-public#11]
hi, i enterd a vault and the times didnt count down

**Comment by scalda** [comment]
this is a duplicate of [issue 6](https://github.com/Iskallia/Vault-public/issues/6)

**Comment by toinedeman** [comment]
that one was when you kild a bos but i got in when entering or is that stil the same?

**Comment by scalda** [comment]
it's all connected

**Comment by toinedeman** [comment]
k thanks :)

**Comment by KaptainWutax** [comment]
Fixed in 1.0.1.
