### ISSUE TITLE
Dragon Etching for Vault Chestplate not working

### ISSUE THREAD

**Issue by EliteForce1** [Iskallia/Vault-public#110]
**Describe the bug**
I placed the dragon etching thing on my vault armor, its the one that makes you have an elytra without needing an actual elytra on your back. Now its not making me able to glide with the correct armor piece on

**To Reproduce**
1. place a dragon etching on a vault piece
2. try to glide

**Expected behavior**
being able to glide with a chestpiece on

**Screenshots or Crash Report**
screen shot: 
![2021-03-28_00 24 22](https://user-images.githubusercontent.com/39034729/112737600-fb8c3d80-8f5b-11eb-80a8-1e88e8d6fc1d.png)

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version = 1.0

**Comment by jmilthedude** [comment]
Do you have the etching on just the helmet or all gear? For the etchings to have effect, you need to have them on and wear all 4 armor pieces.

**Comment by EliteForce1** [comment]
> Do you have the etching on just the helmet or all gear? For the etchings to have effect, you need to have them on and wear all 4 armor pieces.

yeah thx, after trying out some stuff it worked
