### ISSUE TITLE
Scavenger Crates not opening on sky vault

### ISSUE THREAD

**Issue by crazzipenguin** [Iskallia/Vault-public#1108]
I completed a sky vault scavenger run and got rewarded with the crate, but I can't open it. Don't know if its a special button to press or just right click it. I can't get the rewards from it.

1. Complete sky vault scavenger run.
2.Place down crate
3.Try to open it
4.

**Expected behavior**
Though I would open it and get gear

**Info (please complete the following information):**
- World Type: Single player (sky vault)
- The_Vault Version 1.18

**Comment by jmilthedude** [comment]
Crouch and right click it.

**Comment by crazzipenguin** [comment]
Tried to crouch and right click it nothing happened. I also check my controls to see if there were some conflicting controls for it. Nothing that I could see was.

**Comment by jmilthedude** [comment]
So placing the crate, shift+right click doesn’t work. hmmm i’ll investigate

**Comment by crazzipenguin** [comment]
HMMM, just figured it out why, I had a food item in my off hand took it out and was able to open it.
