### ISSUE TITLE
Vault crystal has the wrong growth order

### ISSUE THREAD

**Issue by arwilson51** [Iskallia/Vault-public#1109]
In the sky vaults world, the budding crystal block grows the crystals in the wrong order. This is caused by the crystal_bud_medium.json and crystal_bud_small.json files being backwards (the medium file references the small png and the small one references the medium png)
should be fixed by just switching the files around (still needs to be tested)
![image](https://user-images.githubusercontent.com/119262684/204160600-9220df97-19d3-432c-9628-485b2c4dcf6d.png)

**Comment by arwilson51** [comment]
Switching the text in the files (or renaming them exactly, which has more room for error if you rename incorrectly) works properly. Crystals grow in the correct order after this

**Comment by codetaylor** [comment]
Good catch, thanks!
Fixed in-dev
