### ISSUE TITLE
Forge and Magma error, "the-vault" mod gets recognize as a client side mod. label:"vault mod" 

### ISSUE THREAD

**Issue by MrShirker** [Iskallia/Vault-public#1112]
**Describe the bug**
I created a magma server and i'm not able to start it because of "the-vault" mod.
 #I also created a normal forge server and the problem still remains#

**To Reproduce**
I created a server using pufferPanel and the magma template with the last magma version: 69c2d84e
The server doesnt havve plugins yet.

**Expected behavior**
Dont know if the problem has to do with magma or with the mod. If i delete "the-vault" mod, the server runs fine.

**Screenshots or Crash Report**
This is my error log: https://pastebin.com/iENrCv1b

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version: 1.0.1

EDIT:
It works fine with the last version of forge, so i'm good for now.

**Comment by samuelkanfer** [comment]
@MrShirker What version of forge were you able to get it to work with Magma?

**Comment by jmilthedude** [comment]
For future reference, we will not support any third party platform other than forge.
