### ISSUE TITLE
Monolith Crate after Death

### ISSUE THREAD

**Issue by Noerrells** [Iskallia/Vault-public#1113]
**Describe the bug**
Getting a Monolith crate after death in a beginners grade Vault

**To Reproduce**
1. sky Vault crystal (beginners Grate)
2. complete Monolith
3. death
4. 

**Expected behavior**
not getting a crate

**Screenshots or Crash Report**
sorry no

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version [äh 1.18.2-alpha-0.0.1]

**Additional context**

**Comment by arwilson51** [comment]
maybe a bit more detail? like what you were doing before it happened, what led up to the events of the bug? a little more detail will be of more help to the devs

**Comment by jmilthedude** [comment]
We are aware and this is fixed in the next update.
