### ISSUE TITLE
Selecting available "Completion" bounties crashes client.

### ISSUE THREAD

**Issue by WindsWatcher** [Iskallia/Vault-public#1114]
**Describe the bug**
While accessing the Bounty Table, I have 3 bounties available.  2 completion, and one mining bounty.  When selecting one of the completion items to view, it hard crashes my client.

**To Reproduce**
1.Craft Bounty Table,
2.Select one of the "Completion" options.

**Expected behavior**
Should view the available bounty without closing client.

**Screenshots or Crash Report**
[crash-2022-11-27_23.23.01-client.txt]
[crash-2022-11-27_23.19.35-client.txt](https://github.com/Iskallia/Vault-public-S1/files/10101036/crash-2022-11-27_23.19.35-client.txt)
(https://github.com/Iskallia/Vault-public-S1/files/10101034/crash-2022-11-27_23.23.01-client.txt)

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server] Iskallium server: Can-05, Spring.
- The_Vault Version [e.g. 1.0.1]  1.18.2-2.0.8.763

**Additional context**
None.

**Comment by Kveeez** [comment]
Same issue, only with Completion, others bounties work fine, dont know yet how to fix, playing singleplayer

**Comment by jmilthedude** [comment]
Yea it is a bug with the monolith bounty. Is fixed next patch.

**Comment by Kveeez** [comment]
Cool, thx
