### ISSUE TITLE
No block interactions within vault

### ISSUE THREAD

**Issue by KobeLiesenborgs** [Iskallia/Vault-public#112]
**Describe the bug**
No block interaction possible within the vault (block placement, breaking etc)

**To Reproduce**

Unknown steps to reproduce. 
Issue does persist on the VH-bariton server across multiple users.

**Expected behavior**
Block interactions (opening chests, placing blocks, removing blocks etc).

**Screenshots or Crash Report**
[Video showing the behaviour](https://www.youtube.com/watch?v=px_On8O0rzg)

**Info (please complete the following information):**
- World Type: Server, specifically VH-bariton hosted for t2+ subs
- The_Vault Version 1.0.1

**Additional context**
The issue persists across multiple users and makes the vaults unrunable.

**Comment by boogiebookie** [comment]
Iskall posted about something similar on his discord. he said that spawn protection may stop non-OP players from using vaults properly.

**Comment by Cleggy1012** [comment]
I had the same issue on the VH-Bariton server on 28/03/2021 5 AM GMT. IGN - Cleggy

[Video showing the issue](https://studio.youtube.com/video/jCrpT2kJ6x0/edit)

**Comment by KobeLiesenborgs** [comment]
Issue resolved, it was server specific (world border issues)
