### ISSUE TITLE
Game crashed while using bounty table.

### ISSUE THREAD

**Issue by ezdoes** [Iskallia/Vault-public#1127]
**Describe the bug**
I was using the bounty table.
Game crashed when i click a specific completion type bounty in the available line.
The other two bounties are fine to click.

**Screenshots or Crash Report**

![image](https://user-images.githubusercontent.com/56550676/204570546-1ae83bac-fa79-42d1-90a6-0a5899a38c69.png)
[crash-2022-11-29_23.09.55-client.txt](https://github.com/Iskallia/Vault-public-S1/files/10114421/crash-2022-11-29_23.09.55-client.txt)

**Info (please complete the following information):**
- World Type: Single player
- The_Vault Version 0.0.1

**Comment by Sportlife01** [comment]
I had the same thing happen to me.

**Comment by jmilthedude** [comment]
Duplicates #1114 , fixed in next patch.
