### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by wgnd** [Iskallia/Vault-public#1132]
ok so i had a ryzen 5 2400g with 8gb of ram and a r7 360 with 2gb and i was able to play the modpack (with some freezing here and there) but now i bought a pc with ryzen 5 4500, a gtx 1650 4gb and 16 gb (plus a sdd) and i just CANT PLAY the modpack.. the menu screen freezes more than it did with my old ass pc (i was able to create a world with that one and played for a while) and i can't even create a world (i shows a data pack error) can someone help me please? repairing didn't do anything.

edit: ok so got it to work but the games is still freezing a lot.. it runs at 400 fps but it freezes all the time and again i say.. HELP

**Comment by CatLuvrs54** [comment]
Check the graphics drivers for updates, make sure you've got the latest java version installed, and check your allocated ram settings in curseforge (I think the app automatically sets itself to like 2 which isn't enough for a pack like Vault Hunters). Most likely you're just missing some update or setup with the new pc.

**Comment by wgnd** [comment]
you know when you do eveything but the obvious one? hahaha everything was updated and the ram was fine but i forgot about the java so thanks for reminding me
