### ISSUE TITLE
Bounty Table Complete any vault quest not working

### ISSUE THREAD

**Issue by Adamhalal101010** [Iskallia/Vault-public#1134]
The Bounty that requires the player to complete ANY Vault does not work.

Accepted a Bounty that requires the completin of ANY vault
Completed both a SCAV and a MONOLITH and neither of them allows me to claim the prize in bounty table

![image](https://user-images.githubusercontent.com/119504405/204801676-efe07267-2207-4603-87aa-03e8530c16e0.png)
![image](https://user-images.githubusercontent.com/119504405/204801737-25556d72-5c70-466d-9fcf-638654c739b4.png)

World Type: Iskalia server EU-02 Hercules
The_Vault Version 1.18 first release

Both vaults were in a party. Might be the problem. Alone I have not completed yet.

**Comment by jmilthedude** [comment]
This has been fixed in next patch.
