### ISSUE TITLE
Multiple plentiful modifiers not working

### ISSUE THREAD

**Issue by JacobRoelandt** [Iskallia/Vault-public#1135]
We ran a coop vault with the following modifiers : living, chunky mobs, furious, 2x plentiful, frail, phoenix. In this vault close to zero chests, coin piles or vault ores spawned. For example, my teammate found a crystal cave room, you would expect him to have found a boatload of vault ores in there but he only found 3, all the other ores he found were just vannilla. Or when I was clearing out POI's there were no chests to be found. In this whole vault, which we ran for 20 minutes, i found 3 chests whiich were not even generated by the living modifier, just normal regular wooden chests.
![2022-11-30_15 45 25](https://user-images.githubusercontent.com/119521575/204853098-4b02e4b2-2746-4f91-838d-06b03aeec651.png)

**Comment by arwilson51** [comment]
really interesting. in the vault_modifiers.json file it says it is %20 more vault ores. It also has that formatting error where when you have two plentiful it doesnt format the %d%% properly, where as if you only have one it does format properly. I believe that its having trouble adding the two plentiful modifiers together. Ill have to spend some time to look myself, but hopefully my observation will help lead the actual devs in a right direction

**Comment by jmilthedude** [comment]
This is a known bug and is fixed in the next patch.
