### ISSUE TITLE
Liquids and Obsidian Don't Work

### ISSUE THREAD

**Issue by Dungewar** [Iskallia/Vault-public#1138]
**Bug Description**
This bug doesn't allow to pick up water and lava, as well as preventing you from breaking obsidian.

**To Reproduce**
1. Enter the vault with a bucket of water
2. Place water next to lava
3. Try to pick up lava
4. Try to break obsidian

**Expected behavior**
The water makes obsidian with the lava.
When you try to break the obsidian, the obsidian doesn't break, and lava and water can't be picked up.

**Info (please complete the following information):**
- World Type: Singleplayer, SkyVault
- The_Vault Version: alpha-0.0.1

**Additional context**
I am at level 4, using the level 0 crystal that naturally generates.

**Comment by jmilthedude** [comment]
Silly question, but you are using a diamond pick at least yea? Also, lava in normal vault hunters is disabled in vaults so probably the same thing in sky vaults. I’ll check if this is intended and if so, how you are meant to acquire lava.

**Comment by Dungewar** [comment]
Note: After leaving the vault, I got the lava bucket in my hand, working.
Yes, I am using a diamond pickaxe.

**Comment by Dungewar** [comment]
The lava doesn't work in the vault intentionally, and the obsidian breaking too I assume.
