### ISSUE TITLE
Bounties not working with backup of world. 

### ISSUE THREAD

**Issue by Vaultori** [Iskallia/Vault-public#1141]
**Describe the bug**
When using a backup of my world. Scavenger bounties do not seem to work anymore. 

**To Reproduce**
1. Run a backup world 
2. Select a scav bounty 
3. Run scav bounty 

**Expected behavior**
I just excepted to gain progress/complete bounty when doing it’s task. 

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Single Player 
- The_Vault Version 1.18 initial release

**Additional context**
none

**Comment by jmilthedude** [comment]
I'm not sure what you mean but there are bugs with the bounties in the current version that will be fixed in the next update. This is likely your problem. Please reopen if you still have this issue after the next patch.
