### ISSUE TITLE
Bounty crashes game

### ISSUE THREAD

**Issue by therealfox92** [Iskallia/Vault-public#1142]
**Describe the bug**

**To Reproduce**
1.Clicked on new bounty
2.Crashes Game
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- Single Player
- Vault Hunters 3rd Edition alpha 0.0.1

**Additional context**

**Comment by jmilthedude** [comment]
Duplicates #1114. Fixed in next patch
