### ISSUE TITLE
Vault doll not dropping right amount of items

### ISSUE THREAD

**Issue by Durmad1** [Iskallia/Vault-public#1143]
**Describe the bug**
Just finished a vault with a friends vault doll on my head, vault had a gilded modifier and I looted 56 gilded chests and a few other ones and some ores. After I was completed the vault friend opened the doll and only got Exp, ores and items from non gilded chests (happened before with other tipe of chest but on stream they showed dolls working). Doll was about 40% loot and ~60 Exp

**To Reproduce**
1.  Take a vault doll in the vault
2.  Get a gilded modifier and only look chests that spawn from them 
3.  Complete the vault and get the loot out of the doll

**Expected behavior**
Vault doll giving correct items

**Screenshots or Crash Report**

![Looted items 1](https://user-images.githubusercontent.com/92090367/205359324-7b1fbfce-18a0-44a3-a27a-7771cfc0c8d2.png)
![Looted items 2](https://user-images.githubusercontent.com/92090367/205359334-da081b2a-d4f5-43fd-8de6-673f8859dbe8.png)
![Doll loot](https://user-images.githubusercontent.com/92090367/205359345-7197ee42-780e-4bd2-8310-8628e0c002e4.png)

**Info (please complete the following information):**
- World Type: Iskallia server Eu 04 sage
- Vault hunters 3rd edition alpha-0.0.1

**Additional context**
I'm thinking its because of the modifier but might be wrong

**Comment by jmilthedude** [comment]
This is a known bug and is fixed in the next version.
