### ISSUE TITLE
Died by the vault timer after successfully bailed

### ISSUE THREAD

**Issue by ezdoes** [Iskallia/Vault-public#1157]
**Describe the bug**
I went into a obelisk vault, and I bailed with about a minute left.
Then in my overworld house, I suddenly died by the vault timer and get vault exp again.
But I was able to find the body.
It only happened once.

- World Type:  Single Player 
- The_Vault Version alpha 0.0.2

**Comment by d0zzer2** [comment]
Did you get a crystal with /give or creative? This happens if you do that.

**Comment by jmilthedude** [comment]
Creative menu crystal is fine but you shouldn’t use the give command unless you know what you’re doing cause there is required NBT. Either way, this seems like it could have been lag or something like that. I’m going to close this but let us know if you can reproduce.
