### ISSUE TITLE
Optifine Crash Upon World Gen

### ISSUE THREAD

**Issue by ThatAmishKid** [Iskallia/Vault-public#1158]
**Describe the bug**
Loading optifine 1.18.2 into vault hunters fails to launch the world. Launcher opens, and menu loads fine, but crashes past 0%. 

**To Reproduce**
1. Input 118.2 optifine mod into folder, 
2. Open any world

**Expected behavior**
World load screen pops up, then game crashes. 
**Screenshots or Crash Report**
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'

**Info (please complete the following information):**
- World Type: Single player, survival
- The_Vault Version

**Additional context**

**Comment by Pancakezombie2** [comment]
Vault Hunters doesn't support optifine

**Comment by ThatAmishKid** [comment]
I could have sworn I saw that it was added for season 2, and 1.18.2, but, that would make sense. 
What other optimizing mods are there? I need one to run Vault Hunter smoothly

**Comment by Pancakezombie2** [comment]
Iskall suggests rubidium as the mod to use

**Comment by jmilthedude** [comment]
As previously mentioned, we will not support optifine. Definitely go with rubidium.
