### ISSUE TITLE
Sword prefix "Sweeping hit chance"  not working

### ISSUE THREAD

**Issue by ezdoes** [Iskallia/Vault-public#1163]
**Describe the bug**
a vault sword with 63% Sweeping hit chance(T1)
only did 1 sweeping attack damage forever.
What's the point of this prefix?
and it's hard to farm Pillagers without sweeping edge, so sad.

**Info (please complete the following information):**
- World Type: Single Player 
- The_Vault Version 0.0.2

**Comment by jmilthedude** [comment]
lol why are you sad about a bug? Let me tell you the point of the prefix: It is to apply sweeping edge when attacking. 

It is currently a bug which is going to be fixed in the next public release.
