### ISSUE TITLE
Singleplayer world cannot load

### ISSUE THREAD

**Issue by steven-msk** [Iskallia/Vault-public#1169]
**Describe the bug**
When I enter a singleplayer world, it loads until the terrain starts to generate, but it fail and it just crashes with either an error saying "java.lang.NoSuchMethod"

**To Reproduce**
1. opened vault hunters
2. loaded a new singleplayer world
3. started to load the terrain
4. client crashed

**Expected behavior**
The world ,in which i have selected to load, to work and spawn me into the world.

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

[crash-2022-12-10_17.51.21-server.txt](https://github.com/Iskallia/Vault-public-S1/files/10200424/crash-2022-12-10_17.51.21-server.txt)

![image](https://user-images.githubusercontent.com/107042690/206864726-0245bd71-2972-4344-89d3-2dec713c53e5.png)

![image](https://user-images.githubusercontent.com/107042690/206864747-f8d82d4b-6127-4ffd-be12-b5482c5ed600.png)

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]  ------> Singleplayer
- The_Vault Version [e.g. 1.0.1] ---------> The Vault 3rd edition-alpha-0.0.2

**Additional context**
Is OptiFine compatible with this vault hunters edition? I added the mod in the mod list and I dont know if that is what makes it crash. Also the version for OptiFine that i added is 1.18.2.

**Comment by jmilthedude** [comment]
We do not support optifine. Use Rubidium.
