### ISSUE TITLE
Vault Gear stuck in AE System

### ISSUE THREAD

**Issue by joshuaepstein** [Iskallia/Vault-public#118]
**Describe the bug**
When I put a vault gear item inside of my applied energistics system, I can't get it out

**To Reproduce**
1. Got vault armour/axe/dagger/sword
2. Put in AE System
3. Cant get the item out of the system...

**Expected behavior**
Not sure what will happen, not sure if this is a vault hunters issue

**Info (please complete the following information):**
- Singeplayer but opened to lan
- the_vault version 1.0.1

**Comment by MVPlel** [comment]
This has been known to be a bug for a while and pretty sure it will be sorted soon.

**Comment by joshuaepstein** [comment]
Ok, is that why iskall puts his gear in barrels?

**Comment by MVPlel** [comment]
Yeah
