### ISSUE TITLE
game freezes computer with 100% processor usage.

### ISSUE THREAD

**Issue by guigadj** [Iskallia/Vault-public#1181]
After some time playing (between 1 and 5 minutes) the game starts heavily freezing, stopping videos and lagging my cursor, it happens inside vaults and during worldgen when im flying around, noticibly during chunk border crossing, but not exclusively. im unable to play the game because when it happens it literally kills me in the vault.. somehow mobs still can move and attack during the freeze. last place i went through this trouble in particular i was in a desert themed vault at level 14. thought on reporting because this issue just start after i update, but going back wont make it stop.

Info:
- World Type: single player
- The_Vault Version 0.0.3h

Computer specs:
i5 9600k, 32gb ram(allocated 8 to game), 1060ssc, running on SSD.

**Comment by Steakchest** [comment]
I'm having the same issue in a different vault theme. Had no issues in 0.0.1, updated straight to 0.0.3. Everything normal outside of vaults, CPU spikes to 95%+ after only a few minutes in the vault. If I reload, it'll just happen again in the same amount of time.
Ryzen 5 2600, 16GB RAM(8 allocated), AMD GTX 580.

**Comment by Steakchest** [comment]
From the known issues portion of the VH Discord:

"Vault Hunters 3rd Edition version 0.0.3 performance is lowered compared to version 0.0.2, as well as its stability - resulting in the game randomly crashing upon entering the Vault. This is caused by unintended addition of the World Edit mod into the modpack structure."
 
Go to the mods folder and delete "worldedit-mod-7.2.10.jar"

I've applied this fix and it resolved my issues.

**Comment by guigadj** [comment]
> From the known issues portion of the VH Discord:
> 
> "Vault Hunters 3rd Edition version 0.0.3 performance is lowered compared to version 0.0.2, as well as its stability - resulting in the game randomly crashing upon entering the Vault. This is caused by unintended addition of the World Edit mod into the modpack structure."
> 
> Go to the mods folder and delete "worldedit-mod-7.2.10.jar"
> 
> I've applied this fix and it resolved my issues.

it did resolve for me too, there is no more killer lag for me. thanks a lot for the help!
