### ISSUE TITLE
Vault altar not giving any recipe 

### ISSUE THREAD

**Issue by Tanten501st** [Iskallia/Vault-public#1186]
**Describe the bug**
The vault altar is not giving me a recipe even after destroying it and using another stone

I'm not the most sure on how it happened, but I think it went along something like this
**Steps to reproduce the behavior**
1.put in an empty crystal in the altar
2.nearly complete the recipe 
3.(maybe) run a vault
4.exit the game (perhaps completely) 
5.enter the game again

Their might be some other variables that I'm not sure of
 
**Expected behavior**
When i left the world for the night i hadn't finished making the crystal and thought that I would just complete it the next day without any issues 
**Screenshots or Crash Report**
![2022-12-16_11 13 45](https://user-images.githubusercontent.com/120718527/208076081-c41c9b5e-6ef3-4705-9bfe-f066bbddc5a9.png)

**Info**
The world type is single player with cheats turned on and bonus chest on
The version I'm running is alpha 0.0.3h

**reaching me if need be**
I'm easier to reach on my steam account than here as I don't really frequent this site
https://steamcommunity.com/profiles/76561198107330620/

**Comment by cdwalter** [comment]
I'm having the exact same issue. My altar looks just like this. It did happen after I exited a vault, and I saw the alter showed no items. I had run at least five vaults in the hour before this. I am at level 4. I did break the alter and try new rocks. I also crafted a new altar. I also restarted the client. Not sure what other info you need.

**Comment by cdwalter** [comment]
I also opened a creative world and the altar showed items after I added the rock. I crated the crystal and opened the vault, so it's definitely an issue related to only one world.

**Comment by jmilthedude** [comment]
This is fixed in next update. Reopen if you still have a problem after the next release.
