### ISSUE TITLE
Abandoned Bounty Timer Skip

### ISSUE THREAD

**Issue by SirReBus** [Iskallia/Vault-public#1190]
You are able to spend Vault Bronze to skip the 8hr timer on abandoned Bounty's 

1.Claim bounty
2.Abandon bounty 
3. Select said bounty 
4.Spend Bronze to skip wait timer for bounty / reroll 

Latest version 4.1

**Comment by jmilthedude** [comment]
This was intended. Initially, rerolling was designed to work on any bounty. As of next patch though, this has been removed and only available bounties can be rerolled.
