### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by Ph-Kritos** [Iskallia/Vault-public#1197]
**Describe the bug**
Server crashes a moment after putting a vault stone on a vault altar.

**To Reproduce**
1. Put a vault Stone on a vault altar
2. Server is disconnected

**Expected behavior**

**Screenshots or Crash Report**

>  Description: Ticking block entity
> 
> java.lang.NullPointerException: Cannot invoke "iskallia.vault.altar.AltarInfusionRecipe.getRequiredItems()" because the return value of "iskallia.vault.block.entity.VaultAltarTileEntity.getRecipe()" is null
>         at iskallia.vault.block.entity.VaultAltarTileEntity.updateDisplayedItems(VaultAltarTileEntity.java:152) ~[the_vault-1.18.2-2.0.10.869.jar%23152!/:1.18.2-2.0.10.869] {re:classloading}
>         at iskallia.vault.block.entity.VaultAltarTileEntity.tick(VaultAltarTileEntity.java:140) ~[the_vault-1.18.2-2.0.10.869.jar%23152!/:1.18.2-2.0.10.869] {re:classloading}
>         at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:classloading}
>         at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:classloading}
>         at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorWorld,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinWorld,pl:mixin:A}
>         at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.redirect$zna000$tickChildren(MinecraftServer.java:3915) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
>         at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
>         at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
>         at java.lang.Thread.run(Thread.java:833) [?:?] {}

The Java arguments used on the server are:

> java -Dlog4j2.formatMsgNoLookups=true -Xmx"$HEAPSIZE" -Xms"$HEAPSIZE" -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US @libraries/net/minecraftforge/forge/1.18.2-40.1.61/unix_args.txt nogui

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version : 0.0.3h

**Additional context**

**Comment by ioannisNoukakis** [comment]
I want to add some additional context here: 

- OS: Ubuntu 20.04.5 LTS x86_64
- 5.4.0-135-generic
- AMD Ryzen 5 3600 (12) @ 3.600GHz
- Memory: 64241MiB
- OpenJDK: 17.0.5 2022-10-18
- JVM args: `java -Dlog4j2.formatMsgNoLookups=true -Xmx"$HEAPSIZE" -Xms"$HEAPSIZE" -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US @libraries/net/minecraftforge/forge/1.18.2-40.1.61/unix_args.txt nogui`

To anybody stuck on this, (crashing loop when an entity is throwing exceptions each time the chuck is loaded): https://serverminer.com/article/how-to-fix-a-ticking-block-entity-on-a-forge-server/

**Comment by jmilthedude** [comment]
You need to update. This was fixed in a newer gersion than what you are running.

**Comment by ioannisNoukakis** [comment]
Cool thanks for the fast response!
