### ISSUE TITLE
little mobs for lvl 100 hard vault

### ISSUE THREAD

**Issue by toinedeman** [Iskallia/Vault-public#12]
hi. i have very little mobs spawning in the vault for an hard lvl 100 vault

**Comment by Nimothy** [comment]
Hi @toinedeman, if you are using commands to advance vault level and spawn in vaults there may well be bugs. 
The pack is designed to be played without cheating. 

If you wish to play this way, please wait until the mod is officially released on CursedForge to verify if these issues still exist.

**Comment by toinedeman** [comment]
i didnt use any commands to lvl up. yes i was in crea but otherwise i didnt use comands :)

**Comment by Enderized** [comment]
Indeed there seems to be an issue with Mob-Spawning in general (not just at level 100+ (which to my knowledge wouldn't even increase the spawnrate, but only strengh and type of mob- but i might be wrong there :D)

Overall there are no Mobs spawning for me in the Vault (unless from Mob Spawner spawned mobs...) up until the moment I kill a Vault Boss which then causes Mobs corresponding to my Vault Level to spawn.

The only Commands used by me at least were to get the Vault Altar, a Rock and the Items required to create a Vault Crystal. No Level related command or anything which might/should have caused issues regarding that as the Crystal was generated by the Mod itself

**Comment by scalda** [comment]
this is due to the timer not working in the pubic release so mobs don't spawn

**Comment by KaptainWutax** [comment]
Fixed in 1.0.1.
