### ISSUE TITLE
Transmog table destroys items if used incorrectly

### ISSUE THREAD

**Issue by SinnIos** [Iskallia/Vault-public#1200]
**Describe the bug**
While using a transmog table, if you close the interface before removing the item into your inventory, it disappears.

**To Reproduce**
1. Open transmog table
2. Place item and vault coins in
3. Accept transmog
4. Close interface with the item still in the slot where it ends up after getting transmogged
5. item is deleted

**Expected behavior**
When the table is closed, the item should either remain in the table or be placed into inventory like other crafting benches

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Server (Apex)
- The_Vault Version: v3

**Additional context**

**Comment by jmilthedude** [comment]
This is fixed in the next update.
