### ISSUE TITLE
Game Crash after couple seconds of loading into world (sometimes crash log shows texture errors)

### ISSUE THREAD

**Issue by Old-bimblor** [Iskallia/Vault-public#1205]
**Describe the bug**
When loading vault hunters on Curseforge I can load into server and single player but after a couple seconds game crashes before I get chance to move. The log files sometimes mentions missing textures but from multiple mods. have reinstalled the entirety of minecraft and curseforge as well as install multiple versions of java to get same issue.

**To Reproduce**
1.install mod pack (once or twice with Pam's harvestcraft added too but made no difference with or without the mod installed)
2. load vault hunters
3.click play on minecraft launcher
4.laucnh single player or load to server
5. wait spawn
6. wait 3 seconds
7. crash

**Expected behavior**

**Screenshots or Crash Report**

![Vault hunter crash code](https://user-images.githubusercontent.com/122935918/213013150-c1a36822-9667-4ab5-8d73-c615884c082e.PNG)

(current install)
[latest.log](https://github.com/Iskallia/Vault-public-S1/files/10439417/latest.log)

(previous Install)
[2023-01-16-2.log](https://github.com/Iskallia/Vault-public-S1/files/10439405/2023-01-16-2.log)

(original install)
[2023-01-16-1.log](https://github.com/Iskallia/Vault-public-S1/files/10439425/2023-01-16-1.log)

**Info (please complete the following information):**
- World Type: single player and Server
- The_Vault Version: 3rd edition update 5, 1.18.2 (forge 40.1.93)

**Additional context**

**Comment by Old-bimblor** [comment]
![resolved](https://user-images.githubusercontent.com/122935918/213015477-98cd69ba-955f-49d4-af1f-77ff7adf6144.PNG)

think i found my issue... 2 days of straight looking for this and it was a mekansim issue, hopefully this doesnt return! but didnt realise the craftweaked file was a potential crash log too...

**Comment by Old-bimblor** [comment]
on second thought this hasnt resolved my issue by deleting the .toml for mekansim

**Comment by Old-bimblor** [comment]
[hs_err_pid22988.log](https://github.com/Iskallia/Vault-public-S1/files/10449308/hs_err_pid22988.log)

First crash report, not once has it generated before now. upping my ram helped to get to this point

**Comment by KuLiPoi** [comment]
same issue. :<

**Comment by Old-bimblor** [comment]
i seem to be able to run version 4.1 fine. guessing something updates to 5 differently? not sure if it has smehting to do with an AMD graphics card?

**Comment by Old-bimblor** [comment]
https://www.reddit.com/r/VaultHuntersMinecraft/comments/1098jym/game_crashes_with_exit_code_1073740940/
