### ISSUE TITLE
Emu do not support producing eggs in an Animal Pen.

### ISSUE THREAD

**Issue by Renari** [Iskallia/Vault-public#1210]
**Describe the bug**
Emu when put in an Animal Pen do not produce Emu eggs like chickens do.

**To Reproduce**
1. Capture Emu in bottle
2. Place Emu in Animal Pen
3. Does not produce eggs like chicken does

**Expected behavior**
Emu to produce eggs like chickens

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version: 2.0.14.1415

**Comment by jmilthedude** [comment]
Quedtion: How do you have an Emu? They are disabled.

**Comment by Renari** [comment]
Apparently you can find their eggs in the traveling merchant saddlebags.

**Comment by jmilthedude** [comment]
I suppose we need to try to remove that from the trader. Anyway, they are meant to be disabled so there is no intention to support them.
