### ISSUE TITLE
Server View Distance

### ISSUE THREAD

**Issue by EJK3903** [Iskallia/Vault-public#1211]
**Describe the bug**
i cant change the view distance on my vault hunters server, whenever i do change it in properties and then start the world up it will just reset

**To Reproduce**
1.change view distance in server properties 
2.start server
3.check view distance and it is back to 6

**Expected behavior**
would launch with desired view distance

**Info (please complete the following information):**
- World Type: server
- The_Vault Version 7H

**Additional context**
server hosting is revivenode

**Comment by jmilthedude** [comment]
Check with your host. This is very unlikely to be anything we do. Reopen if you still believe this is our issue.

**Comment by EJK3903** [comment]
ive checked and they seem to believe it could be one of the mods or config files
