### ISSUE TITLE
Minimap Integration causes stuttering

### ISSUE THREAD

**Issue by Silly541** [Iskallia/Vault-public#1215]
**Describe the bug**
When Xaero's Minimap is installed, The Vault mod's minimap integration is put into use. The overworld portion of the integration that ensures the coordinate display reappears on leaving a vault runs on every client tick, causing stuttering. This likely also causes stuttering inside of a vault as well. The vault specific portion of the integration would be ran, causing the stuttering

**To Reproduce**
1. Install Xaero's Minimap and World Map
2. Occasionally, the game will stutter. This may be dependent on the user's processor

**Screenshots or Crash Report**
Here are two Spark profiles showing ticks that take over 150ms to tick. The [first one](https://spark.lucko.me/RgonokUhwt) was performed on a private server (with Journeymap installed only on the client) due to Xaero's Minimap/World Map adding potion effects to the registry. The [second one](https://spark.lucko.me/VOnsCKoV3F) was performed on the official Iskall Vault Hunters server. I have a [third one](https://spark.lucko.me/71tfeGWb6Z) from December 2022, likely taken in update 4. A [fourth one](https://spark.lucko.me/uuICfV0Wgs) also exists, and was likely taken in update 4 as well. Every profile except for the first one was taken on an official Iskall Vault Hunters server, with Xaero's Minimap and World Map installed

**Info (please complete the following information):**
- World Type: Server (although, this is a client side issue)
- The_Vault Version 2.0.14.1492 (pack version 7.7)

**Additional context**
This is likely also caused by my JVM arguments, but after the I performed the profile without Xaero's installed, I am less inclined to believe that it is my JVM arguments alone. I will test later with different JVM arguments and post the results here

**Comment by thelulzy** [comment]
I'm having the same issue, and so is Maz#0001 (is that you?) as described in [this post](https://discord.com/channels/889424759018901514/889845714207801344/1077124836108804107) on the discord.

[Here's my profiler run](https://spark.lucko.me/PHh4zwBypM) where I've isolated ticks taking over 200ms. These ticks can't typically take from 100ms to 1.2 SECONDS for me. 

I can say I've tried this with quite a few different JVM arguments and nothing has changed the behavior.

My SO has told me she does not experience this problem. I have yet to analyze her TPS, but if she's correct something is causing different behavior for those of us with the frame issues. I wonder if there's any commonalities in hardware between people experiencing this issue? I have fairly new & high end hardware, while my SO's is a bit older. An exhaustive list of my hardware is in [this HWiNFO report](https://webeddie.ch/mr/xrun.php?id=rig_usjbsncuzz_6214131398).

**Comment by jmilthedude** [comment]
I have added an additional check so that if the value is already set to the desired value, it will not set it again for no reason. 

The method for getting an option value is not doing anything weird and has low overhead. However, the method for setting an option value in Xaero's mod does not consider if anything changed or not, so the mod was writing to disk every single tick no matter if something changed or not. In order to circumvent this, the precondition is necessary. 

Thank you for presenting this to our attention.

**Comment by thelulzy** [comment]
For some reason I seem to be severely impacted by this issue, despite having a super fast PCIE 4 nvme SSD. Do I need to wait for the next update release, or is there some way I can apply a fix or work around in the meantime?
