### ISSUE TITLE
The command to "reset all" doesn't reset stats

### ISSUE THREAD

**Issue by jinkhya** [Iskallia/Vault-public#1218]
**Describe the bug**
When you do "/the_vault vault_level reset_all" it resets almost everything but the stats (like total vaults, survived etc) are still there. Unless there's another command to reset those, it'd be nice if the reset_all command included those.

**To Reproduce**
1. Run a vault to have some stats in the panel.
2. Run /the_vault vault_level reset_all
3. Check the stats again

**Expected behavior**
For the stats to be gone with the command (or another sub command)

**Info (please complete the following information):**
- World Type: SP or MP, it's the same
- The_Vault Version 8.0.3

**Comment by jmilthedude** [comment]
These commands are for dev purposes. Not meant for players or server admins. Accept and use them at your own risk as they are not documented nor is there any open source for you to see what effect they may have. Many of them do irreversible things.
