### ISSUE TITLE
Mod Crash with exit code -1

### ISSUE THREAD

**Issue by ThawingC** [Iskallia/Vault-public#1224]
**Describe the bug**
Minecraft crashes when mod is loaded
**To Reproduce**
1.Open Minecraft
2.Add the to mods folder
3.Run the game
4.Game chrashes 

**Expected behavior**
The Game to Run
**Screenshots or Crash Report**
[crash-2023-05-03_11.42.22-client.txt](https://github.com/Iskallia/Vault-public-S1/files/11379956/crash-2023-05-03_11.42.22-client.txt)

**Info (please complete the following information):**
- World Type: Single Player 1.18.2
- The_Vault Version: - the_vault-1.18.2-3.8.0.2166, the_vault-1.18.2-3.8.0.2176

**Additional context**

**Comment by BraveCaperCat2** [comment]
The mod is only designed for use with the vault hunters modpack and is OBVIOUSLY causing it to crash.

**Comment by jmilthedude** [comment]
The mod is not intended to be used by itself or with other packs. I’d recommend downloading the Vault Hunters modpack.
