### ISSUE TITLE
Game crashes for my friend when adding minetogether. (but not for me)

### ISSUE THREAD

**Issue by BraveCaperCat2** [Iskallia/Vault-public#1225]
**Describe the bug**

**To Reproduce**
1. Add minetogether to the modpack in the curseforge app
2. Launch the game
3. Game Crashes
4.

**Expected behavior**
Adding minetogether doesn't cause a crash.

**Screenshots or Crash Report**
[crash-2023-05-05_20.41.41-client.txt](https://github.com/Iskallia/Vault-public-S1/files/11409635/crash-2023-05-05_20.41.41-client.txt)

**Info (please complete the following information):**
- The Vault Hunters 3rd Edition Offical Modpack Version [Update 9.0.3]

**Additional context**
Minetogether is a dependency of me playing minecraft java (of any kind) with my friend.

**Comment by jmilthedude** [comment]
Sorry, but we don’t support adding or removing mods or customization of any kind to the pack or vault mod. This si something you would have to make compatible yourself, if possible.

**Comment by BraveCaperCat2** [comment]
Then how should i play with my friend if i can't use minetogether? (servers are not an option, only free methods work)

**Comment by jmilthedude** [comment]
Like I said, you would have to figure that out. I can tell you this.. Judging by the crash report you sent, the mod list does not show any of the mods in the pack. And there is no mention of the vault at all. So I'd recommend making sure your friend set it up properly in the first place. Beyond that, maybe you can find help in some modded minecraft discord or reddit. I'm not sure but we can only support what we release. I hope you understand that, at the level of customization modded minecraft has, we can't be expected to make every modification that every player who plays the game makes. We can only ensure the best experience possible in the version that we release.

**Comment by BraveCaperCat2** [comment]
> Like I said, you would have to figure that out. I can tell you this.. Judging by the crash report you sent, the mod list does not show any of the mods in the pack. And there is no mention of the vault at all. So I'd recommend making sure your friend set it up properly in the first place. Beyond that, maybe you can find help in some modded minecraft discord or reddit. I'm not sure but we can only support what we release. I hope you understand that, at the level of customization modded minecraft has, we can't be expected to make every modification that every player who plays the game makes. We can only ensure the best experience possible in the version that we release.

It's the VAULT HUNTERS 3RD EDITION OFFICAL MODPACK - I thought this is what this issue page was for, since the modpack itself doesn't have an issues link on the modpack's curseforge page, and it's made by the same developers.

The link to it is [Here](https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2) - But the link is down as of writing.

**Comment by jmilthedude** [comment]
Very simply, alter the modpack at your own risk. I gave you some tips based on the crash report but that’s as far as I’ll go. If you change the pack and it no longer runs, I’m sorry to say but that is not our obligation to resolve. Good luck and make sure your friend has the whole pack installed properly off of curseforge.

**Comment by BraveCaperCat2** [comment]
ok, but as far as i can say there is no free options for playing vault hunters modpack with my friend(s).

**Comment by jmilthedude** [comment]
Sorry for any ibconvenience, but this is not something we can do anything about.

**Comment by BraveCaperCat2** [comment]
what's "ibconvenience" (HaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHaHa)

**Comment by jmilthedude** [comment]
Thanks for confirming you're a child. Take care.
