### ISSUE TITLE
Jewel Quest

### ISSUE THREAD

**Issue by dcurtinmines** [Iskallia/Vault-public#1228]
**Describe the bug**
I got to the quest in the game that says to apply a jewel to a vault tool. However, when I put a jewel on a tool, it didn't complete the quest and now I am stuck and can't progress through the quest system. I did put a jewel on a tool before I reached the quest so that may have something to do with it. 

**To Reproduce**
1. After creating the tool station, craft a vault axe instead of a vault pickaxe
2. Put a jewel on the vault axe (I put picking on mine)
3. Create a vault pickaxe, completing the vault tools quest
4. Put a jewel on the vault pickaxe. This didn't complete the Jewels on Tools quest for me. 

**Expected behavior**
After I applied the jewel to the vault pickaxe, I assumed the quest would be complete, but it wasn't. I tried applying jewels to other tools but that didn't complete it either. 

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.
![2023-05-23_14 14 14](https://github.com/Iskallia/Vault-public-S1/assets/134435812/6d0e1400-2041-4e69-a414-afcc4fe83a6b)
![2023-05-23_14 14 21](https://github.com/Iskallia/Vault-public-S1/assets/134435812/8618214f-2068-4cea-aa2f-ecbd6f99b3a1)

**Info (please complete the following information):**
- World Type: Singleplayer
- The_Vault Version:    Update 9.0.3     It's also forge 40.2.1  ,   Minecraft version 1.18.2

**Additional context**

**Comment by jmilthedude** [comment]
The fix for this will be in the next update.
