### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Guercinator** [Iskallia/Vault-public#123]
**Describe the bug**
When i place in my SP world a "Tiny lilypad", my game crashes. I tried that 3 times and the same thing happened.

**Comment by iGoodie** [comment]
It seems like an issue from the mod that adds "Tiny Lilypad".
But could you please share the logs of that one session where your game crashed, so we can see if the Vault mod causes that.

I'm closing the issue till then, but once you share more information, I can reopen it :)
