### ISSUE TITLE
Unable to use wings from origins or any other wings that are not equipped

### ISSUE THREAD

**Issue by Icey-the-dragon** [Iskallia/Vault-public#1244]
**Describe the bug**
Some days ago i wanted to play cault hunters 3 with the origins for forge mod when one of my friends noticed that he was unable to fly with elytrian. In response i tried getting the source code and seeing what was wrong FIRST i disabled 2 mods. The vault && Vault_Integrations. when doind that everything was fixed but i tried then to edit the mod but i did not find anything. Editing with IntelliJ leads nowhere so pleas fix this ♥

**To Reproduce**
1. Download Origins | Forge / NeoForge | && Caelus API
2.Open the game & select Elytrian origin
3. Try to dly with elytra from the origin

**Expected behavior**
Beign able to fly correctly and using the animation

**Screenshots or Crash Report**
No crash happens & no image can describe the situation

**Info (please complete the following information):**
- World Type: both
- The_Vault Version [e.g. 1.0.1

**Additional context**
It starts the animation and tag of ISFALLFLYING for 1 moment but then the ISFALLFLYING tag gets removed

**Comment by jmilthedude** [comment]
We will not support the addition of any mods to the pack.
