### ISSUE TITLE
Loading into the game is brocken

### ISSUE THREAD

**Issue by NumericTuna89** [Iskallia/Vault-public#132]
**Describe the bug**

**To Reproduce**
1.launching the game in curse launcher as its going through the red loading screen it just crashes
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.
![Screenshot 2021-03-29 125021](https://user-images.githubusercontent.com/81584736/112879168-6f2e6780-908e-11eb-95a6-d18da01518ab.png)

**Info (please complete the following information):**
- World Type: single player

- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by ImreBoersma** [comment]
See #86.
It's because you bound a mousekey in your controls.

**Comment by NumericTuna89** [comment]
ah is it fixable or just bricked that file load
