### ISSUE TITLE
Rare Vault broken in Bartion server

### ISSUE THREAD

**Issue by sarasven585** [Iskallia/Vault-public#145]
> 

> **Describe the bug**

the straight path from vault portal was just the room infront of that portal room so please check it out as soon as possible

**To Reproduce**
1.
![B7E070F2-6E11-4258-9D29-85E8C3C8756E](https://user-images.githubusercontent.com/81620824/112970665-b8de8700-914e-11eb-8162-08d8ce613346.png)
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by sarasven585** [comment]
just ask if you want or need more information

**Comment by iGoodie** [comment]
Hey! Looks like this issue is missing details.
Could you please explain it more and try to provide more info? :)
I'll re-open the issue if necessary

**Comment by sarasven585** [comment]
sure i send more information tomorrow when i get on my pc

**Comment by sarasven585** [comment]
> Hey! Looks like this issue is missing details.
> Could you please explain it more and try to provide more info? :)
> I'll re-open the issue if necessary

send me your email and i will send you the video of my vault run to you so you can see the bug yourself
