### ISSUE TITLE
Putting down a gifter statue hard crashes my world

### ISSUE THREAD

**Issue by Millz108** [Iskallia/Vault-public#150]
**Describe the bug**

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by iGoodie** [comment]
Does it happen when you pick one from creative menu?
Does it happen in a Singleplayer world?
Please edit the description and fill it properly.

**Comment by iGoodie** [comment]
Closing the issue until more details are shared :)
