### ISSUE TITLE
treasure room glitch

### ISSUE THREAD

**Issue by CreativeDude1133** [Iskallia/Vault-public#154]
**Describe the bug**
Glitch Into treasure rooms

**To Reproduce**
1. get a elytra
2. use a pearl at the bottom of a treasure room door and just keep doing that until you in
3.do the same thing but out

**Expected behavior**
Glitch Though the door to get all the loot

i don't have any screenshots of doing this sorry

**Info (please complete the following information):**
- World Type: Server
- Version [e.g. 1.0.1]

**Comment by magicalex234** [comment]
This sound like just an issue with the vault room doors just being doors. Everything else is just mobility bugs in vanilla minecraft, meaning there's likely nothing they can do to fix this other than change the vault room doors to be solid blocks.

**Comment by jmilthedude** [comment]
Not really anything that can be done about this. Up to the player to play with honor :P
