### ISSUE TITLE
tiny lilypad client crash

### ISSUE THREAD

**Issue by Joshmja91** [Iskallia/Vault-public#155]
I've found an issue where if i place a tiny lily pad on a server it will crash my client.

1. place tiny lily pad on water

**Expected behavior**
the client will save the world and then crash.

**Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
World Type: Server
Vault hunter version 1.0.0
[crash-2021-03-28_12.38.14-client.txt](https://github.com/Iskallia/Vault-public/files/6233478/crash-2021-03-28_12.38.14-client.txt)

**Additional context**

**Comment by ImreBoersma** [comment]
Thus has already been fixed in the latest version.
#41

**Comment by iGoodie** [comment]
JML fixed it with e8cc193
Should be gone in the next build :)
