### ISSUE TITLE
Vault Timer 

### ISSUE THREAD

**Issue by DevCorp-beta** [Iskallia/Vault-public#160]
**Describe the bug**
THe vault timer cant go above 59 mins

**To Reproduce**
1.enter the vault
2.use a mystic pear
3.the timer increases
4.go above the vault timer

**Expected behavior**
i expected it to go for an hour

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/64924939/113129602-c44fb200-9223-11eb-8500-17c801e13998.png)

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version idk

**Comment by ImreBoersma** [comment]
This issue has already been reported here #17
