### ISSUE TITLE
Reaching the top of the vault generation

### ISSUE THREAD

**Issue by DevCorp-beta** [Iskallia/Vault-public#162]
**Describe the bug**
You can reach the top of the world
**To Reproduce**
1.go to a corner
2.place a ladder
3.then ender pearl
4.lookup and then continue for a while in time I'll reach there

**Expected behavior**
not to be able to go above the vault dimension

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/64924939/113132505-35449900-9227-11eb-9504-7336c27075ed.png)

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version [e.g. 1.0.1]

**Comment by ImreBoersma** [comment]
I guess it's a bug, but why would you want to do that?! You cannot re-enter a vault. You'll have to wait for the timer to pass or kys to get out of the vault..

**Comment by bmemike** [comment]
This feels like as much of a bug as doing this in the nether and not really related to the_vault.

Since the player has to specifically go out of their way to accomplish this and there is, in my opinion, literally no value in doing this (in fact, quite the opposite), this feels like a NOOP.

**Comment by iGoodie** [comment]
This is a bug, unfortunately, caused by the way ender pearls are implemented.
I don't think we'll fix that. But thanks for letting us know!
