### ISSUE TITLE
Treasure room with empty chests

### ISSUE THREAD

**Issue by elyriia** [Iskallia/Vault-public#166]
**Describe the bug**
I run 2 epic vaults where the chests inside the treasure rooms were empty. The only thing that was in one of them was the obelisk.
One of them i tried in normal and the other i tried in creative to see if was bad luck or not

https://user-images.githubusercontent.com/72629514/113202530-3be00a00-9241-11eb-9227-eda55dcc5066.mp4

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version 1.0.1

**Additional context**

**Comment by Euroam** [comment]
that is happening when config is not right i think ,as i saw someone have the same issue, so maybe reinstall the pack after backing up your world might help

**Comment by Euroam** [comment]
i think that is happening when config is not right i think ,as i saw someone have the same issue, so maybe reinstall the pack after backing up your world might help

**Comment by elyriia** [comment]
I don't think that's the problem. I didn't change the config before and I did what you said now but it still no loot

**Comment by Euroam** [comment]
Ok, anyway the modpack is released on curseforge, so just shift your world into the official release of curseforge and it should work, if it doesn’t there might be a problem with your world

**Comment by elyriia** [comment]
Ok the problem was that I didn't have all the mods installed. I didn't think it would be a problem but it was. 
Thank you for the help =D
