### ISSUE TITLE
Potion Recipes Incorrect (JEI)

### ISSUE THREAD

**Issue by shaquillerayau** [Iskallia/Vault-public#170]
**Describe the bug**
Potion recipes in JEI are incorrect or do not display correctly. For example Potion of Invisibility requires a Potion of Night Vision. Potion of Night Vision says it only requires a Golden carrot and water bottle. The potion of Invisibility requires a Potion of Night Vision and Fermented spider eye which isn't entirely correct.

**To Reproduce**
1. Search for a potion in JEI (i.e Potion of Invisibility) 
2. look at recipe 

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server] Server
- The_Vault Version [e.g. 1.0.1] 1.0.1 (Discord Release)

**Comment by iGoodie** [comment]
The Vault mod doesn't implement that feature. Unfortunately, that might be an issue you'd like to report under JEI's repository :P
