### ISSUE TITLE
Will there be a server version on CurseForge?

### ISSUE THREAD

**Issue by iGoodie** [Iskallia/Vault-public#174]
I see the [official modpack](https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack/files) on CurseForge but not the server files.  

I tried to run the only modpack zipfile on CurseForge but I get immediate errors when starting it.  Will there be a server version on CurseForge?

_Originally posted by @hannah98 in https://github.com/Iskallia/Vault-public/issues/71#issuecomment-811958144_

**Comment by MasterWright** [comment]
I was also looking for the server version release so I can set this up on an updating server. Currently I have to manually update the server everytime an update is pushed.

**Comment by scalda** [comment]
Server files have been released but please read the notes on there

**Comment by hannah98** [comment]
Thank you!
