### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Mysticalella** [Iskallia/Vault-public#176]
if i open te game and it starts minecraft than it  chrashes the minecraft

- [ ] 

1. #

what do i need to do

**Comment by iGoodie** [comment]
More detailed info is required in order for us to troubleshoot and fix the issue

**Comment by Mysticalella** [comment]
the crash file is not in the crash-report file where do i find it

**Comment by iGoodie** [comment]
Looks like the installation is corrupted. Try to reinstall the modpack

**Comment by Mysticalella** [comment]
i reinstalld the modpack and it chrashes anyway 
this is the game output 

15:19:50.478
mixin
main
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Monica/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
15:19:53.862
mixin
main
Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
15:19:53.864
mixin
main
Successfully loaded Mixin Connector [corgiaoc.byg.mixin.MixinConnector]
15:19:53.867
mixin
main
Successfully loaded Mixin Connector [eutros.framedcompactdrawers.MixinConnector]
15:19:53.869
mixin
main
Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
15:19:53.871
mixin
main
Successfully loaded Mixin Connector [shetiphian.core.mixins.MixinConnector]
15:19:53.946
mixin
main
Successfully loaded Mixin Connector [iskallia.vault.MixinConnector]
15:19:53.958
corgiaoc.byg.BYG
main
BYG: Mixin Connected!
15:19:53.961
mixin
main
Mixin config assets/patchouli/patchouli.mixins.json does not specify "minVersion" property
15:19:53.967
cpw.mods.modlauncher.LaunchServiceHandler
main
Launching target 'fmlclient' with arguments [--version, forge-34.1.42, --gameDir, C:\Users\Monica\curseforge\minecraft\Instances\Vault Hunters - Official Modpack, --assetsDir, C:\Users\Monica\curseforge\minecraft\Install\assets, --uuid, 1b31b77133334310aa93ad8210ce1566, --username, MysticalElla, --assetIndex, 1.16, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
15:19:54.100
mixin
main
Error loading class: net/minecraft/world/DimensionType (java.lang.ClassNotFoundException: null)
15:19:54.100
mixin
main
@Mixin target net.minecraft.world.DimensionType was not found appliedenergistics2.mixins.json:spatial.DimensionTypeMixin
15:19:54.105
mixin
main
Error loading class: net/minecraft/world/Dimension (java.lang.ClassNotFoundException: null)
15:19:54.106
mixin
main
@Mixin target net.minecraft.world.Dimension was not found appliedenergistics2.mixins.json:spatial.DimensionOptionMixin
15:19:54.252
net.minecraftforge.coremod.CoreMod.immersiveengineering
main
Inserted wire collision callback
15:19:54.332
mixin
main
Error loading class: net/minecraft/world/gen/settings/DimensionStructuresSettings (java.lang.ClassNotFoundException: null)
15:19:54.333
mixin
main
@Mixin target net.minecraft.world.gen.settings.DimensionStructuresSettings was not found appliedenergistics2.mixins.json:structure.DimensionStructuresSettingsMixin
15:19:54.341
mixin
main
Error loading class: net/minecraft/world/biome/BiomeGenerationSettings (java.lang.ClassNotFoundException: null)
15:19:54.341
mixin
main
@Mixin target net.minecraft.world.biome.BiomeGenerationSettings was not found appliedenergistics2.mixins.json:structure.GenerationSettingsAccessor
15:19:54.345
mixin
main
Error loading class: net/minecraft/world/biome/Biome (java.lang.ClassNotFoundException: null)
15:19:54.345
mixin
main
@Mixin target net.minecraft.world.biome.Biome was not found appliedenergistics2.mixins.json:structure.BiomeAccessor
15:19:54.708
net.minecraftforge.coremod.CoreMod.immersiveengineering
main
Inserted after-TER callback
15:19:54.879
net.minecraftforge.coremod.CoreMod.immersiveengineering
main
Inserted wire collision callback
15:19:54.955
mixin
main
Error loading class: net/minecraft/entity/passive/BeeEntity (java.lang.ClassNotFoundException: null)
15:19:54.955
mixin
main
@Mixin target net.minecraft.entity.passive.BeeEntity was not found spawnermod.mixins.json:BeeEntityMixin
15:19:54.958
mixin
main
Error loading class: net/minecraft/entity/passive/WolfEntity (java.lang.ClassNotFoundException: null)
15:19:54.958
mixin
main
@Mixin target net.minecraft.entity.passive.WolfEntity was not found spawnermod.mixins.json:WolfEntityMixin
15:19:54.960
mixin
main
Error loading class: net/minecraft/entity/monster/EndermanEntity (java.lang.ClassNotFoundException: null)
15:19:54.961
mixin
main
@Mixin target net.minecraft.entity.monster.EndermanEntity was not found spawnermod.mixins.json:EndermanEntityMixin
15:19:54.964
mixin
main
Error loading class: net/minecraft/entity/passive/IronGolemEntity (java.lang.ClassNotFoundException: null)
15:19:54.965
mixin
main
@Mixin target net.minecraft.entity.passive.IronGolemEntity was not found spawnermod.mixins.json:IronGolemEntityMixin
15:19:54.969
mixin
main
Error loading class: net/minecraft/entity/passive/PolarBearEntity (java.lang.ClassNotFoundException: null)
15:19:54.970
mixin
main
@Mixin target net.minecraft.entity.passive.PolarBearEntity was not found spawnermod.mixins.json:PolarBearEntityMixin
15:19:54.973
mixin
main
Error loading class: net/minecraft/entity/monster/ZombifiedPiglinEntity (java.lang.ClassNotFoundException: null)
15:19:54.973
mixin
main
@Mixin target net.minecraft.entity.monster.ZombifiedPiglinEntity was not found spawnermod.mixins.json:ZombiefiedPiglinEntityMixin
15:19:54.998
mixin
main
Error loading class: net/minecraft/block/AbstractFireBlock (java.lang.ClassNotFoundException: null)
15:19:54.998
mixin
main
@Mixin target net.minecraft.block.AbstractFireBlock was not found byg.mixins.json:common.block.MixinAbstractFireBlock
15:19:55.001
mixin
main
Error loading class: net/minecraft/entity/passive/AnimalEntity (java.lang.ClassNotFoundException: null)
15:19:55.001
mixin
main
@Mixin target net.minecraft.entity.passive.AnimalEntity was not found byg.mixins.json:common.entity.MixinAnimalEntity
15:19:55.004
mixin
main
Error loading class: net/minecraft/entity/monster/SlimeEntity (java.lang.ClassNotFoundException: null)
15:19:55.017
mixin
main
@Mixin target net.minecraft.entity.monster.SlimeEntity was not found byg.mixins.json:common.entity.MixinSlimeEntity
