### ISSUE TITLE
we can't heal even though we are not in a vault

### ISSUE THREAD

**Issue by dumpkinn** [Iskallia/Vault-public#177]
**Describe the bug**
I am playing on a server that I made, and a person entered a vault now no one can heal through eating food.
**To Reproduce**
1.person entered the vault
2.no one can heal

**Expected behavior**
I expected for us to not lose the ability to heal even though we

**Screenshots or Crash Report**
![unknown](https://user-images.githubusercontent.com/81766750/113322018-1835c600-930c-11eb-9bc2-ba5cc6444107.png)

**Info (please complete the following information):**
- World Type: [Server]
- The_Vault Version [1.2]

**Comment by Mikaaah** [comment]
Gamerule NaturalRegeneration gets set to false after vaults ^^
