### ISSUE TITLE
Rampage crashes game

### ISSUE THREAD

**Issue by Peskybirdofdoom** [Iskallia/Vault-public#18]
When rampage is activated it crashes the game. When I upgraded rampage to max and activated it and crashed the game. Opened the world again and activated it again, and crashed again. Log: https://pastebin.com/r8b65G5i

**Comment by Enderized** [comment]
WIth my glorious observation skills whilst testing that... it does seem to crash once the effect wears off rather than on activation.
Also the effect of maxed out Rampage itself does not work within its duration. (no extra damage is being dealt)

**Comment by Enderized** [comment]
fixed in v1.0.1

**Comment by KaptainWutax** [comment]
Indeed.
