### ISSUE TITLE
Trader Sells Overpriced vault Platinum

### ISSUE THREAD

**Issue by codynutbrain** [Iskallia/Vault-public#181]
I just got another trader to find that it was selling 1 vault platinum for 50 VAULT GOLD!
Considering you can craft 1 vault platinum for 9 vault gold this should not be a thing.

![2021-04-01_18 40 16](https://user-images.githubusercontent.com/81394603/113361660-75387880-931a-11eb-9805-5ec32df5ff52.png)

**Comment by Euroam** [comment]
Not sure, but I think this is a troll trader

**Comment by joshuaepstein** [comment]
Are you using the curseforge official pack, if not, then that will change it, that is an error in the config

**Comment by codynutbrain** [comment]
i am using the official curseforge release

**Comment by iGoodie** [comment]
It indeed is a troll trade :P
