### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Mysticalella** [Iskallia/Vault-public#183]
if i open the game it chrashes 
the crash file is not in the crash-report file 
this is the log file 
[2021-04-01-1.log](https://github.com/Iskallia/Vault-public/files/6248548/2021-04-01-1.log)
what do i need to do now ?

**Comment by joshuaepstein** [comment]
Are you using curseforge? and do have you have enough ram on your computer

**Comment by Mysticalella** [comment]
i am using curseforge and how mutch ram do you need to run vault hunters

**Comment by Mysticalella** [comment]
this is the game output 



14:10:03.438
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
14:10:03.439
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
14:10:03.439
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
14:10:03.439
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
14:10:03.439
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
14:10:03.440
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
14:10:03.440
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:10:03.440
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:10:03.441
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:10:03.441
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
14:10:03.441
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
14:10:03.441
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/79094208.call(Unknown Source)
14:10:03.442
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
14:10:03.442
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
14:10:03.442
STDERR
main
[java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/GameRules$IRuleEntryVisitor
14:10:03.442
STDERR
main
[java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(SourceFile:137)
14:10:03.442
STDERR
main
[java.lang.Throwable:printStackTrace:643]: 	... 11 more
14:10:03.442
STDERR
main
[java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.GameRules$IRuleEntryVisitor
14:10:03.443
STDERR
main
[java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
14:10:03.443
STDERR
main
[java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
14:10:03.443
STDERR
main
[java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
14:10:03.443
STDERR
main
[java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
14:10:03.443
STDERR
main
[java.lang.Throwable:printStackTrace:667]: 	... 12 more
14:10:03.443
STDERR
main
[java.lang.Throwable:printEnclosedStackTrace:709]: 	Suppressed: java.lang.ClassNotFoundException
14:10:03.443
STDERR
main
[java.lang.Throwable:printEnclosedStackTrace:709]: 		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282)
14:10:03.444
STDERR
main
[java.lang.Throwable:printEnclosedStackTrace:709]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
14:10:03.444
STDERR
main
[java.lang.Throwable:printEnclosedStackTrace:709]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
14:10:03.444
STDERR
main
[java.lang.Throwable:printEnclosedStackTrace:709]: 		... 13 more
14:10:03.918
launcher
main

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
14:10:03.918
monitor
Process Monitor
Process crashed with exit code 1

**Comment by iGoodie** [comment]
Looks like its an issue unrelated to the Vault mod.

I've seen those sorts of launching issues being solved by:
1. Trying to allocate more RAM
2. Reinstalling the pack
3. Reinstall CurseForge

**Comment by Mysticalella** [comment]
ok
