### ISSUE TITLE
Crashed and unable to relaunch

### ISSUE THREAD

**Issue by theodorbear42** [Iskallia/Vault-public#184]
**Describe the bug**
I was in a vault on the jmil server. My game froze and proceeded to close. Upon attempting to relaunch the game there was an error (attached) and I have yet to be able to launch

**To Reproduce**
[New Paste 1.txt](https://github.com/Iskallia/Vault-public/files/6248609/New.Paste.1.txt)

1.
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: JMIL server
- The_Vault Version 1.0.1
[New Paste 1.txt](https://github.com/Iskallia/Vault-public/files/6248622/New.Paste.1.txt)

**Additional context**

**Comment by joshuaepstein** [comment]
Try using curseforge, that should fix the issue: https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack

**Comment by theodorbear42** [comment]
Issue Resolved
