### ISSUE TITLE
[Concern] Vault Altar Recipes in 1.2

### ISSUE THREAD

**Issue by Enderized** [Iskallia/Vault-public#200]
With the update on 1.2 (Curse Forge Version) we got several new and/or changed Ingredients for our Vault Crystals to gather.
While I overall like the idea we will inevitably run into issues regarding some of the required ingredients:

- Gold Horse Armor
- Iron Horse Armor
- Diamond Horse Armor
- Dragon Head

Especially on the Iskallian Servers where we should not go beyond 15k blocks (World Border should start there) these resources are limited.
While Gold Horse Armor and Iron Horse Armor do have in theory recipes to be crafted (requiring either 2 Painite or Sparkletine Clusters)... Diamond Horse Armor and Dragon Heads don't have that privilege.

Eventually we will run out of these resources with no way to progress further in any kind, shape or form as we are neither guaranteed to get the required Gems for the Clusters nor that we might get a Trader offering us the Horse Armors/Dragon Head required.

**Comment by jmilthedude** [comment]
We won’t be making any config changes for the vault mod via issues or github for the public release. If there is an issue with something like this, I would recommend reaching out to an admin for the server you are playing on to make a change like that. That’s the whole point of configs. We may try to do our best but in all honesty those are very default configs without too much balancing.

**Comment by Enderized** [comment]
Allrighty, shall do! =)
