### ISSUE TITLE
Vein Miner no longer working

### ISSUE THREAD

**Issue by CaptAlex1092** [Iskallia/Vault-public#203]
**Describe the bug**
I have bought and used the Vein Miner for a while,but after some time it stopped working. The ability icon lights up when i press the ability cast button but I mine normally.
**To Reproduce**
1.
2.
3.
4.

**Expected behavior**
Vein Miner to work
**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]: LAN
- The_Vault Version [e.g. 1.0.1]:1.0.2

**Additional context**

**Comment by Enderized** [comment]
You have to hold the activation key to veinmine. (Default G)
So when pressing and holding G you veinmine =)

(Works fine for me; The_Vault Version 1.0.2; Pack Version 1.2)

**Comment by CaptAlex1092** [comment]
I was holding the activation key down.
The icon was lighted up the entire time.

**Comment by CaptAlex1092** [comment]
I reentered the world and it started working.
Thanks much.

**Comment by CaptAlex1092** [comment]
Nevermind it worked for a few minutes then it stopped working again.

**Comment by MasterWright** [comment]
This happens to us, but it is caused by holding an item in your off hand while vein mining. The item in the offhand will lose durability and when it gets to 0 and doesnt break the item, vein mine stops working. Just remove the item from your offhand and it should work again.

**Comment by Peskybirdofdoom** [comment]
Well I guess that explains why my shield was down to 1 durability even though i don't use it at all

**Comment by CaptAlex1092** [comment]
ohhh okay thanks.
