### ISSUE TITLE
Chest stacking bug

### ISSUE THREAD

**Issue by Peskybirdofdoom** [Iskallia/Vault-public#206]
**Describe the bug**
I was test running 1.2 vaults and came across two chests stacked upon each other

**To Reproduce**
Run vault hunters v.1.2 
Find the lava room with ghast spawner in it
Potentially have the bug happen

**Expected behavior**
I don't think chests are supposed to generate on each other

**Screenshots or Crash Report**
![Screenshot (232)](https://user-images.githubusercontent.com/81360100/113489913-28f36100-94f1-11eb-81a4-8115b372112f.png)

**Info (please complete the following information):**
- World Type: singleplayer
- The_Vault Version [e.g. 1.2]

**Additional context**
The chest generated next to the lava pillar in the room with the ghast spawner

**Comment by Ithkamakazi** [comment]
I don't think that's a bug just the rng attempting to place a double chest but due to terrain it did vertical instead of correct alignment or a minor alignment glitch with chest generation

**Comment by Peskybirdofdoom** [comment]
That could make sense, and it doesn't seem to happen too often so I guess its good
