### ISSUE TITLE
Vector Plate Recipes

### ISSUE THREAD

**Issue by Enderized** [Iskallia/Vault-public#209]
**Describe the bug**
Messed up recipe I assume for Vectorplate Upgrading. 6 Vector Plates + 1 Pog + 2 Beniotite Gem equals only 1 Fast Vector Plate?
Also: Extreme Vector Plate Recipe uses 5 Fast Vector Plates and 1 Normal one for also only 1 Extreme Vector Plate

**To Reproduce**
1. Open a Crafting Table and put stuff in

**Expected behavior**
At least 6 upgraded Vector Plates (which are way too pricy for just some Vector Plates tbh)

**Screenshots or Crash Report**
![UWMp3DY 1](https://user-images.githubusercontent.com/58046616/113496911-ad001580-94fe-11eb-98b8-75e81065f4d0.png)
![xsSik6z 1](https://user-images.githubusercontent.com/58046616/113496914-b5f0e700-94fe-11eb-9e68-8032c94f45ba.png)

**Info (please complete the following information):**
- World Type: SP/MP
- The_Vault Version 1.0.2 / Pack Version 1.2

**Additional context**
N/A

**Comment by bmemike** [comment]
Dupe of #119

**Comment by Enderized** [comment]
> Dupe 

Totally missed that one: my bad - shall close this to reduce open issues then =)
