### ISSUE TITLE
Biomes you'll go not working for end/nether on server

### ISSUE THREAD

**Issue by MasterWright** [Iskallia/Vault-public#217]
**Describe the bug**
When going into the end or nether, it is only vanilla biomes on a server, overworld is fine. Works as intended when making a single player world. We have upgraded the server to the server version and trimmed the nether, but it still loads vanilla only.

**To Reproduce**
1. Create a server
2. go to end/nether
3. You will only see vanilla biomes and cant even locate byg biomes via command

**Expected behavior**
The end and nether should have all the different non vanilla biomes on a server.

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.2 

**Additional context**
I also made sure the server settings for biome type were set to byg. Anyone know how we can fix this?

**Comment by superman12349** [comment]
Not on my server. Must have been a server generation problem on your side

**Comment by MasterWright** [comment]
We ended up finding a solution online after a couple days for searching. https://wiki.griefed.de/SCP/edit-world

The link walks you through the steps to get them to generate in BYG not vanilla.
