### ISSUE TITLE
Leveling Active's resets their Cooldown

### ISSUE THREAD

**Issue by Enderized** [Iskallia/Vault-public#23]
While I don't see any practical way to abuse this as it's uses are limited by the fact that each skill has a max level, one could still get an unintended advantage.

Example:
Summon Eternal
You go into a Vault and summon your Eternal. Then level-up "Summon Eternals" you can instantly summon your Eternal again.
I think it would make more sense if skills retain their cooldowns, even when leveling up.

**Comment by KaptainWutax** [comment]
That's totally fine. ^^
