### ISSUE TITLE
Cannot eat in vault

### ISSUE THREAD

**Issue by JaelMeri** [Iskallia/Vault-public#230]
**Describe the bug**
Hello, I just made it out of my first vault, common. I took 4 golden apples and 2 god apples in plus a whole stack of golden carrots. I could not eat my golden carrots no matter how far down my hearts were. An example is that I was down to 3 hearts and tried to eat golden carrots and it was just like when I have full hearts. You know when the hunger bar goes down then you can eat? Well, my hunger bar never went down even when my hearts did. I ended using all of my apples just to explore a little bit. It was really a disappointment. Also, upon leaving the vault I have only 6 golden carrots. It's like all of the ones I tried to use while I was in the vault were removed from my inventory when I left the vault

**To Reproduce**
1. I don't know if it can be reproduced.

**Expected behavior**
When I lose hearts I should be able to eat to refill hearts. Normal Minecraft behavior.

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Iskallia Muki Server
- The_Vault Version [e.g. 1.0.1]

Minecraft ID -  J_o_L_y_n

**Comment by Capser1234** [comment]
Health regeneration by food is turned off in the vaults. Your hunger bar was probably still full and so you couldn't eat. The only way to regen is by having regeneration of some sort (apples, enchantments such as radiance) or by having a life leech ability. I cant think of a reason why your carrots disappeared.

**Comment by JaelMeri** [comment]
In checking my inventory after the vault I found my stack of carrots in the top-right slot of my inventory. And six additional carrots where I usually keep the stack. So, that part is okay Thanks for explaining this to me. I hadn't read it anywhere.

**Comment by Enderized** [comment]
(feel free to close this issue then when it got resolved) =)
