### ISSUE TITLE
Empty Pandora Box

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#231]
**Describe the bug**
Today I opened my pandora box, and it did not drop anything. 

**To Reproduce**
1. Open pandora box
2. Get lucky

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.0.2

**Additional context**
I think this empty pandora box was containing a donkey head. As `justanotherheadmod:donkey_head` is still in the loot table, but mod itself is removed, I just was very lucky with a drop.

**Comment by iskall85** [comment]
Hi!
I can confirm this, it's because of the Donkey roll, where we had to take that mod out. I left it as an empty slot to simulate the "same bad luck" as a donkey head. So this is working as intended.
