### ISSUE TITLE
Unbreakable Wither Skulls

### ISSUE THREAD

**Issue by shaquillerayau** [Iskallia/Vault-public#247]
**Describe the bug**
Wither Skulls located in the desert town room "cave" located on black blocks next too cannons out of iron blocks are not breakable

**To Reproduce**
1.Go into a vault
2. find or get a desert town room
3. go into the cave underneath the gates usually on the south side
4. try to break wither skulls on black blocks.

**Expected behavior**
Wither skulls should break and drop

**Screenshots or Crash Report**
Screenshot : [https://imgur.com/a/6r765K8](https://imgur.com/a/6r765K8)

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version: 1.2 (Curse)

**Additional context**
N/A

**Comment by Peskybirdofdoom** [comment]
I am pretty sure this is intended, and that you are only supposed to get the one skull on the Iron cannon. The other 2 are unbreakable and only there for decoration
