### ISSUE TITLE
Right clicking on Vending Machine places block

### ISSUE THREAD

**Issue by tibetiroka** [Iskallia/Vault-public#25]
If you right-click on a vending machine when you have an item in your hand, the GUI opens AND the block is placed. I'm not sure which one of these is intended, but I'm pretty sure its not both of them.
 
 How to replicate: Hold any block item in your hand (e.g. glass), and right-click on a vending machine. 
 
This bug happens with Vending Machines and Advanced Vending Machines, regardless of where I click and whether they have any traders inside. Cannot reproduce with the Global Trader.

**Comment by iskall85** [comment]
Hallo, we are aware of this issue but due to time restraints this is not a priority to patch or fix. Thank you for your submission
