### ISSUE TITLE
Question: Knowledge points versus Skill points.

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#251]
## Description

I have a question about pack balance between knowledge and skill points. While playing on AntonioAsh server, I notice, that I got more skill orbs and skill frames than knowledge stars. 

I am reached level 11, and managed to get 5 knowledge stars. I crafted all of them. Star cores I got

- 2 from treasure rooms
- 1 crafter from diamond block
- 2 from traders.

However, I got over 20 skill points, where several was a full skill orb and others were crafted by skill frames, and that is beside 11 that I got from leveling up. 

And have run one Omega Vault and 2 Epic vaults by opening treasure rooms (over 20), and it does not look like star cores are very frequent in loot tables.

By looking at loot tables, I notice, that it is set that ORB_FRAME will be ~3-4 times more frequent than KNOWLEDGE_CORE, but from level 0-11, I do not lack the skill orbs. The biggest drawback is the knowledge, that prevents from setting up more advanced sorting systems and better resource gatherers. 

I understand that Vault Hunters mod pack is about the Vault Running, but at which point we should be able to unlock mods?

As by the current rate, it looks like I will reach level 20 till unlock AE2 or RS, and Botania or mechanism on level 60. It somehow does not fill balanced between skill orbs and knowledge stars.

The main question I wanted to get the answer to: At which point it is expected to start unlock mods?
(botatnia or mechanism, RS or AE2, TE and others)

**Comment by Enderized** [comment]
Personally I feel like most mods are not even worth considering taking- especially not for their Knowledge Cost + even after the Knowledge Requirements... the "good stuff" is still behind unnecessarily overpriced recipes :D 

I'll be completely honest with you- to play and beat VH you only need 2 (technically 1) mod:
Create.
For only 2 Knowledge this mod can almost create anything you need.
The second "mod" to help out Create is simply: Mobspawner (to increase mob spawns with the enhanced spawners... but works fine w/o) and some very basic-vanilla farms.

<details>
  <summary>
The only things you can generate with Create + Spawner + Cobble Gen and basic Vanilla farms would be:</summary>

Bucket of Pufferfish
Diamond
Diamond Horse Armor
Dirt
Dragon Head
Elytra
Gold Horse Armor 
Iron Horse Armor
Lapis Lazuli
Netherite Ingot
Netherrack
Overgrowth Seed
Snowball

(maybe Snowball/Pufferfish could actually be possible... that i dunno tho)
</details>

The time at which you would be finally be able to unlock mods... you basically don't need them anymore.

**Comment by magicalex234** [comment]
did you know that you can craft a star core using 4 beniotite and a vault diamond block?
It's a plus shape with the vault diamond block being in the center. That should help a little bit with the lack of knowledge cores early game, and even late game

**Comment by BONNe** [comment]
Yes, i know, and I wrote that 1 i crafted with diamond. However, the issue is that vault diamonds also is rare loot in treasure rooms/boss create.

**Comment by Enderized** [comment]
> did you know that you can craft a star core using 4 beniotite and a vault diamond block?
> It's a plus shape with the vault diamond block being in the center. That should help a little bit with the lack of knowledge cores early game, and even late game

Wasnt it Larimar?
It took me 20+ Vaults to ever get my first Larimar Vault ^^
So thats not necessarily a good income of knowledge either.
Beside the Vault Diamonds

**Comment by magicalex234** [comment]
@Enderized yes, it is larimar. Had a little brain fart and will go fix my first comment.
Thanks for correcting me :)

**Comment by BONNe** [comment]
Season 2 has reworked everything. 
This is not an issue.
