### ISSUE TITLE
Redstoner

### ISSUE THREAD

**Issue by sarasven585** [Iskallia/Vault-public#252]
**Describe the bug**

**To Reproduce**
1. RFToolsBase Machine Base is underneath World Developer i say it should be underneath Redstoner because it’s used in wireless redstone
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by Enderized** [comment]
duplicate of #226
