### ISSUE TITLE
Bug: Modify The Vault Altar Recipes

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#256]
**Describe the bug**
I get a bit bored with collecting the same items all the time and wanted to play with altar recipes by adding more items and changing the chance of getting some items. However, I notice that there is no option to do it at all. The vault_altar.json file content is completely ignored and everything is taken from altar.json, which is stored in a jar file.

**To Reproduce**
1. Change all recipes in vault_altar.json to something ridiculous, f.e. set everything to require 100000 times more.
2. Start a game or reload a config.
3. Put a new rock on the altar.

**Expected behavior**
The recipes should be taken from vault_altar.json and be with the ridiculous amounts that were set.

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version: 1.0.2

**Additional context**
If that is not a way how to change altar recipes, I would like to know how we could do it.

**Comment by soepie7** [comment]
We managed to change it with a datapack that edits data/the_vault/loot_tables/chest/altar.json, but it may not take effect at once for *some* reason.

**Comment by magicalex234** [comment]
for some reason, the .json file is incomplete and doesn't work. You need to find the altar.json file that's in the code itself. I know you can do this by editing the jar file, though don't do that unless you know how (and even then, make sure to copy the file and work on a copy so that you don't end up breaking the whole pack by making a mistake)

**Comment by khamseen** [comment]
I think for the public release this really needs to be moved back to the standalone config file. The costs of these things are absolutely insane for those of us who don't have arena crates, statues, gift packs etc like the Twitch streamers have.

**Comment by BONNe** [comment]
> We managed to change it with a datapack that edits data/the_vault/loot_tables/chest/altar.json, but it may not take effect at once for _some_ reason.

This is a way how to change the resources required for the vault altar. 

I will close this bug report, as altar recipes are changeable via datapack, but the config file is just for debugging reasons. It is not meant to be used in producion.

**Comment by QuackenAudio** [comment]
> We managed to change it with a datapack that edits data/the_vault/loot_tables/chest/altar.json, but it may not take effect at once for _some_ reason.

can you give a very brief explanation of what to do and how to use a data pack...
most of us are not developers and we just want a simple way to change recipe's

**Comment by BONNe** [comment]
[more_altar_recipes.zip](https://github.com/Iskallia/Vault-public/files/6549705/more_altar_recipes.zip)

These are my modifications that add more items into Vault Altar recipes.

It must be placed in `{server}/world/datapacks/` folder. You can either keep it as a zip file or unzip it into the `more_altar_recipes` folder.

If you want to add it into single player then it is the same procedure, just location is:
`{Instance}/saves/[your-world-name]/datapacks/`

If you want to modify it, just unzip it into the mentioned folder, and navigate to the `/more_altar_recipes/data/the_vault/loot_tables/chest/altar.json`. Open with any text editor and modify amounts or items as you pleased.

**Comment by QuackenAudio** [comment]
> [more_altar_recipes.zip](https://github.com/Iskallia/Vault-public/files/6549705/more_altar_recipes.zip)
> 
> These are my modifications that add more items into Vault Altar recipes.
> 
> It must be placed in `{server}/world/datapacks/` folder. You can either keep it as a zip file or unzip it into the `more_altar_recipes` folder.
> 
> If you want to add it into single player then it is the same procedure, just location is:
> `{Instance}/saves/[your-world-name]/datapacks/`
> 
> If you want to modify it, just unzip it into the mentioned folder, and navigate to the `/more_altar_recipes/data/the_vault/loot_tables/chest/altar.json`. Open with any text editor and modify amounts or items as you pleased.

Thank you so Much...
this makes it so much more realistic to be able to knock some of those items down to realistic numbers for the average player
