### ISSUE TITLE
Raffle trader game crash

### ISSUE THREAD

**Issue by tibetiroka** [Iskallia/Vault-public#26]
How to reproduce:
Take a Raffle Trader Core (from creative inventory) and put it in an empty Advanced Vending Machine (haven't tested with non-empty machines yet). Then, right click on the vending machine. The game will crash.

Doesn't happen in regular Vending Machines, only in advanced ones.

**Comment by Nimothy** [comment]
Hi @tibetiroka, this is not an issue please see #10

**Comment by tibetiroka** [comment]
I find it strange that it only crashes in Advanced machines, but let it be.
