### ISSUE TITLE
Feature request: Allow to define Vault Fighters

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#268]
#### Is your feature request related to a problem?

While playing VaultHunters it is funny to fight and kill yourself after reaching level 30. However, after some time it becomes sad and I would like to be able to change who I am killing in the Vault. Especially on online servers, were beside me, are other players who I would like to see and kill in the vault.

#### Describe the solution you'd like us to implement.

I would like to get an option to set different Vault Fighter names. It could be a single file where we could specify names or a random player from online members on servers.

If there is a file for defining names then it would allow to change them for single-player mode.
While choosing random players from all online players would allow enhancing multi-player mode.

I would be happy for any of them.

**Comment by Ithkamakazi** [comment]
Yes please, this would be a great QOL improvement for vault runs

**Comment by BONNe** [comment]
Implemented in season 2.

Custom skins can be added via `usernamecache.json`.
