### ISSUE TITLE
Cannot open vending machine

### ISSUE THREAD

**Issue by URAMAN45** [Iskallia/Vault-public#269]
My game crashed giving the exit code 1 when using a trader core (from the creative menu) in an advanced vending machine (I believe it would work for any type of vending machine).

**Comment by BONNe** [comment]
https://github.com/Iskallia/Vault-public/issues/10#issuecomment-806537650

**Comment by URAMAN45** [comment]
I just realized I did not roll the trader circuit so it had now trades and that is why my game crashed.
