### ISSUE TITLE
Armor duplication

### ISSUE THREAD

**Issue by bacchusnow** [Iskallia/Vault-public#27]
After crafting armor and you equip while still in crafting menu by right clicking it will duplicate armor.

**Comment by HoogaSwe** [comment]
It happen to me to and its any gear as long we are in an inventory you can right klikc to dupe.

**Comment by iskall85** [comment]
Is this VAULT GEAR or any armour?
If any armour this is unrelated to The_Vault mod and I believe it is because of inventory tweaks or CPW Mods.

**Comment by HoogaSwe** [comment]
Any armor

**Comment by bacchusnow** [comment]
Yeah any armor. Haven’t gotten far enough for vault armor yet.

**Comment by mefallit** [comment]
I've duped twice iron chestplate and leggings (goodie server) last night. It thought that it might related with lag
