### ISSUE TITLE
Upside down boos room generation

### ISSUE THREAD

**Issue by Capser1234** [Iskallia/Vault-public#280]
**Describe the bug**
I was running a vault and  the boss room I entered was upside down

**To Reproduce**
1. Enter a vault
2. Find a boss room

**Expected behavior**
No upside down room should generate.

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.
![2021-04-25_16 51 59](https://user-images.githubusercontent.com/81431065/115998511-dd137380-a5e7-11eb-8888-825f7e518cab.png)
![2021-04-25_16 52 11](https://user-images.githubusercontent.com/81431065/115998516-e4d31800-a5e7-11eb-85a2-091d22bfb5c6.png)
![2021-04-25_16 52 41](https://user-images.githubusercontent.com/81431065/115998523-ed2b5300-a5e7-11eb-9d08-eaf670de0c84.png)
![2021-04-25_16 52 55](https://user-images.githubusercontent.com/81431065/115998532-f61c2480-a5e7-11eb-876c-cc54cbd51060.png)

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version: Newest curseforge version: 1.2

**Additional context**
At first i thought it might have been a intentional room but the connectors were at the top of the room. In addition  some chest had spawned on a bedrock floor below the room (picture 3), while there were no chest inside the room itself. It could be intentional but I have never seen this boss room upside down before. I have seen the room in the normal state.

**Comment by BONNe** [comment]
No, that is intentional vault boss room. Not a bug. (chests spawning at the bottom of room I would consider as a bug)
