### ISSUE TITLE
Having only 2 Actives unlocked makes it unable to access the Wheel to select them.

### ISSUE THREAD

**Issue by Enderized** [Iskallia/Vault-public#29]
And therefore you cannot swap e.g. Ghostwalk for Megajump if you only have these two.
https://youtu.be/_FZE_Hm8nHU
(am pressing Left Alt repeatedly before leveling into mega jump)

After learning a 3rd ability it works just fine

**Comment by BONNe** [comment]
I run into the same issue. It looks like it just does not open or switches abilities if you have any 2 unlocked.

This happens still in 1.0.1 version.

**Comment by iskall85** [comment]
This is working as intended. The ability wheel will only activate after 3 or more abilities. WAI closing the report

**Comment by BONNe** [comment]
Iskall, I have a question, how to change abilities?
