### ISSUE TITLE
game crashes randomly

### ISSUE THREAD

**Issue by daniember2** [Iskallia/Vault-public#308]
**Describe the bug**
the game crashes randomly. I played on 1.2 in singleplayer and the game crashes randomly. I played for a bit, then it crashed while I was just mining. I restarted the modpack, played again normaly for a bit and it crashed again while I was just walking.

**To Reproduce**
1. I dont realy know how to reproduce this
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by BONNe** [comment]
Hmm, I am guessing but may be not enough memory assigned to the game? How much did you assigned?

**Comment by daniember2** [comment]
i dont know. how can I see that?

**Comment by BONNe** [comment]
![ram](https://user-images.githubusercontent.com/1344358/117414806-3c468180-af20-11eb-9ed0-c4ee2d24dfe7.png)

I suggest to use 6000 - 8000 (6 to 8 gb)

**Comment by daniember2** [comment]
oh i dont have enough then
