### ISSUE TITLE
3 mods require Forge 34.1.42

### ISSUE THREAD

**Issue by Giorgio243** [Iskallia/Vault-public#309]
When I tried to open the modpack for the first time, it said that 3 mods require Forge 34.1.42. However, the latest version of Forge available for Minecraft 1.16.3 is 34.1.41. What can I do to solve this problem?

**Comment by BONNe** [comment]
Hmm ... do not know what you talk about...
![hmm](https://user-images.githubusercontent.com/1344358/117312975-28523f80-ae8e-11eb-857c-b4dcb4d19cec.png)

**Comment by Giorgio243** [comment]
I have no idea what's wrong here...
![2021-05-07](https://user-images.githubusercontent.com/83756586/117427399-ad406600-af2d-11eb-86f2-95189117c41b.png)

**Comment by BONNe** [comment]
Did you install modpack via CurseForge launcher or you set it manually?

**Comment by Giorgio243** [comment]
I installed it via CurseForge, but I'm using TLauncher so I had to copy the files into another folder in order to make it work

**Comment by BONNe** [comment]
Maybe you could try to run it via CurseForge launcher?
Check if it works...

**Comment by Giorgio243** [comment]
Launching the modpack via CurseForge redirects to the official Minecraft launcher and I don't have an official Minecraft account

**Comment by BONNe** [comment]
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.3.html
The latest version is 34.1.42

Install forge manually.

**Comment by Giorgio243** [comment]
After messing with it to a point where I thought I'd definitely break it, I finally made it work! Thank you SO much for your help!
