### ISSUE TITLE
Inability to switch abilities if only 2 are unlocked.

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#31]
#### Describe the bug

I unlocked 2 abilities however, there is no way how to switch them. 

#### Steps to reproduce the behavior

Unlock only 2 abilities and press a key that should open the ability wheel.
Nothing happens.

#### Expected behavior

Either it should open the ability wheel or switch ability instantly.

### Additional context (Optional)

 Tested with `1.0.1-Public` version.
 
 As soon as I unlock the third ability, I can switch them. This bug appears only with 2 abilities.

**Comment by Nimothy** [comment]
Hi @BONNe, this seems to be a duplicate of #29. Maybe cancel this, and comment there 😄

**Comment by BONNe** [comment]
Duplicate #29
