### ISSUE TITLE
NO VAULTS!!!

### ISSUE THREAD

**Issue by monsterT2008** [Iskallia/Vault-public#312]
**Describe the bug**
you cant open a vault without extreme non ending lag and the game saying "minecraft 1.16.3 - not responding" also the vault robot is the only boss spawnable

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: single player
- The_Vault Version: 1.0.2

**Additional context**

**Comment by BONNe** [comment]
It is likely that your game does not have enough RAM memory. 
CurseForge version by default has 4GB assigned, but it is not enough for running this modpack (do now know the reason behind 4gb).

I suggest changing it to 6-8 GB. 
(blue circle shows which value to change)

![ram](https://user-images.githubusercontent.com/1344358/117586960-138ed980-b124-11eb-9508-de8c18bf936c.png)

**Comment by bmemike** [comment]
The robot is the only boss for a long time (I believe until you’re vault level 30, but might be mistaken on the actual level).

This part is not a bug.

**Comment by monsterT2008** [comment]
Ok thank you so much!!!

**Comment by theobuisson2008** [comment]
i have checked it and it is now fixed :D
