### ISSUE TITLE
vault boss not spawning

### ISSUE THREAD

**Issue by navheziv** [Iskallia/Vault-public#320]
when i go into a vault and put 4 inscriptions into the obelisk, the boss doesn't spawn.

1.get into a vault
2.put inscriptions into obelisk
3.
4.

i expected the boss to spawn.

![Minecraft_ 1 16 3 - Singleplayer 12_05_2021 17_38_42](https://user-images.githubusercontent.com/84090591/118006265-c98c3a80-b353-11eb-8678-0ad86cdbf52b.png)

single player, 1.0.2

i imagine it's a problem with my setup of the mod instead of an actual bug since it's game breaking and the mod's been out for a while.
it happens whether i'm in creative or survival, the obelisk is naturally generated or not, the vault is from commands or regular, and all difficulties.

**Comment by bmemike** [comment]
How did you install vault hunters? 

Are you running just the mod or the full modpack?

**Comment by navheziv** [comment]
the full modpack.
as i said, it could be a problem with my setup, since i downloaded the pack on curseforge and moved the mods to a different folder so i can play on a different launcher.

**Comment by navheziv** [comment]
Update: after u/damnsecci on reddit told me to look at the config, i found that there were two files for most of the entries, one mostly empty for customization and one with the actual configs. thing is, since the both had the same name, the right configs got the (2) treatment from the computer and the mod didn't go for them but for the blank ones.
thank you very much. the mod works perfectly now.

**Comment by navheziv** [comment]
...that was a long time ago and is no kinda awkward.

Did you manage to do it?

בתאריך יום ה׳, 13 במאי 2021, 06:01, מאת bmemike ***@***.***>:
