### ISSUE TITLE
Potentially self updating to 1.16.5 but need help

### ISSUE THREAD

**Issue by JoeFoxe** [Iskallia/Vault-public#321]
Hey so ive been doing my own version of vault hunters and I have been adding mods here and there and changing configs to fit better etc, I was also wondering if I can force update it to version 1.16.5 as that will open many many many more mod opportunities as many of them are newly added in 1.16.5 and many of the big updates/fixes as well. I think the bountiful mod would be a perfect fit for this having you do side quests at the start to build up vault xp and vault goodies before entering the vaults but in a much slower fashion. Thank you in advance

**Comment by bmemike** [comment]
This is a bug tracker for the official release, not a general modding support board. 

I would suggest you reach out for assistance through other channels (try reddit) or simply experiment and test the results first hand.

**Comment by JoeFoxe** [comment]
ah well shucks, as I was directed here from iskalls reddit. I feel like ive just been tossed around a lot. I have just been trying to get in contact with one of the devs which I have been pointed here so.

**Comment by bmemike** [comment]
The devs are extremely busy actively working on the new version.

While I can’t speak directly to any of their specific schedules, they probably don’t have much free time to assist with people’s side projects.

The main reason 1.16.3 was chosen was because many mods that were targeted didn’t have 1.16.5 versions out. It should be easy for you to test 1.16.5 and updated mod versions directly.

**Comment by JoeFoxe** [comment]
Yes when you say it should be easy for me to do that, can you tall me how I do this? because all in all this is all I am looking for. If it is easy you should be able to tell me how to do so yes? or do I need to look elsewhere. also I do appreciate the time they put into these projects. I was really just trying to put out a better version for the public to use as the current vault hunters version is very buggy and pretty unbalanced. with the slight configs I have changed it has drastically increased the enjoyability of the game. as well as adding multiple more mods and adding research configs to them and recipes etc. I do not ask for much time at all just a single message really of the direction/steps I would have to take to update the vault mod to 1.16.5. This is also the first modpack I have been working on. It has been a very very rough few years and finding this and trying to make a better and enjoyable version for the public to play and its finally given me some sort of purpose to life really (as I also have made a datapack that many of the community is already using in their worlds to help balancing). I am just reaching out for help and I feel like im just gettin shot down everywhere I go. Feels bad no one really cares about the little man anymore

**Comment by JoeFoxe** [comment]
as you know I also dont have money to donate to streamers to ask questions or get attention. so I just ask for help and hope someone nice enough is out there. I just wanted to make something for people to enjoy from something that has so much potential.

**Comment by bmemike** [comment]
You’ll need to update the Minecraft version to 1.16.5 and make sure each mod has a compatible version (or update the versions where you would like).

That’s trivial to do manually.

If you’re asking how to actually create a modpack, that’s not as easy to type up and I would encourage you to find one of the many resources online through some basic google searches. 

There are many videos and articles written on the topic.

**Comment by JoeFoxe** [comment]
Okay thanks man, I really do appreciate it. I guess I was just over thinking it too much and didnt get the right questions to ask
