### ISSUE TITLE
Game crashes when adding vaultrock to vaultaltar, exitcode 0

### ISSUE THREAD

**Issue by cocolosious** [Iskallia/Vault-public#329]
I played the full vanilla timeline, everything ran smoothly. But when I yesterday made the vaultaltar and tried to add the vaultrock to it, the game crashed. I've tried multiple times, and it crashes every time, I never even see the recepie. 
The game closes, and sends me back to the gamelauncher. It says exit code 0. Im playing on curseforge, and installed java recently. 

**Expected behavior**
To get a recepie for my vaultcrystal

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version: 1.0.2

This is the crashreport I found, but I dont know how to understand it. 

[crash-2021-05-18_10.19.00-server.txt](https://github.com/Iskallia/Vault-public/files/6499678/crash-2021-05-18_10.19.00-server.txt)

**Comment by BONNe** [comment]
One of the issues could be that you run the mod on 1.16.5 version.
It was made for 1.16.3, so there is a chance that some parts of the code may not work properly on 1.16.5.

As well as, the mod by itself is not playable. It is meant to be played with all mods from the pack. As Vaults inside requires blocks and loot from the other mods.

**Comment by cocolosious** [comment]
Thanks for an answer! What do I do then? I thought when I downloaded the Vaulthunters modpack, all I needed to play it would be included. Do I need to change to 1.16.3, and download some other stuff?

**Comment by BONNe** [comment]
From Crash Report it looks like you downloaded Official Mod, not a Mod Pack.

Here is a link to the ModPack: https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack
