### ISSUE TITLE
vault_mobs.json ignored?

### ISSUE THREAD

**Issue by khamseen** [Iskallia/Vault-public#333]
**Describe the bug**
I'm doing level 0 and now level 1 vaults and in all vaults so far I've had zombies, skeletons, wraiths, wither skeletons, spiders, cave spiders, pillagers, creepers, and blazes spawn. Yet according to the vault_mobs.json up until level 5 only zombies should be spawning. 

**To Reproduce**
1. Run a vault below level 5
2. See that more than what the vault_mobs.json says should spawn is spawning

**Expected behavior**
The vault spawns should respect the config file

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- Server
- The_Vault Version 1.0.2-public

**Additional context**
It may be that, like the altar recipes, this config has been moved somewhere else but I can't find anything in the jar unless it's now hardcoded and can't be altered.

**Comment by bmemike** [comment]
Many of the mobs you're referring to are spawned in due to spawners placed within vault rooms (oftentimes hidden within walls or behind other blocks). 

Those mobs won't change regardless of level because they are created by the spawners themselves.

**Comment by khamseen** [comment]
Yeah I was about to close this after asking about it on Reddit and someone said what you did. I hadn't really paid attention to the rooms I was seeing them spawn in but after it was explained it made sense. My memories of early VH season 1 streams is vague at this point haha. Thank you for the response though.
