### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by Tommmmy02** [Iskallia/Vault-public#337]
Hello, my Server is not starting and G-Portal cannot help me.

Which files do you need to look into it ?

The server is starting but after 2 minutes it shuts down. 
In this time you are not able to join the server.

**Comment by waidesoper** [comment]
do you have a console log from the server?

**Comment by Tommmmy02** [comment]
> do you have a console log from the server?

Sure :) 

[latest.log](https://github.com/Iskallia/Vault-public/files/6593581/latest.log)

**Comment by waidesoper** [comment]
The log seems a bit short. There's only 30 seconds of activity, I can't see any glaring errors.

**Comment by joshuaepstein** [comment]
Are you using the server pack?

**Comment by joshuaepstein** [comment]
If not it can be found here: https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack/files/3257498 - There is not a server pack for version 1.3 yet though

**Comment by Tommmmy02** [comment]
> The log seems a bit short. There's only 30 seconds of activity, I can't see any glaring errors.

I think this one should be better. After the last thing it´s crashing. 
[latest.log](https://github.com/Iskallia/Vault-public/files/6612265/latest.log)

**Comment by Tommmmy02** [comment]
> Are you using the server pack?

Yeah, the serverpack do not have any mods in it and after filling all the mods in the log is the same as above :/

**Comment by waidesoper** [comment]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

There's your problem - you need to allocate more memory to Java.

**Comment by Tommmmy02** [comment]
> Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
> 
> There's your problem - you need to allocate more memory to Java.

You mean to the server ?

**Comment by waidesoper** [comment]
On the server, yes.

**Comment by Tommmmy02** [comment]
> On the server, yes.

Sorry for my late answer but it worked thank you very much ;)
