### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by DraamaQ** [Iskallia/Vault-public#34]
My game crashes when i open an advanced vending machine with a trader inside. Can open without trader, but crash when theres one in 
![crash](https://user-images.githubusercontent.com/81376585/112501519-9bde3880-8d89-11eb-9645-1a8364b38b18.jpg)

**Comment by Nimothy** [comment]
Hi @DraamaQ, could this be the same problem as #10?

**Comment by Enderized** [comment]
Does only apply when you put a trader item it which literally does say:
"Right click to generate Trader"

So if you put a trader in which has no trades.

**Comment by DraamaQ** [comment]
@Nimothy Yes, probably the same issue! thanks

**Comment by jmilthedude** [comment]
#10 trader core needs to be generated first.
