### ISSUE TITLE
Is there any way to decrease the number of trader cores needed per player for making an eternal?

### ISSUE THREAD

**Issue by JoeFoxe** [Iskallia/Vault-public#348]
If i can do this through datapacks what would i need to add/change?

**Comment by waidesoper** [comment]
The NBT Tag that controls this is "MaxCoreCount" on the cryochamber tile entity.

**Comment by Capser1234** [comment]
Go to config>the_vault>cryo_chamber.json and add your name like its is already done for iskall, stress and antonio. it should  end up looking something like this:
```
{
  "INFUSION_TIME": 5,
  "GROW_ETERNAL_TIME": 10,
  "STREAMER_CORE_REQ": {
    "AntonioAsh": 100,
    "iskall85": 100,
    "Stressmonster101": 100,
    "<YOUR NAME>": <AMOUNT OF TRADERS>
  }
}
```
Make sure to check your file afterwards with a json validator to make sure you have not missed anything. Hope this helps :P

**Comment by JoeFoxe** [comment]
thanks both of you! :)

**Comment by joshuaepstein** [comment]
@JoeFoxe If you are finished with this issue, I would recommend closing this to make it easier for the developers to find the issues that need fixing
