### ISSUE TITLE
might be generation bug 

### ISSUE THREAD

**Issue by Bright7185** [Iskallia/Vault-public#35]
This is my first vault room and dead end straight away 
![2021-03-25_15 54 14](https://user-images.githubusercontent.com/17716203/112503014-7d287380-8d82-11eb-8385-8e31fe8fb58c.png)

![2021-03-25_15 55 52](https://user-images.githubusercontent.com/17716203/112503177-9c270580-8d82-11eb-97cd-a95b5d1a7efb.png)

**Comment by iskall85** [comment]
Yes this has been fixed in the next version of Vault 1.0.2
