### ISSUE TITLE
Shulker "Right-click to add" doesn't work

### ISSUE THREAD

**Issue by DDR-Khat** [Iskallia/Vault-public#352]
**Describe the bug**
Quark provides the ability to right-click items into a shulker similar to how "bundles" work in the upcoming Minecraft 1.17 version. This does not seem to work with this modpack.

**To Reproduce**
1. Get a Shulkerbox.
2. Pick up an item in your inventory.
3. Hover it over the Shulker
4. Right-click it.
5. Become sad it didn't work ):

**Expected behavior**
Right-clicking the item into the shulker should fit it into the shulkerbox without needing to place it.

**Screenshots or Crash Report**
N/A

**Info (please complete the following information):**
- World Type: Either/Or
- The_Vault 1.0.2

**Additional context**

**Comment by bmemike** [comment]
This isn't an issue with the the_vault mod but a conflict with Mouse Tweaks.

To get this to work as expected, you need to set `RMBTweak=0` in config/MouseTweaks.cfg.

**Comment by DDR-Khat** [comment]
I didn’t say this was specifically a conflict with the_vault , but thanks for the exact info I needed all the same (:
