### ISSUE TITLE
Keep getting same Broken Vault

### ISSUE THREAD

**Issue by Dr3mmy** [Iskallia/Vault-public#355]
I created a Normal Vault, but when I spawned in, I was on the roof of the Vault.  I rolled back to a backup, and tried a Rare and ended up on the roof again.  Kept doing the roll backs and going through Spectator / Creative opened chests and throwing trash out of inventory.  Whenever I would make a new Vault, no matter which type crystal I used, I ended up with the SAME Vault, down to even having the trash still floating on the ground.

Is there a file where the Vault creation is at and how can I reset it back to creating random Vault Dungeons?

The 2nd picture with Red Circle shows where I had previously gone into Creative and dug down to find the Vault.
I had gone into Spectator as well to see if I could find the Portal and exit but could not find the portal.

As last ditch effort, I killed the Boss hoping that would push a recycling of the Vault Generation but when I went back in on a different type Crystal, I was back on the roof with the same hole.

- World Type: Single Player
- The_Vault Version 1.3
![Rare Vault](https://user-images.githubusercontent.com/85458815/120938714-e4936580-c6d9-11eb-9437-caf7ef6d6745.png)
![Rare Vault_roof](https://user-images.githubusercontent.com/85458815/120938715-e78e5600-c6d9-11eb-8366-aa44a8f44be9.png)

**Comment by BONNe** [comment]
You can try removing the vault dimension. 
It should then generate a new world.

**Comment by Dr3mmy** [comment]
> You can try removing the vault dimension.
> It should then generate a new world.

Do not know what file that would be though, can you provide a picture??

**Comment by BONNe** [comment]
it is in your saved world under the dimensions folder.
Named the_vault

**Comment by Dr3mmy** [comment]
YES!!  Thanks BONNe!!  
![Screenshot 2021-06-06 192013](https://user-images.githubusercontent.com/85458815/120944842-3baa3200-c6fc-11eb-9776-db9e527ee829.png)
