### ISSUE TITLE
Cowardice Enchantment no longer working.

### ISSUE THREAD

**Issue by WindsWatcher** [Iskallia/Vault-public#359]
**Describe the bug**
The Cowardice enchantment is no longer giving extra strength when full health.

**To Reproduce**
1.Enchant armor piece with Cowardice 3
2. Get full health
3. no benefit given.

**Expected behavior**
Before the update to 1.3 HOTFIX, this enchantment would give a Strength buff.  This enchantment should still give the Strength buff.

**Info (please complete the following information):**
- World Type: Iskall85 VH server.
- The_Vault Version  1.0.3

**Additional context**

**Comment by BONNe** [comment]
The same for some other Dungen Gear mod things, like soul (holy) fist, does not deal damage.

**Comment by BONNe** [comment]
Cowardice enchantment does not give a strength buff. It now gives direct damage increase.

Unfortunately, daggers has reach -1. This means, that they cannot hit anything. 

This was changed by Dungeons Mod.

This bug report can be closed as there are no issues with cowardice.
