### ISSUE TITLE
Question: How to switch abilities?

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#36]
#### Question

I unlocked 2 abilities however, I cannot switch between them. 
Based on #29 ability wheel should not open, but I do not know what should I do to change ability then.

#### Steps to reproduce the behavior

If you have unlocked just 2 abilities, there is no obvious way how to switch between them.
The only key that comes from the Vault Hunter mod is: Ability Wheel key, however, pressing it nothing happens.

![ability-bug](https://user-images.githubusercontent.com/1344358/112505309-558ed680-8d95-11eb-9d75-5d0763a2822b.png)

#### Aditional Information
Based on code line: https://github.com/Iskallia/Vault-public/blob/33798da8a1189af2a5327c1aa58c0b6c13345973/src/main/java/iskallia/vault/event/InputEvents.java#L53

I do not see a why how abilities can be switched without an ability wheel. The code directly says, that if there are 2 or less abilities, it does nothing.
In the first ability implementation, there were hotkeys that allowed to switch abilities. However, they are not present in the public release, so it is not possible to switch between 2 abilities.

**Comment by iskall85** [comment]
Sorry for not clarifying in the previous post.
Skill Button (Ability Cast Key) + ScrollWheel.
The reason for the <= 2 is graphical maths in zones i believe.

**Comment by BONNe** [comment]
Thanks a lot.
I did not find any information about this, so it would be nice if we could get some info in Ability Screen or under controls. 
It is not obvious that it is cast key and scroll.

(I tried only wheel key and scroll :D)
