### ISSUE TITLE
Can't launch mod pack at all

### ISSUE THREAD

**Issue by Fancymanjm** [Iskallia/Vault-public#363]
Every time I launch the mod pack it loads for a few seconds than instantly crashes doesn't give me a crash report or anything.

1.Launch the game
2.Launch the game
3.Launch the game
4.Launch the game

If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- The_Vault Version [1.2/1.3/1.3hotfix] I've tried all versions I am also using Curse forge to download the mod pack
![Crash](https://user-images.githubusercontent.com/86175710/122660224-dc154300-d14d-11eb-9037-e783796fc5f9.png)

Other mod packs work fine this one just doesn't seem to want to launch for me at all.

**Comment by waidesoper** [comment]
Can you please post a crash log?

**Comment by Fancymanjm** [comment]
> Can you please post a crash log?

There isn't a crash report already looked in folder.

**Comment by Fancymanjm** [comment]
[latest.log](https://github.com/Iskallia/Vault-public/files/6681649/latest.log)

Theres a log if this will help at all.

**Comment by waidesoper** [comment]
Check your Java version. It needs to be 1.8

**Comment by Fancymanjm** [comment]
Will check that real quick

**Comment by waidesoper** [comment]
Optifine Is not compatible

**Comment by Fancymanjm** [comment]
Mb about the optifine but even before that was in was doing same thing

**Comment by Fancymanjm** [comment]
Just updated Java will see if that fixed it.

**Comment by Fancymanjm** [comment]
[latest.log](https://github.com/Iskallia/Vault-public/files/6681651/latest.log)

With optifine removed and java updated still same issue.

**Comment by waidesoper** [comment]
You've got an issue with applied energistics.

**Comment by waidesoper** [comment]
Can you try without chlorine?

**Comment by Fancymanjm** [comment]
Sure

**Comment by Fancymanjm** [comment]
Instantly crashed same as all others

**Comment by waidesoper** [comment]
What other mods have you added?

**Comment by Fancymanjm** [comment]
None that was all. The Cholrine and optifine that I removed both.

**Comment by Fancymanjm** [comment]
I literally installed the mod pack like 40 mins ago freshly launched it didn't work got my friend to install and launch it worked fine for him and than I looked to see what others said about the issue couldn't find anything that was talking about right as they launched it.

**Comment by waidesoper** [comment]
Can you try using Gdlauncher?

**Comment by Fancymanjm** [comment]
Yeah sure.

**Comment by Fancymanjm** [comment]
That seems to have gotten it to work. Guess it's something related to CurseForge

**Comment by waidesoper** [comment]
It looks like the version of minecraft it downloaded was corrupt.

**Comment by Fancymanjm** [comment]
Weird why it did that for me but my friends worked fine.
