### ISSUE TITLE
Enchantment Applicator is not capped at any level.

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#365]
**Describe the bug**
Enchantment Applicator from industrial foregoing is not capped at any level. If you have a lot of books or just use Botania enchantment, you can easily create overpowered enchanted items, like fortune 20, sharpness 20 and etc.

**To Reproduce**
1. Craft enchantment applicator and enchantment extractor
2. Combine fortune 3 book with a tool that has fortune 3 -> result will be fortune 4.
3. Continue the loop until you reach the enchantment level that you desire.

**Expected behavior**
I would expect that enchantments should be capped at some level. Like we can get Antic (+1), Super (+2) and Legendary (+3) books, so I would assume that all enchantments should be capped at ORIGINAL_MAX + 3 levels. 

**Screenshots or Crash Report**
![2021-06-21_11 55 18](https://user-images.githubusercontent.com/1344358/122735397-abd1bf80-d287-11eb-9aca-b505bdccdb27.png)

**Info (please complete the following information):**
- World Type: Iskall Danny Server however it is reproducible in a single-player too.
- The_Vault Version 1.0.3 

**Additional context**
If there is no way how to block the enchantment max level, then I suggest blocking Enchantment Applicator, as this is just broken.
If someone uses Botania, they just need one book and they can get to any level they want. 
The other option would be to block Botania Enchantment as it does not consume a book, however, it does not solve the issue, just increases the effort for crafting the books. And as this process can be automated, it is just a matter of time.

**Comment by BONNe** [comment]
This issue was introduced after updating Industrial Forgoing:
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/820

**Comment by bmemike** [comment]
The Botania Mana Enchanter only lets you apply enchantments to an unenchanted item so I'm not sure that this problem exists for Botania.

**Comment by BONNe** [comment]
Season 2 has solved the issue.
