### ISSUE TITLE
I have completed the vault crystal recipe but was not given a vault crystal.  All show as complete but it does not drop.  I have tried relogging, breaking the alter, and loading a previous backup.  This is a single player world. Vault Hunters - Official Modpack 1.3-hotfix.  I am using ATLauncher but added the pack directly from curseforge

### ISSUE THREAD

**Issue by Peterpan228** [Iskallia/Vault-public#369]
**Describe the bug**

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by BONNe** [comment]
Yea...
Vault Hunters lacks a tutorial for people who do not watch streamers.

You need to power the altar with a Redstone signal... often it is just a button on the side of the altar.

**Comment by Peterpan228** [comment]
Derp. Thank you! I'm literally sitting here watching Iskall and forgot that's a thing. Thank you!
