### ISSUE TITLE
Cant Start

### ISSUE THREAD

**Issue by ItsBuffy99** [Iskallia/Vault-public#37]
When I start it crashes after a while.
I gave it 9 gigs
That is the Error:
Error: java.lang.IllegalStateException: GLFW error before init: [0x10008]Cocoa: Failed to find service port for display

**Comment by Avilla32** [comment]
^^ that is a Mac M1 error. Forge doesn't support M1 processor until version 36.0.43 which is Minecraft 16.5 so the modpack would have to be updated to 16.5 before it would work. (not a developer of this project just know of this issue as I do develop for Mac) Minecraft runs GLFW 3.2.2 and the API call doesn't support M1 Macs which is the main problem.
