### ISSUE TITLE
Ghost Blocks on a server Everywhere. Trees, Portals, Vaults.

### ISSUE THREAD

**Issue by JoeFoxe** [Iskallia/Vault-public#370]
**Describe the bug**
Ghost Blocks on servers when growing non vanilla trees, same goes for treasure rooms dont generate the bedrock around the door client side as well as the door, it shows as an iron door but server side it generated. The portal block when generating a vault as well doesnt generate the full portal client side but are ghost blocks.  Some chests inside the room just show as pink or purple wool until right clicked. there are just a lot of ghost blocks on a server.

**To Reproduce**
1.bonemeal a palm tree on a server
2.create a vault portal on a server
3.find a treasure room on a server
4.

**Expected behavior**
Trees to grow and show client side without having to relog after growing a single tree. Treasure rooms to be properly generated without ghost blocks.

**Screenshots or Crash Report**
trying to grow a palm tree
https://gyazo.com/75e1bf6ecaf3c7c9ec5b7dba89e7cb15
https://gyazo.com/15f647458cc882c8c3431882dddd9d25

vault treasure room
https://gyazo.com/d8685c0e79425ffab5be99c726c91f86
https://gyazo.com/43efd91af37dff62ebb56d1db8fa02a8

vault portal
https://gyazo.com/aee3d626c33798ff1f3c017a56b04a42

**Info (please complete the following information):**
- World Type: Server
- Compiled code from github as the vault mod.

**Additional context**

**Comment by BONNe** [comment]
Emm... that is weird... did you compiled correctly?

But well, I would suggest to use official modpack, as it has already everything prebuild.

**Comment by JoeFoxe** [comment]
yea I just ran the gradlew build in commandprompt, also I would like to edit the mod to my liking which is why I wanted to get the compile to work properly. im really not sure why it does this.

**Comment by JoeFoxe** [comment]
but the compile works fine for you?

**Comment by waidesoper** [comment]
What's the error you are getting when you run gradlew build?

**Comment by waidesoper** [comment]
Hey Joe, BONNe has compiled from source and has their code under releases on their github repository. You may find other people who have done the same thing, and may be open to helping you modify the code by checking the repositories of other people who have submitted Pull Requests to this repository.

**Comment by JoeFoxe** [comment]
ohhh awesome, yea ill see if I can snag BONNe's version. I did snag a bunch of her pull requests and added them in myself. as for the error. I dont get any compile errors. it runs and I get in game issues as shown above.

**Comment by waidesoper** [comment]
Check with other people too...

**Comment by JoeFoxe** [comment]
will do, and thank you so much for the help :)

**Comment by JoeFoxe** [comment]
So I found out this was caused by EmbellishCraft. whenever that mod is installed it causes all sorts of ghost blocks. my code was fine all along. I was so lost lmao. Thanks anyways for the help everyone :)
