### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by webolljr** [Iskallia/Vault-public#38]
The game locks up as soon as it tries to launch a new word. I am using gdlauncher with 8 gigs of ram allocated to the game.

It seems to do fine until it tries to verify you game with mojang and then it just freezes with the 100% screen of the world creation

Here is the end of the gdlauncher log

[12:53:18] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config dropper: item-insertion:false
actions.js:2035 [12:53:18] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Opt-outs:sign_decor
actions.js:2035 [12:53:18] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 31%
actions.js:2035 [12:53:18] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 32%
actions.js:2035 [12:53:19] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 38%
actions.js:2035 [12:53:19] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 43%
actions.js:2035 [12:53:20] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 49%
actions.js:2035 [12:53:20] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 53%
actions.js:2035 [12:53:21] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 58%
actions.js:2035 [12:53:21] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 62%
actions.js:2035 [12:53:22] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 68%
actions.js:2035 [12:53:22] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 72%
actions.js:2035 [12:53:23] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 78%
actions.js:2035 [12:53:23] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 83%
actions.js:2035 [12:53:24] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 86%
actions.js:2035 [12:53:24] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 90%
actions.js:2035 [12:53:25] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 96%
actions.js:2035 [12:53:25] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Time elapsed: 12725 ms
actions.js:2035 [12:53:25] [Server thread/INFO] [co.po.ne.NeonCraft/]: HELLO from server starting
actions.js:2035 [12:53:25] [Server thread/INFO] [is.is.co.IskallUtilities/]: Server is starting
actions.js:2035 [12:53:25] [Server thread/INFO] [co.by.BYG/]: BYG: "Server Starting" Event Complete!
actions.js:2035 [12:53:25] [Server thread/INFO] [FTB Utilities Backups/]: Backups folder - /Users/willie/Library/Application Support/gdlauncher_next/instances/Vault Hunters   Official Modpack/backups
actions.js:2035 [12:53:25] [Server thread/INFO] [minecraft/IntegratedServer]: Changing view distance to 11, from 10
actions.js:2035 [12:53:28] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@4d58ce7d[id=ffd3e739-d6d4-4081-bded-1933a76fd36c,name=Ocsisor,properties={textures=[com.mojang.authlib.properties.Property@295679cb]},legacy=false] (local:E:6787b6a6) lost connection: Internal Exception: java.lang.ClassCastException: net.minecraft.network.login.ServerLoginNetHandler cannot be cast to net.minecraft.client.network.play.IClientPlayNetHandler
﻿
​
And then it freezes

**Comment by Nimothy** [comment]
Hi @webolljr, this looks to be the same issue as #8.
Maybe close this and put a comment on that issue?

Worth noting other users have had success importing the mode into CurseForge and running from there.
