### ISSUE TITLE
In vault hunter season 2 pete is using a storage system that has a remote control thing that u can use to pick up or put stuff in it from around the world so u can make a phoenix crystal and bring all of ur gems and stuff u want to dupe and put it in the storage system and kill ur self i hope iskall reads this massage

### ISSUE THREAD

**Issue by TheCalmBoy** [Iskallia/Vault-public#385]
**Describe the bug**

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by BONNe** [comment]
No, you cannot. You already can try that in public pack. 
Wireless inventories are disabled in the vault.

**Comment by TheCalmBoy** [comment]
Oh ok thanks
