### ISSUE TITLE
Server Crashes after opening a vault even with powerful specs

### ISSUE THREAD

**Issue by RedPxnda** [Iskallia/Vault-public#388]
For some reason whenever a player on my server tries to open and enter a vault the server crashes. The server's specs are great,(
Intel i9-9900K / Xeon E-2236 @ 4.8Ghz, DDR4 2666MHz Memory, and 2 cores) The log says a tick took too long, but we used to be able to open vaults.

**Crash Report**
https://pastebin.com/pkBuAnDh

**Info**
- World Type: Server
- The_Vault Version: 1.3 hotfix

**Comment by waidesoper** [comment]
Try deleting the vault dimension files. The error you are having is while the raid initialisation is looking for blocks inside the vault to replace

**Comment by RedPxnda** [comment]
Unfornately it did not work.

**Comment by RedPxnda** [comment]
after resetting some of the vault configs I managed to get it to work.
