### ISSUE TITLE
Cant launch modpack with OptiFine

### ISSUE THREAD

**Issue by BearTaffy** [Iskallia/Vault-public#39]
when I try to launch VH with optifine mid loading Minecraft crashes. But when I take optifine out of the mods folder it works just fine.
![image_2021-03-25_193124](https://user-images.githubusercontent.com/81381255/112517173-b079fb00-8da0-11eb-8b5a-28e73482f90d.png)

I use CurseForge with 8gb of ram.
I have tried to use 6gb and also MulitMC

**Comment by ItsBuffy99** [comment]
yep vault hunters is not working with Optifine bc of the models

**Comment by BearTaffy** [comment]
> yep vault hunters is not working with Optifine bc of the models

oh i didnt know that ty
