### ISSUE TITLE
Unable to join self hosted server.

### ISSUE THREAD

**Issue by Olivoz** [Iskallia/Vault-public#396]
Describe the bug
Unable to join server because the usage of client side only classes in server enviroment.

To Reproduce

Create a Forge server and copy mods in to the server mods folder and launch

Screenshots or Crash Report
https://pastebin.com/ULvRgXDE

World Type: Multiplayer
The_Vault Version 1.0p1.8.8
Additional context

**Comment by scalda** [comment]
Please wait for server files to be posted as there are certain fixes, for servers

**Comment by Olivoz** [comment]
Alright :)

**Comment by RicoNijeboer** [comment]
Do you know when we can expect the server files?

**Comment by Schoktra** [comment]
Even with the "server files" I am unable to join the server after doing a fresh delete and install of just the server pack files.

**Comment by Olivoz** [comment]
Things appear to work fine. Did remove mcmt to fix random crashes.
