### ISSUE TITLE
Immersive Engineering and MCMT

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#398]
**Describe the bug**
While playing on my own server I run into issues with Immersive Engineering Villager Homes (engineer).
Sever just freezes and crashes on time out.

I could not get why it is happening and try random stuff -> remove mods one by one that was involved in stack trace.
And I got lucky -> removing MCMT solves the issue and the server is not crashing anymore.

**To Reproduce**
1. Create a new world with modded stuff.
2. Find a village with Immersive Engineering homes.

**Expected behavior**
The crash should not happen.
There already were reports about crashes in VaultHunters Legacy with the same issue.
Maybe there is a way around how to keep immersive engineering homes and mcmt mod?

**Info (please complete the following information):**
- World Type: [Server]
- The_Vault Version 1.1

**Comment by scalda** [comment]
mcmt is removed from the v1.2 of the pack as well as the server files

**Comment by BONNe** [comment]
Confirm that setting up server from client version, MCMT is not present.

However, the presented server pack for 1.2 still includes in mods directory.
As expected, removing MCMT solves the world crash.

Thanks for the answer @scalda .
Was not sure if that mod is important for Vault dimension performance or not.
