### ISSUE TITLE
Private server keeps timing players out permanently after a set amount of time

### ISSUE THREAD

**Issue by shadescar24** [Iskallia/Vault-public#399]
Just as the title says, my friend's private server keeps timing players out after around 6-7 minutes in the 1.2 version of the new pack. The command prompt doesn't crash or anything, but all players will get timed out and will be unable to join until the server is reset again.

I don't really know how to reproduce it. He just portforwarded using the server files provided in the curseforge website. We're all able to join, but the server times out at specific times. This is why it's leading me to believe that this is an issue with the server files itself instead of something on our end (I really don't know though).

**Comment by BONNe** [comment]
The same issue: https://github.com/Iskallia/Vault-public/issues/398

One way would be to pregen the world as iskall servers a re doing, but I think there should be found more reliable fix

**Comment by shadescar24** [comment]
Hmmm ok. When my friend gets home later I will try both of the solutions mentioned.

**Comment by BONNe** [comment]
Update:
https://github.com/Iskallia/Vault-public/issues/398#issuecomment-934137349

Just remove jmt_mcmt mod

**Comment by shadescar24** [comment]
Ok yeah we just played for around 2 hours without any issues so this fixed it, thanks!
