### ISSUE TITLE
Altar chest loot table contains Curios items 

### ISSUE THREAD

**Issue by DrTasslehoff** [Iskallia/Vault-public#406]
**Describe the bug**
vault altar chests still contain curios items 

**Expected behavior**
They should not be obtainable.

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/42073120/136055872-331635ae-5df0-49cc-b914-f059c3b05c75.png)

**Info (please complete the following information):**
- World Type: single player
- The_Vault Version 1.2

**Comment by Pancakezombie2** [comment]
I'm pretty sure they are supposed to be there. They have been in the alters since the alters came out in VH2. There also hasn't been any mention from anyone saying they were getting taken out. The only issue with the alter loot was a tablet thing that wasn't supposed to be there.

**Comment by BONNe** [comment]
Iskall confirmed in todays stream that it is a mistake, and will be removed.
