### ISSUE TITLE
This source code is showing the wrong software license

### ISSUE THREAD

**Issue by waidesoper** [Iskallia/Vault-public#410]
**Describe the bug**
The code hosted here claims to be GPLv3 where the author never intended the code to be open source

**To Reproduce**
go to the code page and look at the license in the about section

**Expected behavior**
the licence should state "All rights reserved" or some similar licence type

**Additional context**
This issue can be resolved by changing the LICENSE file in the root of the pack to the type that the author originally intended. Alternatively, just a post to README.md stating that the license is incorrect would be better than leaving it in the state that it is.

**Comment by BONNe** [comment]
But the code is open source.
You can browse through it.
And author placed the code in Github for public access.

**Comment by jmilthedude** [comment]
This is the code repo for the previous version of the mod. The season 2 updates, features and revisions are, thus far, closed source.

**Comment by waidesoper** [comment]
**Douwsky — 05/10/2021**
_it was never intended to be open source, this was a mistake. it was never intended to be modified and then redistributed. so if you ask me, don't do it_

Isn't it better to just get rid of the ambiguity? If the source code is meant to be public, but not modified or redistributed, just put a notice where people are going to look and know. The only way I found out was to ask a developer, publicly, which made me look like a fool, and opened me up to a tonne of criticism because "I shouldn't be stealing other people's work and claiming it as my own". I'm not the only person who has assumed that the licence listed is the intended licence - for example: [https://www.curseforge.com/minecraft/mc-mods/vault-research](https://www.curseforge.com/minecraft/mc-mods/vault-research)
