### ISSUE TITLE
Game crashes when loading into a world or server

### ISSUE THREAD

**Issue by Starmarine06** [Iskallia/Vault-public#412]
**Describe the bug**
When I create a new world or try to join a world I created it will just get stuck at the loading screen on 100
or when I join a server it will say generating terrain and crash

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/64924939/136170608-9916a715-8cee-4ee2-9b63-1fefd08e12f8.png)

**Info (please complete the following information):**
- World Type: Both
- The_Vault Version 1.2

**Comment by Starmarine06** [comment]
The only way I get it to work is by removing the FTB chunks, FTB backup, and the Xareo's Worldmap mod.
Cuz of this I can't join servers.
(This never happened to the VH: Legacy mod pack)

**Comment by BONNe** [comment]
Could you try to reinstall a mod pack from a scratch? 

As it looks like you do not have FTBChunks mod installed for some reason.

**Comment by Starmarine06** [comment]
> Could you try to reinstall a mod pack from a scratch?
> 
> As it looks like you do not have FTBChunks mod installed for some reason.

yes for sure

**Comment by Starmarine06** [comment]
ooh thx a lot it worked
I'm so thank fun thx a lot bonne
