### ISSUE TITLE
No xp gained from successful boss kill

### ISSUE THREAD

**Issue by Hazelthejoy** [Iskallia/Vault-public#414]
I was level 4 with none of the xp bars filled when I entered the vault. I successfully killed the boss, received my crate, and returned to the over world only to receive no xp for my efforts. The xo bar did not move at all. Here is the full context

I am zellybell playing in the mango iskallia server. I was close to leveling to level 4 when I died in the vault. The resulting xp leveled me up to level 4 with no bars filled. While I was rebuilding, someone from the server asked to restart the server for a change. After the restart, I found and ate 5 burgers and my xp bar did not move. I then entered the vault where I successfully killed the boss and my so bar still did not move. I feel softlocked and afraid to try any more vaults for fear I will be losing out on xp

**Comment by perschip** [comment]
I have the same issue with the vault. I have ran 3 vaults before noticing I was earning xp. I have eaten burgers and still nothing. Another player on Summer is having the same issue as me. My IGN is InvertMC
