### ISSUE TITLE
Vault rocks not working on Alter

### ISSUE THREAD

**Issue by Hindzee** [Iskallia/Vault-public#417]
When i click the vault rock onto the vault alter it doesn't work. This is on a private server using the server pack provided. Any fix?

**Comment by PatateNouille** [comment]
I have the same issue here, I deleted the jmt_mcmt and jmt_mcmt_core mods from the server to fix the constant timeout issues, but apart from that there were no further modifications

**Comment by Hindzee** [comment]
So I got this fixed... the server operator must log in to confirm the difficulty of the vaults. After that it works perfect
