### ISSUE TITLE
Overgrowth Seed Not Craftable Without Botania

### ISSUE THREAD

**Issue by DarkHorseAsh1** [Iskallia/Vault-public#423]
**Describe the bug**
Even with the ingredients, you can't craft the overgrowth seed without botania. This makes it basically the only possible thing on the Hard pillar that can't be crafted early on and given the removal of end dungeons and how hard it is to find overgrowth seeds in desert temples, this is kinda a needed thing. Given every other option on that pillar of the altar is craftable this seemed like an oversight.

**To Reproduce**
1. Open crafting table
2. Try and put in ingredients
3. Fail
4.

**Expected behavior**
To craft a seed

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.0

**Comment by DaycareJr** [comment]
You can find the min loot chests

**Comment by BONNe** [comment]
Seeds can be found:
- In the Vault boss creates and God Altar Chests
- In the loot chests that are around the world (mineshafts, temples, dungens, strongholds)

**Comment by jmilthedude** [comment]
Confirmed, this is by design. You are meant to find them.
