### ISSUE TITLE
End portal in the Vault

### ISSUE THREAD

**Issue by HoogaSwe** [Iskallia/Vault-public#424]
**Describe the bug**
End portal in the Vault do not generate chests.

**To Reproduce**
1. Finnish portal whit the last eye of ender. 
2.
3.
4.

**Expected behavior**
We did have 2 vaults now that the challenges to complete the End portal to get gilled chest do not work on our server we have been 2 player that notice same issue.

**Screenshots or Crash Report**
![2021-10-07_21 54 08](https://user-images.githubusercontent.com/81357122/136456494-8260f2b2-34d7-4661-a16d-a8df2e2764d2.png)

**Info (please complete the following information):**
- Server, Self hosted
- 1.2

**Additional context**
Add any other context about the problem here

**Comment by BONNe** [comment]
So some of the custom functions in Vault Hunters are done with command blocks.

The issue you are experiencing is that command blocks on your server are disabled.
You need to enable them:
in server.properties change: `enable-command-block=false` to `enable-command-block=true`

**Comment by HoogaSwe** [comment]
Yes i did see this change in the 1.5 server files. We will test this out when we get one portal room :)

**Comment by HoogaSwe** [comment]
Yes can now say thgis was the issue that command block was not activated. Thank you!
