### ISSUE TITLE
Error: multiple incorrect recipes 

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#427]
**Describe the bug**
This is not an important bug, however, I do think that these issues should be fixed, as it is not impossible to do, and will avoid fewer errors in a log files.

**To Reproduce**
1. Join a server or start a fresh world.
2. Open the log file and notice the error.

**Expected behavior**
Either recipes for items are fixed with proper existing elements, or removed completely.

**Screenshots or Crash Report**
```
Parsing error loading recipe industrialforegoing:washing_factory
com.google.gson.JsonSyntaxException: Unknown item 'industrialforegoing:meat_feeder'
```
```
Parsing error loading recipe supplementaries:flower_box
com.google.gson.JsonSyntaxException: Unknown item 'supplementaries:flower_box'
```
```
Catching
com.google.gson.JsonSyntaxException: Unknown item 'industrialforegoing:mob_imprisonment_tool'
```
```
Parsing error loading recipe industrialforegoing:dissolution_chamber/infinity_launcher
com.google.gson.JsonParseException: com.google.gson.JsonSyntaxException: Unknown item 'industrialforegoing:mob_imprisonment_tool'
```

**Info (please complete the following information):**
- World Type: Both
- The_Vault Version 1.2

**Comment by scalda** [comment]
This is due to the "meat_feeder" being disabled in the pack

**Comment by BONNe** [comment]
> This is due to the "meat_feeder" being disabled in the pack

Yes, I know the reason, but shouldn't recipes that relies on removed items be removed too?
Or replaced with different items.

It is not like it is a very important bug. I do not care about these items. However, this would clean up the log file from unnecessary error messages.

**Comment by scalda** [comment]
Correct and this is what I am currently going over fully cleaning up what the pack devs have missed.
 like you say it will clean up the logs

**Comment by BONNe** [comment]
These errors are fixed
