### ISSUE TITLE
Vault Burgers not providing XP

### ISSUE THREAD

**Issue by massartnoah** [Iskallia/Vault-public#432]
**Describe the bug**
When eating vault burgers xpXPbar shines but no XP is granted

**To Reproduce**
1.Make vault burger
2.Eat vault burger

**Expected behavior**
XP bar should shine and XP should increase

**Info (please complete the following information):**
- Server
- 1.4

**Comment by DaycareJr** [comment]
This is ment to be a chance you wont get a lot of xp for vaultburgers. You are going to get 0- a little bit of xp

You just lowrolled

**Comment by iskall85** [comment]
Intended behaviour, the vault burger always triggers the XP bar, but can yield 0% if you low roll, it's 1 in 4 to get 0.
