### ISSUE TITLE
X marks the spot/ Rubik's cube/End portal rewards do not appear or activate at all

### ISSUE THREAD

**Issue by JoeFoxe** [Iskallia/Vault-public#435]
**Describe the bug**
Once completing the puzzle room it does not give the reward or the X marks the spot room doesnt generate the side rooms.

**To Reproduce**
1.Dig down in the X  marks the spot room
2.Stand in room waiting for it to change
3.Nothing happens
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [Server]
- The_Vault Version [1.2]

**Additional context**

**Comment by BONNe** [comment]
So some of the custom functions in Vault Hunters are done with command blocks.

The issue you are experiencing is that command blocks on your server are disabled.
You need to enable them:
in server.properties change: `enable-command-block=false` to `enable-command-block=true`

**Comment by JoeFoxe** [comment]
oh my lord.. I cant believe i didnt see this before. Thank you haha '^^
