### ISSUE TITLE
While wearing a chestplate, if swapped for a Vault Chestplate which is higher level, it crashes the game

### ISSUE THREAD

**Issue by Pranav-RB** [Iskallia/Vault-public#441]
**Describe the bug**
I had a netherite chestplate. Tried to wear the vault chestplate knowing it was too high without removeing the other chestplate first. The vault chestplate got equipped but then it was thrown out of inventory and I had the netherite chestplate on the mouse. Then the game crashed. Tried to open the world again but it still crashed

**To Reproduce**
1. Wear a vanilla armor piece
2. Hold a vault armor on top of the vanilla one and click
3. Crash
4.

**Expected behavior**
I expected the vault armor to pop off and the mouse still holding the vanilla armor

**Screenshots or Crash Report**
Cannot take screenshots and Crash reports says unexpected behaviour

**Info (please complete the following information):**
- World Type:  Single Player
- The_Vault Version: 1.5

**Additional context**
Unable to enter the world again. Will use NBT Explorer to try and remove that chestplate

[crash-2021-10-11_08.16.54-server.txt](https://github.com/Iskallia/Vault-public/files/7319208/crash-2021-10-11_08.16.54-server.txt)

**Comment by jmilthedude** [comment]
Hello, a crash report would possibly still be helpful.

**Comment by Pranav-RB** [comment]
Sorry, it was 3 in the morning and took a while. I've updated it and attached the report. Thank You

**Comment by Pranav-RB** [comment]
Sorry, it was 2 in the morning and took a while to load and crash. I've updated it and attached the report

**Comment by Pranav-RB** [comment]
I tried using NBT Explorer and I did delete a chestplate but it was a netherite one. But it still crashed when i tried to open it. If it's possible to restore the world could anyone please help?

**Comment by jmilthedude** [comment]
Thank you for that crash report. That actually looks to be unrelated to the chestplate swap issue. There was an issue with a loot table which was causing that crash. There should be an update soon to fix this.

**Comment by Pranav-RB** [comment]
Is there anyway to fix my world? :(

**Comment by jmilthedude** [comment]
It looks like the update has gone live on CurseForge now. You can update your VH modpack to the latest 1.5.1 and let me know if you are able to get into your world.

**Comment by Pranav-RB** [comment]
It worked. Thank you so much!

**Comment by jmilthedude** [comment]
Awesome, glad to know it is resolved. Happy Hunting!
