### ISSUE TITLE
Decorator cheese

### ISSUE THREAD

**Issue by 06Wanderer** [Iskallia/Vault-public#443]
**Describe the bug**
"Mail Boxes" combined with the "Post Box" from Mr. Crayfish's Furniture Mod works inside the vault, connected to the outside world. This means people can receive (We have not tested sending yet) things while they are inside the vault, by placing down a mail box. 

**To Reproduce**
1. Unlock "Furniture" for 1 point
2. Craft a mail box and post box
3. Send stuff back and forth like a Cheeserson

**Expected behavior**
Cheese

**Info (please complete the following information):**
- World Type: Mango Server [Canada 1]
- The Vault Version: 1.5

**Additional context**
They look super cool and are super functional outside the vault :D

**Comment by 06Wanderer** [comment]
We did test sending things from in the vault and it works as well

**Comment by iskall85** [comment]
Thank you! Fixed in version 1.6 (v1.8.10)
