### ISSUE TITLE
Afterlife modifier not respected if the player dies via health alter after the boss kill

### ISSUE THREAD

**Issue by Hazelthejoy** [Iskallia/Vault-public#444]
I was running a raffle, afterlife vault. I killed the boss, then after I received the crate I killed myself by draining health into a health altar. Upon respawn, my gear was lost, nothing was restored. 

I am Zellybell on the Mango Iskallia server, playing on pack version 1.5

**Comment by jmilthedude** [comment]
This will be fixed in the next update. Players will no longer take damage after killing the boss.
