### ISSUE TITLE
[Minor] Duplicate entry in altar loot table

### ISSUE THREAD

**Issue by UnderscoreSkyy** [Iskallia/Vault-public#447]
**Describe the bug**
Apple entry in the resource altar pool is duplicated

**To Reproduce**
```
{
          "type": "minecraft:item",
          "weight": 4,
          "name": "minecraft:apple",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": {
                "min": 2,
                "max": 8
              }
            }
          ]
        },
	    	{
          "type": "minecraft:item",
          "weight": 4,
          "name": "minecraft:apple",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": {
                "min": 2,
                "max": 8
              }
            }
          ]
        },
```

**Expected behavior**
To me there should be only one entry just for consistency

**Screenshots or Crash Report**

**Info (please complete the following information):**
- World Type: All
- The_Vault 1.8.8 and upward

**Additional context**
I'm aware that removing the duplicated entry or merge them both to keep the same total weight won't change a thing in the end. just wanted to signal it

**Comment by jmilthedude** [comment]
Thank you for pointing this out. This has been resolved and will take effect in the next update.
