### ISSUE TITLE
Server crashing after start up trying to generate record rewards

### ISSUE THREAD

**Issue by Karoiyu** [Iskallia/Vault-public#448]
**Describe the bug**
After our servers automated restart at the server loaded back up and proceeded to keep crashing and i think its saying it was to do with generating the trophy box and record rewards. 

**Screenshots or Crash Report**
[crash-2021-10-11_14.12.20-server.txt](https://github.com/Iskallia/Vault-public/files/7322367/crash-2021-10-11_14.12.20-server.txt)

**Info:**
- World Type: Server
- The_Vault Version 1.5p 1.8.9

**Comment by jmilthedude** [comment]
Please update the pack and server to version 1.5.1. The Vault mod should be the_vault-1.5p1.8.9.1.jar. This should fix your issue.
