### ISSUE TITLE
Vault Issues

### ISSUE THREAD

**Issue by Dragoslayer2006** [Iskallia/Vault-public#45]
The common vaults once done generating have not loot in the chests, and the vault generation looks really weird. Also the timer does not work!

![2021-03-25_15 36 21](https://user-images.githubusercontent.com/81389209/112541351-47cf5600-8d81-11eb-8a8a-9dc2e25c5dad.png)
![2021-03-25_15 37 06](https://user-images.githubusercontent.com/81389209/112541441-60d80700-8d81-11eb-9314-d83a42cd2695.png)
![2021-03-25_15 37 21](https://user-images.githubusercontent.com/81389209/112541447-62093400-8d81-11eb-8b1a-a0e03a688f63.png)

**Comment by Dragoslayer2006** [comment]
I did the update to the vault, but I dont know if doing this had something to do with it: https://www.youtube.com/watch?v=M-oKnAwF88g

**Comment by Dragoslayer2006** [comment]
This seems to be the problem for every vault type. Mainly the empty chests

**Comment by Dragoslayer2006** [comment]
Killed a vault boss, and the time when down to 22 seconds. The boss crate was also empty. 
![2021-03-25_16 09 54](https://user-images.githubusercontent.com/81389209/112544224-c083e180-8d84-11eb-8dc7-bfc2c1ba44e6.png)
![2021-03-25_16 09 59](https://user-images.githubusercontent.com/81389209/112544264-ca0d4980-8d84-11eb-9cb1-e629cbb895b8.png)

**Comment by Nimothy** [comment]
Hi @Dragoslayer2006, if I were you I'd look at using MultiMC and importing the Zip as an instance. 
The zip you have doesn't have any mods any of the extra mods that are required. 

You probably want to download the latest Zip that Iskall published and import it into MultiMC

**Comment by jmilthedude** [comment]
It looks to me you are using the Vault mod without the pack. This is what generation looks like when you are missing the mods that contain the blocks that were used to build out the vaults.

**Comment by Dragoslayer2006** [comment]
Thank you all!!
