### ISSUE TITLE
Blocks that need support (torch, carpet, etc.) are destroyed if the block below is vein mined

### ISSUE THREAD

**Issue by Guybrrush** [Iskallia/Vault-public#452]
**Describe the bug**
Blocks that need support (torch, carpet, etc.) are destroyed if the block below is vein mined.
By destroyed I mean it is not dropped as an item but voided

**To Reproduce**
1. Pick Vein Miner, level and specialisation do not matter.
2. Vein mine a block with a torch on top of it
3. The torch gets destroyed without dropping

**Expected behavior**
The torch gets dropped.

- World Type: Both Server (EU-2) and Solo
- The_Vault Version 1.5.1

**Comment by jmilthedude** [comment]
I ma investigating this. Currently, I am seeing something else. The torch or carpet stays floating instead of dropping. Will update when the expected behaviour the outcome.

**Comment by BONNe** [comment]
I had the same issue with pickerang.
I placed redstone components on bricks, and then vein mined the bricks with pickerang and redstone components disappeared.

**Comment by jmilthedude** [comment]
This should be resolved and the fix will be released in the next update.. If there is still an issue with the Pickarang @BONNe , that is likely on Quark's end.

**Comment by BONNe** [comment]
This issue has reappeared. 

I do not know exactly when but in the latest version (1.12.4) blocks that require support are voided again.

**Comment by sb-khelbig** [comment]
For me it hasn't reappeared (at least not the initial bug). Instead the old behavior that @jmilthedude has been seeing of floating (in my case) redstone is still happening. Vein mined the glass blocks under the redstone with a silk touch pick.

![grafik](https://user-images.githubusercontent.com/3788587/162587721-728c2765-35fb-4f46-99be-ceec751c0d3d.png)
