### ISSUE TITLE
Can't place Vault rock on the altar, Private server

### ISSUE THREAD

**Issue by Durmad1** [Iskallia/Vault-public#463]
**Describe the bug**
On my friends private server we just made our first vault altar and when trying to place the vault rock on it, nothing happens. Works fine in single player

**To Reproduce**
1. Make an altar
2. put the rock in

**Expected behavior**
A reason to why that can happen/ A fix to the problem

**Screenshots or Crash Report**

**Info**
- World Type: friends Private server
- The_Vault Version 1.5

**Additional context**

**Comment by DaycareJr** [comment]
Did you try to braik and place it again? it sometimes happens that it buggs out and it will work after replacing it

**Comment by Durmad1** [comment]
Yes, first thing  we did

**Comment by d0zzer2** [comment]
Has someone logged into the server as OP yet? It won’t ask like single player you have to sign in as OP to get the difficulty pop up, without choosing a difficulty you can’t do anything.

**Comment by Durmad1** [comment]
Sorry for late response, going in as OP and setting difficulty fixed it. Thanks
