### ISSUE TITLE
Vault axes can't break 2 blocks tall plants

### ISSUE THREAD

**Issue by Guybrrush** [Iskallia/Vault-public#483]
Vault axes can't break 2 blocks tall plants. The vaults are full of such plants, meaning that very often, the monsters are shielded from our attacks.

This does not occur with Vault swords

- World Type: [Server Eu-2
- The_Vault Version 1.6 and previous

**Comment by jmilthedude** [comment]
This is actually intended. Vault Axes are meant to be weapons so they have had their efficiency values set to 0 to disallow them from being used to mine anything. The only thing I can suggest is to avoid 2-tall plants when fighting as best you can.
