### ISSUE TITLE
Tank specialization : Chill -> Eternals are affected too

### ISSUE THREAD

**Issue by Guybrrush** [Iskallia/Vault-public#485]
**Describe the bug**
Your own eternals are affected my the slowness aura from the Chill ability

**To Reproduce**
1. Summon your eternal(s)
2. Use your Tank: Chill Ability

**Expected behavior**
The Eternal(s) is unnaffected by the slowness

**Info (please complete the following information):**
- World Type: EU-2
- The_Vault Version 1.6

**Comment by jmilthedude** [comment]
I found the issue. Will be patching.

**Comment by jmilthedude** [comment]
Fixed in the next update.
