### ISSUE TITLE
Puzzle room gilded chest

### ISSUE THREAD

**Issue by mballt** [Iskallia/Vault-public#488]
entered the puzzle room
i puted down 2 crates to get the required puzzle blocks that i had with me then i put the in their position then pressed the button and the 2 crates got destroyed and turned into gilded chests
*i have the footage for that*

**Comment by BONNe** [comment]
Yes, that is how that works.
If you place something in the spot where gilded chests will be generated, these blocks will be destroyed.

**Comment by mballt** [comment]
so i will not be refunded?

**Comment by BONNe** [comment]
> so i will not be refunded?

Well, that is an issue you should talk with server administrators, not in the github.

**Comment by mballt** [comment]
ok thank you.
