### ISSUE TITLE
Vault stews shouldn't be in boss crates

### ISSUE THREAD

**Issue by elixdreamer** [Iskallia/Vault-public#5]
Iskall mentioned that boos crates shouldn't include any stews.
Just looked fairly quickly in the code and food this line. Could be related?

https://clips.twitch.tv/BlindingOilyChickpeaRalpherZ-3JkMSfa_VmhLZ8Ov

https://github.com/Iskallia/Vault-public/blob/9f0f27854c5f6b28f968b6750dbbdc5619ff5b64/src/main/resources/data/the_vault/loot_tables/chest/boss3.json#L1035

**Comment by jmilthedude** [comment]
The loot tables for public release are still WIP. Thank you for pointing it out though.
