### ISSUE TITLE
Paxel + speed

### ISSUE THREAD

**Issue by HoogaSwe** [Iskallia/Vault-public#509]
**Describe the bug**
If you have speed +1 on a paxel and then eat a canybar to get speed 5, if you switch to the paxel it will lower the speed to paxel speed. And paxel speed will not stack whit armor speed. 
Exampel i had 1 paxel whit speed +1 and armor whit speed +1 and normal speed trait 2, but it will not stack to become speed 4.

**To Reproduce**
1. Eat candy bar 
2. switch to speed paxel
3.lose candy bar bonus.  
4.

**Expected behavior**
Paxel not remove speed 5 buff, and stack whit armor. 

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Server 
- The_Vault Version 1.15.1

**Additional context**

**Comment by jmilthedude** [comment]
I believe I see the issue, requires some testing.

**Comment by jmilthedude** [comment]
Hmm, I actually experience a different issue. With speed 1 on the paxel, eating a candy bar grants speed 6 as it should, but.. It is infinite. Until you move from the paxel when it reverts to speed5 from the candy bar and continues counting down. 

I will confirm the intended effect and fix this.

**Comment by jmilthedude** [comment]
The fix should be present in a future update. It will work the same as vault gear now.
paxel: speed 1
chest: speed 1
talent: speed 1

speed 3 while paxel is held.
