### ISSUE TITLE
Placeholder Blocks in vault instead of chests/ores/obelisks

### ISSUE THREAD

**Issue by KaiHD** [Iskallia/Vault-public#510]
**Describe the bug**
Majority of vaults hasn't generated correctly where placeholder blocks are appearing and resulting in the vault being unbeatable (due to no obelisks). On some occasions the first few rooms will be fine and the remainder will not work, and others the entire vault is like this..

**To Reproduce**
N/A - Issue happens randomly when entering vaults.

**Expected behavior**
Vaults to generate correctly, including chests/obelisks/etc.

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version: 1.6.2 (this issue has persisted across multiple versions)

**Additional context**
- I have had the same vault crashing issue as per other logs on here, and as advised have deleted the vault dimension and run vaults/debug command until the vaults started generating correctly again. However this bug then shows randomly on future vaults.
- The first time I experienced this was after loading a back-up however the vaults have worked since and I haven't loaded a back-up for some time.

![OresChests](https://user-images.githubusercontent.com/76951153/138572358-3baffa8b-b6d9-45c9-9346-cbd916c753e3.png)
![Chests](https://user-images.githubusercontent.com/76951153/138572360-32ed55e3-15ad-492f-b4dd-36c9136d69e2.png)
![Chests3](https://user-images.githubusercontent.com/76951153/138572363-7b5aeea5-a9e5-46c6-bc0b-86d46d1415a4.png)
![Chests4](https://user-images.githubusercontent.com/76951153/138572364-a93aaf20-cbdd-4b50-beae-acd3f013cd92.png)
![Obelisks](https://user-images.githubusercontent.com/76951153/138572365-24731f46-286a-4ce1-a42a-a0970dc4a02b.png)
![Ores](https://user-images.githubusercontent.com/76951153/138572366-b53af8f2-8e0f-4290-8cf4-62e07b632d68.png)

**Comment by sethy1999** [comment]
I had similar issues in my vault at level 9 with an easy modifier.  I thought perhaps it may have been caused by it being a lower level vault but then I see you are at 19.

**Comment by KaiHD** [comment]
I may have found a potential fix, I’ve only ran 2 vaults so far but they generated correctly, will keep this open for a little bit longer in case the problem starts again but will close if after a few more tests it keeps running good!

I’ve seen mentioned about on here and discord about old config files/repositories with the immersive crashes, so I had a thought that I originally had VH Legacy and have just updated on curseforge throughout on the same profile (if you’ve done the same I might be on to something)…

I moved my save file out of the pack, completely uninstalled the pack and then re-installed from fresh at 1.6.2, moving my save file back in and (fingers crossed) it seems to have fixed things.

May be worth a try and if it does work would appreciate if you’d let me know on here, might help some others and would help close this report :)

**Comment by KaiHD** [comment]
Happy to close this - After running a few vaults I have not seen any placeholder blocks after doing the above so seems to fix the issue.
