### ISSUE TITLE
Paxel Rush + Any passive haste from a vault items increases multiplier

### ISSUE THREAD

**Issue by Abaan404** [Iskallia/Vault-public#512]
**Describe the bug**

While holding an item such as an axe or sword that grants the haste potion effect, if the player switches their item to a paxel within 15 seconds (before the effect expires) to a rush/haste paxel, the haste stacks onto the paxel indefinitely. Effectively granting effects like haste 2 on a rush 1/haste 1 paxel. (No haste skill abilities were unlocked)

**To Reproduce**
1. Obtain a vault gear with haste on it
2. Obtain a paxel with a Rush modifier
3. Hold the vault gear to get the haste from it
4. within 15 seconds, switch to the rush paxel
5. The player gets more than intended haste effect indefinitely while holding the paxel.

**Expected behavior**
After switching to the paxel from the vault item, the haste modifier should drop back down to haste 1 after 15 seconds.

**Screenshots or Crash Report**
https://imgur.com/DkrfWhE

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.6.2

**Additional context**

**Comment by jmilthedude** [comment]
#509 duplicate. will be fixed in a future update.
