### ISSUE TITLE
Infinite water bucket turning into normal bucket after it is used on statue cauldron

### ISSUE THREAD

**Issue by PhilDaMan** [Iskallia/Vault-public#514]
Bug:

Used a infinite water bucket on a statue cauldron and it turned into a normal bucket. 

Expected behaviour:
Water to be added into the statue cauldron without reverting to a normal bucket (as the VH buckets now cost a pog). This was strange for me because I thought the infinite water bucket would be coded as a infinite water source block (like a creative water source block) but instead it still functions as a bucket. 

Info :

World Type: Iskallian VH Server
The_Vault Version 1.6.2

**Comment by jmilthedude** [comment]
This will be fixed in a near future update. Thanks for reporting.
