### ISSUE TITLE
Twerker causing cactus to act strange

### ISSUE THREAD

**Issue by magicalex234** [Iskallia/Vault-public#520]
**Describe the bug**
When using twerker to speed up cactus growth, newly grown cactus blocks will ignore the mechanic that causes cactus to break, and will even delete blocks above the cactus to grow cactus there

**To Reproduce**
1.  Place sand (or snad, applied to both) on the ground with cactus on it.
2. Level the twerker talent to level 3 or 4 (but applies to both, and lower levels don't grow cactus)
3. Place any block that breaks cactus 2 blocks above the 1 tall cactus, sneak to force grow. The block will be replaced by cactus once it grows
4. Place a 2nd block to the side of that new cactus, it will break that cactus as intended, but new cacti that grow there will not 

**Expected behavior**
Cactus should break if a block is to the side of it, and should not delete blocks above it when growing, regardless of how it grew.

**Screenshots or Crash Report**
<img width="1440" alt="example" src="https://user-images.githubusercontent.com/60080843/138775914-a8ab933f-32dc-44e2-ad32-efd7a8c44574.png">

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version:  1.6.2

**Additional context**
initially tested on snad, but this bug also applies to vanilla sand.

**Comment by jmilthedude** [comment]
This is fixed in the next version.
