### ISSUE TITLE
The game crashes/freezes 

### ISSUE THREAD

**Issue by balutbek31** [Iskallia/Vault-public#522]
While I am loading the world, it sometimes freezes 
the crash log sometimes says about not enough memory in minecraft and sometimes event click handle thing
and sometimes it just saves the game after the game says it is loading the world
I have screenshot of only the time that its ran out of memory
![2021-10-26](https://user-images.githubusercontent.com/75940029/138912824-8a46c78e-e0ae-4df1-9ecc-3f4f8c3f1309.png)

**Comment by BONNe** [comment]
https://vaulthunters.gg/installguide

Check (6.) for Curseforge launcher or (3.) for MultiMC

**Comment by balutbek31** [comment]
I am already using curseforge
But I will try MultiMC

**Comment by BONNe** [comment]
My comment was about memory -> how to assign more memory
Point 6 in Curseforge instructions and point 3 in MultiMC launcher.
