### ISSUE TITLE
Vault crash, World no longer loads

### ISSUE THREAD

**Issue by Khayd2** [Iskallia/Vault-public#540]
**Describe the bug**
After entering a gilded vault crystal, Game lagged out and stopped breaking blocks. Relogged to fix it like every other time this has happened and world gets stuck at 100% loaded.

**To Reproduce**
1.Copy Save from location attached in additonal content.
2.Try to load world

**Expected behavior**
Load back into the vault, able to continue on the run

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/13619301/139780403-7758fe2a-82ac-49e1-844a-b683811e4a1d.png)
Game doesn't crash, just doesn't finish loading.

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version 1.6.2

**Additional context**
I have removed JMT_MCMT.JAR
Save file here: https://drive.google.com/file/d/1bgihrDA1ltLw5F7WwcMr6E-a30mssIXB/view?usp=sharing 

.

**Comment by crzyblue** [comment]
Sounds like you have corrupted vault chunks... https://github.com/Iskallia/Vault-public/issues/469

You can resolve this by going into your save, and deleting the vault dim, and the the_vault_VaultRaid.dat (this file is located in /saves/worldname/data

**Comment by Khayd2** [comment]
I had tried just removing the Vault Dimension, but not this other file.

This seems to have fixed it. TYVM
