### ISSUE TITLE
Breaking Blocks and opening chests

### ISSUE THREAD

**Issue by TerrisFarrinz** [Iskallia/Vault-public#543]
**Describe the bug**
People on my server can enter the vault but once they enter the vault they are unable to break any blocks or open any chests. They can still kill mobs and get the loot from them. But not even normal chests can be opened once inside the vault. Outside the vault everything appears to work normally.

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**
To be able to mine blocks inside the vault and open chests.

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server] Server
- The_Vault Version [e.g. 1.0.1]  1.6.2

**Additional context**

**Comment by Zoinzibar** [comment]
Hello, i'm having the same issue, do you have a fix ?
