### ISSUE TITLE
its not realy a bug report

### ISSUE THREAD

**Issue by balutbek31** [Iskallia/Vault-public#548]
I just want to know how can I link like the youtube or even twich account to the mod like iskall????????????????????????

**Comment by bmemike** [comment]
Twitch integration is not part of the public release and it won't be added.

**Comment by balutbek31** [comment]
but why, if I am streamer wouldnt it be more fun to stream this modpack with the twich intergration?

**Comment by bmemike** [comment]
That's the decision that was made.

**Comment by balutbek31** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
