### ISSUE TITLE
CraftTweaker error: Unknown item tag

### ISSUE THREAD

**Issue by Uklusi** [Iskallia/Vault-public#573]
**Describe the bug**
When loading a world with default configs, CraftTweaker raises an error about missing tags (`the_vault:perfectcommongems`, `the_vault:playergems`, `the_vault:nonplayergems`).

As a consequence, some recipes are displayed incorrectly in JEI (e.g. healing potion).

**To Reproduce**
1. Load a world with default configs
2. Open logs/crafttweaker.log
3. Confirm that the following line is present: `[DONE][CLIENT][ERROR] Unknown item tag 'the_vault:perfectcommongems'`

**Expected behavior**
No errors when loading CraftTweaker modifications, and correct recipes for e.g. the healing potion.

**Screenshots or Crash Report**
[crafttweaker.log](https://github.com/Iskallia/Vault-public/files/7534201/crafttweaker.log)

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version: 1.6.2p1.8.10.2

**Additional context**
Writing a CraftTweaker file adding the missing tags fixes the problem, but that currently only works in single player worlds.

**Comment by joshuaepstein** [comment]
You have probably not updated properly

**Comment by Uklusi** [comment]
Tested on a new instance, problem did not happen. Closing
