### ISSUE TITLE
Vault Timer

### ISSUE THREAD

**Issue by DevCorp-beta** [Iskallia/Vault-public#6]
The vault timer doesn't count down even after killing the bose it is stuck on 20
![image](https://user-images.githubusercontent.com/64924939/112440002-d67cac80-8d5a-11eb-99fd-5da77d11120a.png)

**Comment by joshuaepstein** [comment]
I am also getting this issue

**Comment by scalda** [comment]
Hi that you for the report we are looking into it today and hopefully will have a fix ready for the official release of the pack

**Comment by KaptainWutax** [comment]
Fixed in 1.0.1.
