### ISSUE TITLE
Enchantment Extractor from Industrial Foregoing duplicating enchantments

### ISSUE THREAD

**Issue by Dravox1234** [Iskallia/Vault-public#640]
**Describe the bug**
When placing an enchanted item with only 1 enchantment on it into the enchantment extractor, you'll receive 3 copies of the enchantment. When placing an enchanted item with 2 enchantments on it into the enchantment extractor, you'll receive 2 copies of the second enchantment. This can be used to duplicate Ancient Enchanted books or Super Enchanted books

**To Reproduce**
1. Place down and power an enchantment extractor
2. Place an "Addon: Speed Tier 2", an "Addon: Efficiency Tier 2", and an "Addon: Processing Tier 2" into the upgrade slots
3. Add a stack of books to the book slot in the extractor
4. Place an enchanted item with only 1 enchantment on it (ex unbreaking IV) into the blue "input enchantment item" slot. 
5. The machine will remove the enchantment from the item, but will provide you with 3 copies of the enchantment (ex 3 copies of Unbreaking IV).

-Alternate steps 4 and 5.
4. Place an enchanted item with 2 enchantments on it (ex Protection V and unbreaking IV) into the blue "input enchantment item" slot. 
5. The machine will remove the enchantments from the item, but will provide you with 1 copies of the first enchantment and two copies of the second enchantment (ex 1 Protection V and 2 Unbreaking IV).

**Expected behavior**
I expected the enchantment extractor to output 1 copy of the enchantment like it does when you place an enchanted item with multiple enchantments on it. Ex. I place a vault helmet with Protection V and Unbreaking IV and Respiration III into the extractor, and I get 1 book of Protection V, 1 book of Unbreaking IV and 1 book of Respiration III. 

**Screenshots or Crash Report**
These 11 copies of the Unbreaking IV book were made using 1 copy of the unbreaking IV book, several regular books, and a few copies of unbreaking III (since that needs to be applied before you can apply Unbreaking IV).
![image](https://user-images.githubusercontent.com/96046209/145778871-48a76c22-f132-4980-828f-8829f32e449c.png)

**Info (please complete the following information):**
- World Type: - Iskallium Server - CAN 14 (Charm server)
- The_Vault Version - Vault Hunters-1.9-1.10.3 - H2

**Additional context**
After making the enchantment extractor, I was testing various odd items to make sure it was able to pull the enchantments off of it (ex paxel, pickarang, vault leggings), and I found the bug when I removed unbreaking III off of a vault Idol. I then confirmed it also worked with other items and enchantments as long as the item only had 1 enchantment (for tripling) or 2 enchantments (for doubling) when placed into the extractor.

**Comment by PhilDaMan** [comment]
Additionally ancient books can be combined with each other to increase the enchantment level.  After upgrading to an legendary book the enchantment cost goes from 80 levels to 1 level, allowing for cheap infinite level enchants. 

This was a major issue with season 1 balancing and why the mana enchanter from botania was removed.

**Comment by Dravox1234** [comment]
This bug was resolved in one of the newer versions of the pack.
