### ISSUE TITLE
Architect vaults not working how they are described in patch notes

### ISSUE THREAD

**Issue by Abcdhary** [Iskallia/Vault-public#656]
**Describe the bug**
The votes appear not to have changed in any way since the patch, so you get the same votes we’ve had for awhile. And the biggest thing that says something is wrong is when you complete a BAV you get a boss instead of a portal.
**To Reproduce**
1. Create an architect crystal 
2.type /the_vault crystal objectivecount 1
3.enter vault and go to summon boss vote, should only take two votes, initial vote and summon vote
4. A boss will appear and not a portal

**Expected behavior**
A portal is supposed to appear, also your supposed to get room votes.
**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server] single player
- The_Vault Version [e.g. 1.0.1] 1.10-1.11.1-h1.zip

**Additional context**

**Comment by crzyblue** [comment]
You need hotfix 2, and if it is a server, the config files need to be replaced.

**Comment by Abcdhary** [comment]
I posted this before the patch and forgot to close it
