### ISSUE TITLE
Haste on Gilded chest stopped working

### ISSUE THREAD

**Issue by labskaus86** [Iskallia/Vault-public#665]
**Describe the bug**
Couple of days ago I noticed, that the great "brrrr" feature when breaking Gilded chests in vaults due to Haste+efficiency stopped working in my Singleplayer world. Since we've seen this happening to the streamers on the occasional chest I didn't bother. But I realised it's happening now with every Gilded chest inside and outside the vault (I went into creative mode to put Gilded in the overworld to test). I created a new world, put a Gilded in the overworld and gave me haste 2 + effiV pick per creative mode and tadaa, the desired fast breaking reappears. 

Any idea how I can fix this problem in my SP world? It would suck to throw either the world with my progression in the trash or going back to open every Gilded by hand. 

**To Reproduce**
1. No idea, since I couldn't reproduce it in a new world

**Info (please complete the following information):**
- World Type: Single player
- The_Vault Version 1.10-1.11.1-H2

**Comment by Ithkamakazi** [comment]
Haste 4 or 5 is the haste level needed for insta nine of guilded chest I think it's 4 with eff 5

**Comment by labskaus86** [comment]
Well, don't know what I've done to make it work before, but thank you.
