### ISSUE TITLE
New modpack file crashes on starting while the old works

### ISSUE THREAD

**Issue by Kanav30** [Iskallia/Vault-public#68]
Hello i am having a problem that is that whenever i run the the second VH modpack after downloading on GD Launcher it crashes while the very first VH modpack is running fine. 
So can anyone tell why its happening and solution? it might help me a lot please

**Comment by Nimothy** [comment]
Hi @Kanav30,
Please can you provide the log files?
Also how did you import the pack into GD Launcher?

**Comment by Kanav30** [comment]
Um sorry for any problems but after I deleted zip and then again downloaded the zip file and imported into GDLauncher it is Woking now
Thank you for what all you did!!
