### ISSUE TITLE
World won't load.

### ISSUE THREAD

**Issue by Astroman250** [Iskallia/Vault-public#682]
The game loads fine, but once I start to load a world the game chugs for a bit then crashes. I have never had trouble with other modpacks, but this seems to eat up my CPU. When I open Task Manager if a world is loading it is ng 85%-90% of my CPU. My CPU is not that old and should run this fine. If you know how to solve it, It would be much appreciated.

**To Reproduce**
1.Open Modpack
2.Load a world

**Expected behavior**
I expected the world to load fine.

**Screenshots or Crash Report**
N/A

**Info (please complete the following information):**
- World Type: Single player
- The_Vault Version: The latest one

**Comment by jaxb3** [comment]
Same here, I have a Ryden 5 5600X CPU and the pack eats 85-95% during world generation, definitely needs to be looked at.

**Comment by bmemike** [comment]
Be sure you're allocating 8G to your running instance. Not having enough memory is the primary problem for these types of issues.

**Comment by Astroman250** [comment]
I have 32GB of RAM so I do not know why it would be a problem. Even when the only application I have open is vault hunters it still eats 85%-95% of the CPU.

**Comment by SoggyGiz** [comment]
I was having the same issue with the worlds not loading, i run curse forge, so i allocated as much memory to minecraft through curse forge and my world started loading just fine. Maybe give that a shot?

**Comment by bmemike** [comment]
> I have 32GB of RAM so I do not know why it would be a problem. Even when the only application I have open is vault hunters it still eats 85%-95% of the CPU.

Having RAM on your PC isn't sufficient. You have to configure your mod loader to tell java how much RAM it's allowed to use.

If you don't do this, you're likely not allocating enough memory to the running instance.

**Comment by Astroman250** [comment]
> > I have 32GB of RAM so I do not know why it would be a problem. Even when the only application I have open is vault hunters it still eats 85%-95% of the CPU.
> 
> Having RAM on your PC isn't sufficient. You have to configure your mod loader to tell java how much RAM it's allowed to use.
> 
> If you don't do this, you're likely not allocating enough memory to the running instance.

Thanks for the help. I'll try that. Would you be so kind as to tell me how. I use the curse fordge app by the way.
