### ISSUE TITLE
large ammounts of lag even with extra RAM allocated

### ISSUE THREAD

**Issue by SpoonMan234** [Iskallia/Vault-public#686]
**Describe the bug**
the game laggs for no apperent reason

**To Reproduce**
1. launch modpack
2. create single player world
3. game lags to an unplayable degree

**Expected behavior**
game runs at about 60 fps

**Screenshots or Crash Report**
N/A

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version 1.12.1 and 1.12.2

**Additional context**
I have allocated 4 more gbs of ram than recomended, but the game still runs at about 2-5 fps. I doubt this is a cpu issue, as my cpu hovers at about 25-35%.

**Comment by bmemike** [comment]
How much total RAM is allocated? The suggested amount is 8G.

You may also want to try to install Optifine.

There are a number of optimizations you can do - such as reduce mipmap to 0 and lower your render distance.

**Comment by SpoonMan234** [comment]
> How much total RAM is allocated? The suggested amount is 8G.
> 
> You may also want to try to install Optifine.
> 
> There are a number of optimizations you can do - such as reduce mipmap to 0 and lower your render distance.

I have about 12 gbs of ram allocated, and all my video settings are set to as low as possable.
Ive also heard optifine is not compatable with this modpack

**Comment by bmemike** [comment]
Optifine is compatible and certainly recommended.

You should target 8G of RAM. Adding more can cause some unwanted problems due to the way that java works. 

Additional suggestions:
* Turn mipmap level to 0.
* Turn biome blend to 0.
* Turn graphics to fast.
* Reduce render distance and FPS.

**Comment by SpoonMan234** [comment]
> 

some combanation of the fixes you gave me worked, thank you!
