### ISSUE TITLE
Trader Core issues

### ISSUE THREAD

**Issue by KillerImposter** [Iskallia/Vault-public#7]
> The elytra trader trades 32 elytras upto 3 times. This seems kind of excessive and may be a typo

> There is a trader of 1 vault gold for 5 vault gold which seems pointless

> There are a few blank trades (having id:"") in the code of loot table

**Comment by stacode123** [comment]
32? gez

**Comment by Dark-Ducky** [comment]
These are the proofs

![vault gold](https://user-images.githubusercontent.com/81279900/112444845-7abf1d00-8d74-11eb-87a3-63a29b6f2c54.png)
![Elytra loottable wrong](https://user-images.githubusercontent.com/81279900/112444852-7b57b380-8d74-11eb-9a4b-68e0f8b54c85.png)
![buy id missing](https://user-images.githubusercontent.com/81279900/112444855-7bf04a00-8d74-11eb-9e49-c5e0d1cca5b9.png)

**Comment by scalda** [comment]
These are now fixed ready for the official public release via curse

thank you for pointing these out
