### ISSUE TITLE
Error open Jar

### ISSUE THREAD

**Issue by Braindeado00o** [Iskallia/Vault-public#70]
I Can't open the jar folder on MACos. Don't know where the problem is. My mac hardware is definitely good enough

**Comment by Nimothy** [comment]
Hi @Braindeado00o, 
Which Mac do you have?
Is there an error message?
What do you mean by can't open the folder? What are you trying todo, import he .zip in MultiMC?

**Comment by Braindeado00o** [comment]
Die Java-JAR-Datei „the_vault-1.0.1-public.jar“ konnte nicht geöffnet werden.

**Comment by Braindeado00o** [comment]
Mac mini (Ende 2012)
2,6 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3 
Intel HD Graphics 4000 1536 MB

**Comment by Nimothy** [comment]
Hi @Braindeado00o, the official modpack isn't yet approved in Curseforge, we are still waiting on that. 
Here is the recommended way to install at the moment. 

1. Download and Install MultiMC
2. Launch MultiMC
3. Head into Settings => Java
4. Set Maximum memory allocation between 6 - 8 gb. ( either 6144 or 8192 )
5. Download the modpack from discord
6. If using Safari, go into trash and restore .zip file. 
7. In MultiMC click Add Instance
8. Select Import from zip in the box to the left. 
9. Navigate to the .zip downloaded from discord. 
10. Click ok.

Once the mods and pack are downloaded you should be able to launch the game by double clicking the icon.

**Comment by Braindeado00o** [comment]
Thank u 🙏🏻 Very much. Seems to work. 

Von meinem iPhone gesendet

**Comment by Nimothy** [comment]
@Braindeado00o glad to hear it, please feel free to close this issue 😄
