### ISSUE TITLE
Not being able to join my own server

### ISSUE THREAD

**Issue by JesseMMVI** [Iskallia/Vault-public#71]
I don't know if I am the only one, but when me and my friends want to join my own vault hunters server, we get the error message: failed to synchronize registry data of server, closing connection. I already checked the forge version of the pack and the version of the server, but they are the same. Also all the mods are installed correctly (I think. I just copied them from forge folder to server folder) Can someone pls help me with this because it is really frustrating...

**Comment by bmemike** [comment]
The server version will be released once the pack is approved by CurseForge.

**Comment by hannah98** [comment]
I see the [official modpack](https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack/files) on CurseForge but not the server files.  

I tried to run the only modpack zipfile on CurseForge but I get immediate errors when starting it.  Will there be a server version on CurseForge?

**Comment by iGoodie** [comment]
I'm moving this issue to #174
