### ISSUE TITLE
Tenos is still giving parry on the latest patch

### ISSUE THREAD

**Issue by TrevNel** [Iskallia/Vault-public#721]
**Describe the bug**
Tenos is still giving parry on latest patch. According to the patch notes, Tenos should only give luck and chest rarity, but I still got parry in my last vault

**To Reproduce**
1. update to 1.12.3
2. have tenos modifier up to 16
3. run vaults until you get a tenos modifier
4. check to see if you get the parry modifier

**Expected behavior**
Tenos should only give luck and chest rarity

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.
![2022-01-23_13 15 15](https://user-images.githubusercontent.com/8564673/150689910-7eb206ff-67cb-42a2-9892-938f91a07b43.png)

**Info (please complete the following information):**
- World Type: Server (Canada Autumn
- The_Vault Version1.12.3

**Additional context**

**Comment by Ithkamakazi** [comment]
Double check patch notes and server version, you may be on the patch where tenos doesn't give parry but the server may not be there yet

**Comment by TrevNel** [comment]
Yeah, that's what it was. I'm so used to updates being available and you having to update, so to avoid loading the pack again I just updated. I'll revert my version and log in again, wait until the server is updated
