### ISSUE TITLE
Cannot obtain a Trident as a 'rare' item for Vault Altar

### ISSUE THREAD

**Issue by AesMC** [Iskallia/Vault-public#743]
**Describe the bug**
There is no "crafting" recipe that lists obtaining a trident using vanilla methods. For instance, searching rotten flesh, and viewing recipes will show a drowned, with drops of gold ingots, and rotten flesh, but not a trident.

**To Reproduce**
1. Search "trident" in the crafting menu
2. Use the "view recipe" keybind to see crafting recipes (the one I see involves larimar and beniotite)
3. Observe that there is no mob drops section for the Trident
4. Perform additional search of rotten flesh to see that there is a mob drops section, and that trident is not listed under a Drowned.

**Expected behavior**
I expect to be able to receive a trident from Drowned Zombies as a drop, but it doesn't appear that it is possible ATM.

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/98505363/151287689-be0b3b82-05e9-4e7c-aa75-d598a20ae985.png)
![image](https://user-images.githubusercontent.com/98505363/151287696-6cced7e6-ae05-473f-94a2-df8b51f1fcd6.png)

**Info (please complete the following information):**
- Single Player
- The_Vault Version [1.7.0p1.12.1]

**Additional context**

**Comment by AesMC** [comment]
UPDATE: Just checked my version and realized there was a new one (1.12.4) which I have updated to and it shows the same issue.

**Comment by bmemike** [comment]
You can still get tridents from drowned. This hasn't changed. 

The recipe that contains vault items is in addition to the normal vanilla drop rates. 

If you look at zombies, skeletons and other mobs that have weapons and armor, those do not show up in the "drops" windows - but we know those can still drop. That's what you're seeing here.

**Comment by AesMC** [comment]
Thanks, guess I just have to hunt some more. I was turning zombies into drowned from my mob spawner, but thinking back, I don't think any were given tridents when they transformed.

**Comment by bmemike** [comment]
A zombie converted into a drowned won't generate or drop a trident. I believe that works on Bedrock, but not on Java. 

If you don't get lucky with some random in-the-wild kills, it's worth considering building a drowned farm. Nautilus shells also show up in altar recipes rarely.
