### ISSUE TITLE
Crash when joining a world

### ISSUE THREAD

**Issue by ghost** [Iskallia/Vault-public#775]
I've been playing for about a week already and suddenly I can't open any of my worlds because I just crash after the world loads to 100%. I can't seem to determine what's causing it from the crash report either. I have also tried to create a new world in a fresh install of the pack but unfortunately I keep getting the same crash.

- World Type: Single Player
- The_Vault Version 1.12.4

The earlier crash report here is from me loading my survival world (has a bunch of optimization mods), the later one is from creating a new world in a fresh install (no added mods at all).

**Comment by ghost** [comment]
nvm its working now lol

**Comment by Pnbllwzrd** [comment]
how did you fix it
