### ISSUE TITLE
Mobs too strong in level 0 vault

### ISSUE THREAD

**Issue by Gervi88** [Iskallia/Vault-public#78]
When entering a level 0 vault, all mobs can one-shot you with full diamond and even two-shot you with full ametrine. I saw other people talking about it here, but I didn't see anyone address the strength issue, only the two swords thing

**Comment by BONNe** [comment]
The same as #44

Intended by default configuration:
```
              {
                "NAME": "minecraft:generic.attack_damage",
                "MIN": 15.0,
                "MAX": 29.0,
                "OPERATOR": "set",
                "ROLL_CHANCE": 1.0
              },
              ```
It is intended for zombies to take 7 to 15 hearths.

**Comment by Gervi88** [comment]
then how is it resonable that in a level 0 vault, mobs could 2-shot, or 3-shot the player with ametrine armor? how are players suppose to progress if you instantly die in every vault until level 30, where the damage is lower than in the level 0 I'm pretty sure

**Comment by Gervi88** [comment]
Thanks!
