### ISSUE TITLE
Recipe tiny cole not working

### ISSUE THREAD

**Issue by Braindeado00o** [Iskallia/Vault-public#79]
The recipe for tiny cole (i assume tiny Charcole also) is not working, just throws the cole on the ground without crafting

**Comment by BONNe** [comment]
In the Vault Hunter modpack, a lot of modded things are locked at the start, and players must use knowledge points to unlock them. 

Coal Peace is lock behind Organization Research.
You can find which research required in JEI GUI by hovering over an item.

![tiny-coal](https://user-images.githubusercontent.com/1344358/112659045-b2a18f80-8e5c-11eb-9b8b-0f40e65997dd.png)

**Comment by Braindeado00o** [comment]
OH not the smartest from me :-)

**Comment by Braindeado00o** [comment]
Jeah pretty dumb from myself. Sorry for the unnecessary issue. Closed the issue
