### ISSUE TITLE
Relic Statues not increasing vault timer

### ISSUE THREAD

**Issue by jam7k** [Iskallia/Vault-public#812]
Multiplayer Server (not the owner) 
Had 6 unique relic statues sets (all crafted and placed by me). Vault timer is still the default 25:00 (tried Multiple Times after i noticed it). No One else has Statues on the serve yet so cant replicate.

**Comment by AntonioAsh** [comment]
When crafting, do not hold shift while clicking the statue into creation

**Comment by jam7k** [comment]
> When crafting, do not hold shift while clicking the statue into creation

Thank you very much, I don't know if I'll be able to craft them all again but that would be something I'd see myself doing for sure (holding shift)

**Comment by jam7k** [comment]
> 

I managed to craft new 8 relic statues and i got +4 mins on the timer as intended. Thank you, gonna close the issue as I think it's already reported on discord.
