### ISSUE TITLE
Errors when launching the modpack.

### ISSUE THREAD

**Issue by Kulfyr3** [Iskallia/Vault-public#824]
I'm not really sure where i should report this, but i've been having similar issues with a lot of modpacks, and was wondering why these errors occur. I would appreciate any help, but if this is the wrong place to post, i don't mind the post being deleted.

Here's the link to the error log: https://paste.ee/p/veN0w

**Comment by Midlou** [comment]
Yep, same error here

**Comment by Midlou** [comment]
Related error:

https://github.com/MultiMC/Launcher/issues/4470#issuecomment-1025114255

Downgrading Java to 312 solved the problem
