### ISSUE TITLE
vault alter changing recipe

### ISSUE THREAD

**Issue by sb-khelbig** [Iskallia/Vault-public#831]
We wanted to create the first vault crystal, right clicked the altar with a vault rock and got the following recipe:

3 gunpowder, 11 flint, 1 poison potato, 44 sand

We then threw one gunpowder at the alter, which it didn't accept. I then saw the alter with the vault rock but without a recipe.

Upon taking the rock and putting it back, we got a completely different recipe:

1 dragon head, 7 lapis, 16 lilac, 89 netherrack.

Although the new recipe is not too bad, i guess this is a bug, that should be looked into.

We are playing vault hunters official 1.12.4 on a server. The server is hosted locally. Apart from adding optifine and changing the config for fast workbench to show the recipe book, nothing else was changed.

**Comment by bmemike** [comment]
You're using the word "we", but altar recipes are per-player.

I assume what happened is that Player A placed the vault rock the first time. When it was broken, Player B picked up the rock and placed it into the altar - yielding a new recipe for that player.

If Player A were to replace the vault rock into the altar they should see the first recipe.

**Comment by sb-khelbig** [comment]
Thanks for clarifying.
