### ISSUE TITLE
Vault Timer not counting down?

### ISSUE THREAD

**Issue by KaiHD** [Iskallia/Vault-public#85]
Just ran my first common vault but when I go into the vault the timer stays at 25mins and does not count down
- Playing SP, newest version as per discord and using MultiMC to run

**Comment by BONNe** [comment]
The issue is fixed in the latest Vault version.
You should update your client with the newest VaultHunter version (1.0.1)

**Comment by KaiHD** [comment]
Sorry I didn't mean to close this
I'm using the latest version as per discord, but this downloads as version 1.0 (the one iskall posted yesterday afternoon)

**Comment by KaiHD** [comment]
Ignore this, worked it out, the mod didn’t update through the discord link but manually updated through curseforge
