### ISSUE TITLE
Server Failing

### ISSUE THREAD

**Issue by Kojouro** [Iskallia/Vault-public#871]
**Describe the bug**
With default forge version shipped with pack, server crashes on startup, regardless of java version. Updating forge version to 36.2.33 lets the server start, but I nor my wifey can connect to the server.

**To Reproduce**
1. Download server files
2. Try to run them
3. Try to update
4. Profit?

**Expected behavior**
The server to actually function.

**Screenshots or Crash Report**
[latest.log](https://github.com/Iskallia/Vault-public-S1/files/8354759/latest.log)

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version: 1.12.4

**Additional context**
If you need more info or anything, let me know, I've tried to include most if not all useful information. Might have missed or forgotten something though.

Edit: Mistyped the version, corrected it.

**Comment by chico1992** [comment]
Downgrade your java version to java 8_311 or java 8_312 the forge version used by vh is not compatible with the java version you used

**Comment by Kojouro** [comment]
This is all that pops up, even with that java version.

![image](https://user-images.githubusercontent.com/29297233/160305213-d16075c2-2eb2-4d33-b425-f37ea1e69643.png)

**Comment by chico1992** [comment]
this error is mostly linked to networking issues vh servers start by default on port 25569

**Comment by Kojouro** [comment]
Shouldn't I have still been able to connect through localhost? It gave that error, even for me.

**Comment by chico1992** [comment]
did you try to connect to localhost:25569 ?

**Comment by Kojouro** [comment]
That ended up working.. Just had to also port forward for her to be able to join, it's all working now though. Thank you so much!

**Comment by chico1992** [comment]
You're welcome
