### ISSUE TITLE
Vault Altar requires more Iron Ingots than config allows

### ISSUE THREAD

**Issue by scott-adkins-mediware** [Iskallia/Vault-public#88]
I have a vault altar that wants 2,412 iron ingots, but the config in (.minecraft\config\the_vault\vault_altar.json), shows a max of 1300:

    {
      "ITEM_ID": "minecraft:iron_ingot",
      "MIN": 400,
      "MAX": 1300
    },

[vault_altar.zip](https://github.com/Iskallia/Vault-public/files/6214299/vault_altar.zip)

**Comment by scott-adkins-mediware** [comment]
![2021-03-26_16 46 27](https://user-images.githubusercontent.com/41387694/112690838-d6f86e80-8e52-11eb-8793-3f9b6572d4b0.png)

**Comment by ImreBoersma** [comment]
hmm weird, are you sure you didn't change any configs/settings?
In the source code it says this:
`src/main/resources/data/the_vault/loot_tables/chest/altar.json`
```json
{
   "type":"minecraft:item",
   "weight":10,
   "name":"minecraft:iron_ingot",
   "functions":[
      {
         "function":"minecraft:set_count",
         "count":{
            "min":120,
            "max":6000
         }
      }
   ]
}
```

**Comment by scott-adkins-mediware** [comment]
Well it's entirely possible the vault_altar.json is ignored completely and I'm just assuming it's used.  But no, that's the json file straight from the freshly installed pack, no alterations were made.

**Comment by jmilthedude** [comment]
This is fixed in a recent commit. The altar was pulling from the json in config instead of the loot tables as it is supposed to. After the next update to the mod is pushed you may reopen if you still have the same issue.
