### ISSUE TITLE
Typo:  item minecraft:andesite is named "andeRsite"

### ISSUE THREAD

**Issue by ghost** [Iskallia/Vault-public#887]
the typo is on the items:
minecraft:andesite
minecraft:andesite_stairs
minecraft:andesite_slab
minecraft:polished_andesite
minecraft:polished_andesite_stairs
minecraft:polished_andesite_slab

**Comment by bmemike** [comment]
This is not a bug.

**Comment by EthanOfAmerica** [comment]
Not a bug, Iskall pronounces it "andersite" and he created the mod so that's what he named it, similar to how the rarest rarity is "Omega" because he says that a lot.

**Comment by ghost** [comment]
i got it, just seems like generally bad practice to introduce what is effectively a typo into the base game when you mod it because you pronouce it this way

**Comment by McMelonTV** [comment]
bruh
