### ISSUE TITLE
SpaceX cannot be crafted on a stonecutter

### ISSUE THREAD

**Issue by MrFierceWolf** [Iskallia/Vault-public#889]
Whenever you try to craft any SpaceX block from a stonecutter it just glitches and doesn't craft.

World Type: Server

**Comment by bmemike** [comment]
Dupe of #478

**Comment by MrFierceWolf** [comment]
Well then why hasn't it been fixed

**Comment by bmemike** [comment]
Because:
1) There's only so much the development team can work on at any given time and
2) It's not a priority
