### ISSUE TITLE
cant play due to frame rate

### ISSUE THREAD

**Issue by Martine1231** [Iskallia/Vault-public#896]
I can launch the modpack and go about the main menu but when I load into a world the frame rate is around 4fps. I have enough memory allocated to the game, I am using java version 1.8.0_51 64bit
![2022-04-10_20 46 13](https://user-images.githubusercontent.com/67770237/162663595-f3301c3c-c45a-46aa-b82e-4a2c0863c524.png).

What are the minimum recommended specs needed to play this well?

**Comment by tslom** [comment]
https://gyazo.com/f99ad5d2e5cf98877e3c4cffdf06ba6b

**Comment by Martine1231** [comment]
biome blend is the only thing I couldn't find to disable but the performance was no different. My java version, CPU, GPU Memory and Allocated ram all seem to be good enough for the job as far as I can tell but it remains unplayable

**Comment by SosnoviyBor** [comment]
It may be an issue with Radeon RX videocards cuz I saw few people (myself included) with such issue. Try this
Video Settings -> Animations -> Disable Terrain Animation

**Comment by Martine1231** [comment]
You are a absolute god send. Can play the game now. Thank you!
