### ISSUE TITLE
Crashes on placing Tiny Lilipads on water

### ISSUE THREAD

**Issue by krin-san** [Iskallia/Vault-public#92]
- Break a "Tiny Lilypad" from "Oh The Biomes You'll Go" mod
- Place it back on water
- Remember not to do that ever again 🙈 

Stack trace mentions `SuperSecretCakes.onCakePlaced` but I'm pretty sure Lilypad is not the cake. It even tastes different...

![2021-03-26_23 58 28](https://user-images.githubusercontent.com/2318002/112700783-35dbd900-8e8f-11eb-9872-2ba525715986.png)

[crash-2021-03-26_23.47.13-client.txt](https://github.com/Iskallia/Vault-public/files/6214661/crash-2021-03-26_23.47.13-client.txt)

**Comment by BONNe** [comment]
Duplicates #41

**Comment by krin-san** [comment]
Tough to find duplicates if issue title is just "Crash"...

**Comment by BONNe** [comment]
Agree, u also made a report for the crash before
