### ISSUE TITLE
Honey blocks can move hoppers

### ISSUE THREAD

**Issue by alex93293** [Iskallia/Vault-public#928]
**Describe the bug**
Honey blocks can move hoppers, which are supposed to be immovable objects.

**To Reproduce**
1. Place a hopper facing upwards
2. Place a honey block on the hopper
3. Place a piston facing the honey block
4. Power the piston

**Expected behavior**
The honey block doesn't move the hopper

**Screenshots or Crash Report**
Unpowered: 
![image](https://user-images.githubusercontent.com/46309763/166969298-29b90ab7-404a-466d-933b-d91917075169.png)
Powered: 
![image](https://user-images.githubusercontent.com/46309763/166969326-227dfca6-9a1e-422e-becf-59cc12888f16.png)

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version 1.7.2p1.12.4

**Additional context**

**Comment by BrianTB1** [comment]
Not a bug but  feature from the mod quark.
You can dissable it by pressing esc -> a blue q button left to options -> automation -> piston move tile entities, and uncheck that option.
For more information go here:
https://quarkmod.net/#features then automation and "piston move tile entities"

Can close the thread now 😀.

**Comment by alex93293** [comment]
Didn't know it was a feature not a bug, closing issue~
