### ISSUE TITLE
Vault timer and after-boss-kill-countdown aren´t starting

### ISSUE THREAD

**Issue by MrL159** [Iskallia/Vault-public#93]
The Vault timer doesn´t start when entering a vault. And also there are no mobs spawning except mobs from spawners. The Countdown-Timer after the boss kill also doesn´t start so you can´t leave the vault

**Comment by BONNe** [comment]
Duplicate of #84 
Do you use latest 1.0.1 version?

**Comment by MrL159** [comment]
No, I was still using 1.0. . I will then just update my version.
