### ISSUE TITLE
Flax not accepted in phytogenic insulator.

### ISSUE THREAD

**Issue by kaylaNsmart** [Iskallia/Vault-public#942]
Describe the bug
Flax seeds not accepted as input for phytogenic insulator.

To Reproduce
Try to put flax seeds in phytogenic insulator, it will not accept them.

Expected behavior
Put flax seeds into phytogenic insulator to duplicate.

Screenshots or Crash Report
If applicable, add screenshots or crash reports to help explain your problem.

Info (please complete the following information):

World Type: Server
The_Vault Version: will check when I get home

Additional context
Not sure if this is intended or a mod conflict.

Thanks.

**Comment by bmemike** [comment]
Flax Seeds are from Supplementaries.

Phytogenic Insulator is from Thermal Series. 

This modpack doesn't actually change any of those other interactions and, if you look in JEI, putting flax seeds are not an acceptable input for Phyto. This is working as intended as far as the modpack is concerned.

If you want to see support for this you should open a feature request with either Supplementaries or Thermal.

**Comment by kaylaNsmart** [comment]
> Flax Seeds are from Supplementaries.
> 
> Phytogenic Insulator is from Thermal Series.
> 
> This modpack doesn't actually change any of those other interactions and, if you look in JEI, putting flax seeds are not an acceptable input for Phyto. This is working as intended as far as the modpack is concerned.
> 
> If you want to see support for this you should open a feature request with either Supplementaries or Thermal.

Awesome, thanks for the reply/help!
