### ISSUE TITLE
Linux MultiMC 5 Mod IDs not resolvable

### ISSUE THREAD

**Issue by hackelle** [Iskallia/Vault-public#953]
**Describe the bug**
When trying to install the modpack, mod IDs cannot be resolved 

**To Reproduce**
1. Follow guide on https://vaulthunters.gg/installguide for MultiMC installation
2. When resolving Mod IDs, loading fails with Message "Unable to resolve mod IDs:
Some mod ID resolving tasks failed."

**Expected behavior**
Modpack added to MultiMC

**Screenshots or Crash Report**  
![image](https://user-images.githubusercontent.com/10208786/169654162-cf91b470-a064-410c-8e9f-1a73be21d36f.png)

**Info (please complete the following information):**
- World Type: N/A
- Modpack release 1.12.4

**Additional context**
Ubuntu 20.04, kernel 5.13.0-41-generic
java-1.17.0-openjdk-amd64

**Comment by chico1992** [comment]
That's due to the curseforge api changes nothing specific to vh

**Comment by hackelle** [comment]
Is there a way/workaround to run the modpack on linux? CF has no Linux release and MultiMC does not work then

**Comment by chico1992** [comment]
Yeah maybe by manually setting up everything, I'm also a linux user and haven't spend much time looking at how to manually set it up for future updates

**Comment by hackelle** [comment]
Ok, then I may have to wait for the future (luck) or the official release of CF on Linux (expected this year). Thanks

**Comment by chico1992** [comment]
@hackelle forgot to mention it previously but you might give gdlauncher a try it might still work there
