### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by joshuaepstein** [Iskallia/Vault-public#96]
I know that there is a recipe for vault stew in the Main pack for iskall and the streamers but there is no recipe for vault stew and there are also no recipes for leveling up vault crystals

**Comment by Gervi88** [comment]
iskall said when it was introduced that the recipe does not appear in JEI

**Comment by joshuaepstein** [comment]
Ok, do you know the recipe for vault stew @Gervi88

**Comment by NBlood** [comment]
> 
> 
> Ok, do you know the recipe for vault stew @Gervi88

Reddit figured it out yesterday:

from /u/cheekygirl43: "Between myself and u/magicalex234 we figured it out: Vault Stew Recipe - empty bowl - oozing pizza - Hunter’s Eye - Sweet Kiwi - Poisonous Mushroom - Vault diamond - 3x any Vault Gem"
