### ISSUE TITLE
Server crashing when entering vault

### ISSUE THREAD

**Issue by SpeedyDestroyer** [Iskallia/Vault-public#962]
When anyone in the server opens and load a vault. The server crashes with the "ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)" Error.

Server is hosted on a laptop with 20 GB of ram.

Vault Hunter Version [1.12.4] on 1.16.5

Crash report
https://pastebin.com/Te7t3R32

Any idea of fix?

**Comment by chico1992** [comment]
revert back to forge version 36.2.23 
you'll have to use java version 8_311 or 312 or older
