### ISSUE TITLE
Creating single player world will not load

### ISSUE THREAD

**Issue by LlamaLord427** [Iskallia/Vault-public#965]
**Describe the bug**
When creating a single player world it says "Not responding"

**To Reproduce**
1. Open mod on curse forge
2. Creat single player world
3. Minecraft says "Not Responding"
4. Gives error code: -1

**Expected behavior**

I expected it to load the world.

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.
error code: -1
**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version: 1.12.4

**Additional context**

Is this caused by the experimental content?
Will this be able to be fixed?
I really want to play Vault Hunters.

**Comment by bmemike** [comment]
This is typically due to not allocating enough RAM. Be sure you're giving your instance 8G.

**Comment by LlamaLord427** [comment]
How do you do that?

**Comment by bmemike** [comment]
https://vaulthunters.gg/installguide

**Comment by LlamaLord427** [comment]
it will load the world now but is some ties just crashes and gives error code: -805306369

**Comment by LlamaLord427** [comment]
Restarted computer and now works great. Thanks so much for the help. :P
