### ISSUE TITLE
Rift etching set not applying the bonus CDR

### ISSUE THREAD

**Issue by vasilislang** [Iskallia/Vault-public#979]
**Describe the bug**
Rift Armor set with 53% CDR base (should add up to 103% uncapped, 90% capped) doesnt show the correct amount under stats. CDR amount also seems to be more at 80% and not 90%
**To Reproduce**
1. Get a full set with rift etchings
2. get ~50%
3. look at stats page
4. compare CDR with a non rift set with 80% CDR

**Expected behavior**
Due to rift etching, CDR exceeds 80% up to 90% and shows the stats under stats page
**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.
![image](https://user-images.githubusercontent.com/97075284/172517377-b0923454-376d-4805-aa64-c075e3e1f66b.png)
![image](https://user-images.githubusercontent.com/97075284/172517471-f05981f3-a27d-4a29-9856-99a9d91a6e1c.png)
![image](https://user-images.githubusercontent.com/97075284/172517492-3b1584f7-794c-4fb5-b426-c1f6d1b38d0c.png)
![image](https://user-images.githubusercontent.com/97075284/172517510-3648e9ff-5655-4703-ab87-cfa51ee4d554.png)
![image](https://user-images.githubusercontent.com/97075284/172517546-4a373233-ee43-49ef-8c31-19ee8499e53c.png)

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.12.4

**Comment by HellFirePvP** [comment]
Conceptually a bit badly communicated i suppose.
It halves the cooldown.

Let's say you have 20 seconds cooldown on some ability.
With 50% CDR from gear, that gets pushed down to 10 seconds.
With the Rift Etching set, this 10 second period gets halved. So you end up with a cooldown of 5 seconds in this scenario.

Hence why it can't really be displayed with a number on the stats as it's dependent on the cooldown the ability/thing has.
