### ISSUE TITLE
chest problem

### ISSUE THREAD

**Issue by piranija** [Iskallia/Vault-public#98]
chest no have loot in the vault.

**Comment by ImreBoersma** [comment]
There are some rooms with decorative chests. Can you provide some more information?
Like screenshots of the location of the chests, Vault rarity

**Comment by iGoodie** [comment]
I shall close the issue, because it doesn't provide any details or trace about the issue you're facing.
Please share more information so that we can work on fixing it :) I can re-open, once more info is shared!
