### ISSUE TITLE
Error in datapack

### ISSUE THREAD

**Issue by Mullion11** [Iskallia/Vault-public#982]
**Describe the bug**
Missing textures.

**Expected behavior**
The game should load

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/107392164/173303436-8e85d469-b1a9-4a4b-9269-96d31b0ff1c7.png)

**Info (please complete the following information):**
- Single Player 
- The Vault Version  1.12.4

**Additional context**
![image](https://user-images.githubusercontent.com/107392164/173303729-074f3a58-ed7a-4823-9d63-282a1539d56a.png)
![image](https://user-images.githubusercontent.com/107392164/173303874-d41e3772-41c0-443e-8267-150907fa336a.png)

**Comment by bmemike** [comment]
You should start by reinstalling the pack. 

If you still have issues, share the full latest log (and not screenshots).

**Comment by Mullion11** [comment]
I am using curseforge. Is there a way I can do that without deleting my data?

**Comment by Mullion11** [comment]
I am using curseforge. Is there a way I can reinstall without deleting my data?

**Comment by Mullion11** [comment]
@bmemike

**Comment by Mullion11** [comment]
@bmemike
