### ISSUE TITLE
Can start a Vaulthunters world. I can still start a superflat world.

### ISSUE THREAD

**Issue by Sam-Cloud19** [Iskallia/Vault-public#985]

**Comment by bmemike** [comment]
Without some clarification and far more information, I don't believe anyone will be able to provide some assistance with whatever issue you're experiencing.

**Comment by Sam-Cloud19** [comment]
I actually managed to fix it by uninstsllibg microsoft onedrive

**Comment by iGoodie** [comment]
I apologize, but we are unable to provide any assistance without a detailed explanation or context.
Closing the issue for now. Please re-open by sharing some more info, if you're still experiencing the problem
